### ISSUE TITLE
Dashboard Verification?

### ISSUE THREAD

**Issue by steven-pozarycki** [jgyates/genmon#100]
Hi -
I believe I have the cable working and getting results to my webpage. 

Question: Are the stats for the monitoring page showing the "M" and "S" packet numbers increasing good?  I am guessing yes since it does show my serial number as correct and the exercise time every Saturday at 10am.

Screenshots below:
![status-page](https://user-images.githubusercontent.com/8644997/39068586-c4781f70-44aa-11e8-8d48-6c1be057980e.PNG)
![monitor-page](https://user-images.githubusercontent.com/8644997/39068598-cae4ff54-44aa-11e8-80b3-7d95f4d86cb9.PNG)
![maint-page](https://user-images.githubusercontent.com/8644997/39068600-ce406972-44aa-11e8-86d2-172b3b6fc349.PNG)

**Comment by jgyates** [comment]
Yes, your output looks good. The M and S are for the Master (Raspberry Pi) and Slave (Generator Controller) packet count. These should increase as time goes on. If they do not then you will get an error (i.e. Monitor Health will not be "OK"

**Comment by jgyates** [comment]
With minor mods to the genlog.py program you can log any text output. The current genlog.py program only logs the base status (running, stopped, ready, exercising, etc) when the status changes.

Changing the logic in the while loop to call this, for example:

     data = MyClientInterface.ProcessMonitorCommand("generator: status")

would log the status at the interval of your choosing.
