### ISSUE TITLE
Genmon MQTT MTLS

### ISSUE THREAD

**Issue by Daniel-dev22** [jgyates/genmon#1006]
Does genmon support mtls for mqtt. It appears to support ssl but not mtls? As in I don't see anywhere to provide a client certificate.

Or is the ca file all that I would need for mtls?

**Comment by jgyates** [comment]
The MQTT add on support SSL and TLS, but not MTLS

**Comment by jgyates** [comment]
The client cert file full path and filename is in the "SSL/TLS CA certificate file" setting.

**Comment by jgyates** [comment]
@Daniel-dev22,

Sorry, I don't know how to specifically answer your question. Here is what I do know: 

The MQTT support in genmon is based on the [paho MQTT python client](https://pypi.org/project/paho-mqtt/). The web interface exposes the options that allow most of the security options the client library supports. These options are SSL or TLS  and provide an option to supply a client side cert file ("SSL/TLS CA certificate file" setting). It also has the option to force the broker to supply a certificate ("Certificate Requirements" setting). 

Supplying a cert from the client and requiring one for the broker sounds like MTLS, but the paho client does not call it MTLS. It calls this TLS with a required broker certificate. I don't know enough about MTLS to now if that is the same thing.

I hope this helps.

**Comment by jgyates** [comment]
I updated the UI, wiki, add on and the comments in the conf file to support these two new parameters.  This will add two new (optional) entries in the web UI. The new entries will be added to the conf file by the UI so just update your software to the latest, enable the add on and set the client cert and key file path. Let me know if you have any issues.
