### ISSUE TITLE
CSS file has absolute paths

### ISSUE THREAD

**Issue by RalphBSz** [jgyates/genmon#1009]
I just got Genmon installed permanently to monitor our generator: 16kW air cooled, with an Evolution 1.0 panel; using a pHat for power and serial port, on a RPI 0W (no, not the Zero 2, the old-style 0). Genmon version is V1.19.01. Works great; thank you all involved for all the work you put into it.

I have a very minor bug report. And it only matters in a VERY unusual situation. Let me explain:

The web-based Genmon UI is designed to run on a dedicated port, in my case on generator.example.com:8000. That works great. When a web client (browser) connects to that port, the main program serves a web page which it calls "index.html", and that web page then loads things like libraries.min.js (a lot of JavaScript code) and libraries.min.css (the corresponding style sheets). The CSS file internally has references to other resources it loads, for example images: those are loaded from the images directory. (In the source distribution, those files are all in the static/ directory and subdirectories, and the libraries.min... files are built from more extensive libraries in other directories.)

The problem is: In the libraries.min.css file, some images are loaded from "/images/ui...". Note that this resource name starts with a leading slash, it is an absolute path! For the little web server that's built into Genmon (Flask or Werkzeug), that works fine.

In my particular case, this leads to a small problem, on a very circuitous path. The generator is on an internal network, which is not accessible from the outside world, only to approved machines inside our private network. That's obviously a good thing. But sometimes I'm not at home, and need to get into the internal network. That's handled by having a reverse tunnel going into the house, which is secured by several layers (username and passwords, cookies, unusual port numbers, the usual). The http tunnel goes to my main house server, let's call it house.example.com. So now how do I get to the generator? No problem at all: I just configure the web server on house.example.com to please proxy all accesses for https://house.example.com/generator over to http://generator.example.com:8000. Works fine: When one loads the page https://house.example.com/generator, it gets correctly rewritten to ...generator/index.html, Genmon on the generator.example.com machine serves the correct index.html page, it links to libraries.min.js and libraries.min.css which get proxied the same way, the various json files that are flowing back and forth all get handled perfectly. This all works because all the http files have **RELATIVE** path names, so the fact that my proxy prepends /generator/ to them doesn't matter.

Where this breaks: As described above, the libraries.min.css file has references to **ABSOLUTE** path names /images/ui..., and the web client outside will then try to load those from https://house.example.com/images/ui..., and those obviously don't exist! They would exist under https://house.example.com/generator/images/ui... (because that is proxied). This caused my web proxy server (a regular Apache) to throw out a handful of error messages; I didn't notice anything broken on the Genmon UI, but something somewhere must be missing.

So this is what I did to fix it: I went into the Genmon distribution, files static/libraries.min.css and css/jquery-ui.css, and in all places where it has url("/images..., I removed the leading slash. This does not break direct access to http://generator.example.com:8000, and the proxied use also works perfectly. There is roughly a dozen places where this happens, and as far as I can see, it is only in those two files.

A few questions: (a) I am completely not a JS, CSS or AJAX person; never dealt with this stuff before. Is my guess at the fix correct? (b) In jquery.idealform.css and libraries.min.css, there are references to url("../images/..., which resolve correctly; I wonder whether they could be simplified. (c) I have the fix in my Git repository, but I won't push it, unless you tell me to. (d) In general, is there something terribly wrong with the idea of proxying all of the Genmon UI into a subdirectory of another server? Security is not an issue, it's similar to a VPN,  with usernames and password.

### Expected Behavior

If the web UI is to be proxied into a subdirectory path, then it should only use relative paths to resources (such as images).
 
### Actual Behavior

In one place, it uses roughly a dozen absolute paths.

### Steps to Reproduce (including precondition)

See above, it's a bit of work: Set up a proxy that exposes the Genmon http server as a subdirectory of another server, then watch for error messages (403 codes) in the proxy server log.

### Screenshot or Pictures relating to the problem (if possible)

Some Apache log examples, first bad, then good:
192.168.0.66 - - [15/Jan/2024:18:51:14 -0800] "GET /images/ui-icons_222222_256x240.png HTTP/1.1" 403 199
192.168.0.66 - - [15/Jan/2024:19:13:55 -0800] "GET /generator/images/ui-icons_222222_256x240.png HTTP/1.1" 200 7006

### Your Environment

See above:
- Generator Model: Generac 62560 (16kW Guardian, air-cooled, Evolution 1)
- Genmon Logs: N/A
- Genmon Version: V1.19.01

**Comment by jgyates** [comment]
@RalphBSz 

That sounds reasonable. If you want to submit a pull request (PR) I can test out your changes and commit them. Alternatively you can post any changed CSS files as an attachment to this thread if you are not familiar with the PR process. You only need to update the CSS. The ibraries.min.css and ibraries.min.js files are generated from the ./static/js and ./static/css folders with closure-compiler.py. Let me know if you have any questions.

**Comment by RalphBSz** [comment]
Will prepare a pull request and attach it; will take a day or two, as there is urgent work and music stuff first.

**Comment by jgyates** [comment]
No worries. Thanks!
