### ISSUE TITLE
Battery Drain issues?

### ISSUE THREAD

**Issue by steven-pozarycki** [jgyates/genmon#101]
All,

I'm not sure if this normal. I hooked up the "MOTOPOWER 0609A 3.1Amp Waterproof Motorcycle USB Charger Kit SAE to USB Adapter" to my battery in the generator and noticed that yesterday the battery voltage was in the 13.7 to 13.9 range. This morning it is around 12.7 - 12.9.  The CPU usage of my Raspberry Pi is only around 5% or so.

Normal or no on the battery measurement?

-Steven

**Comment by jgyates** [comment]
Normal. This is your battery charger kicking on and off. Charging cycles vary but can last up to 18 hours according to the manual.
