### ISSUE TITLE
Undervoltage (Both Zero Crosses missing) : Alarm Code: 1902

### ISSUE THREAD

**Issue by STiFTW** [jgyates/genmon#1010]
### 
Have a problem with my Generac 17kW.  Just had a massive snow storm roll through, I did a test of the generator before the storm and everything was fine.  After about 30" of snow, blizzard force winds, and temps of -20F the generator failed its weekly self test and further manual tests with the error 'Undervoltage Both Zero Crosses missing)'. 

After a bit of research it could be the brushes, but I came across something that said frost on the slip ring could cause this and there was a software/firmware update that changed the warmup behavior to do a full warm-up before testing for voltage on the slip ring. 

I could really use some help finding a firmware update for my unit that includes the fix, but would not break my genmon setup.  I do my own maintenance, so it has been frustrating to not be able to find an update on my own.  I would also appreciate any other ideas/suggestions.  I'm trying to wrap a battery warmer around the generator coil to see if that is a temporary fix, and opened up and cleaned out all the snow from inside the unit. Detailed specs below, hardware V1.05 firmware V1.07

<img width="1254" alt="image" src="https://github.com/jgyates/genmon/assets/6237846/b455a4c7-7e43-4497-90c7-109d3557937a">

### Your Environment

Service :
        Service A Due : 185 hrs or 02/15/2025

        Service B Due : 385 hrs or 02/15/2027

        Battery Check Due : 02/16/2024

        Total Run Hours : 160.00 h

        Hardware Version : V1.05

        Firmware Version : V1.07

Maintenance :
    Model : 0062430

    Controller Detected : Evolution, Air Cooled

    Nominal RPM : 3600

    Rated kW : 17 kW

    Nominal Frequency : 60 Hz

    Fuel Type : Natural Gas

    Generator Phase : 1

    Engine Displacement : 992 cc

    kW Hours in last 30 days : 0.08 kWh

    Fuel Consumption in last 30 days : 52.17 cubic feet

    Total Power Log Fuel Consumption : 1536.93 cubic feet

    Run Hours in last 30 days : 0.71 h

    Run Hours in the last year : 13.40 h

    Controller Settings :
        Calibrate Current 1 : 1465

        Calibrate Current 2 : 1477

        Calibrate Volts : 1010

        Nominal Line Voltage : 240 V

        Rated Max Power : 17 kW

**Comment by STiFTW** [comment]
> You appear to have an Evolution 1.0. If that is the case you can upgrade your firmware via Generac maintenance technician an genmon will still work. Evolution 2.0 firmware is encrypted, beginning with version 1.10 but that still works with genmon. I don't know of a way to get firmware without going thru Generac.

I appreciate the information, I was worried about getting an encrypted version that would break GenMon. I'm hoping to find someone out there that might be able to help, but good to know if I call a service tech I won't lose my ability to use GenMon.

**Comment by jgyates** [comment]
So far I have not heard any reports of someone losing genmon access from a service visit. I still use a certified tech to service my generator.

**Comment by jgyates** [comment]
I am going to close this thread, but feel free to post any follow up status or questions to this threa.

**Comment by grsthegreat** [comment]
Updates will not lock up genmon on evolution 1 generators. I am a service tech on generac units. My own evolution 1 unit has most current updates, no issues.

I have several customers that have icing occur on brushes, both on evolution and previous makes of controllers. I found that by placing a battery heat pad below the stator back towards the exhaust fan area. This will produce enough heat to prevent icing. I don’t like actually placing pad on the stator due to worry about heat harming windings directly.
![Uploading 20221213_151419.jpeg…]()

**Comment by grsthegreat** [comment]
I use generacs flat heat pad. Not the wrapping type. The wrapping type heat pad, when used on batteries can also boil off batteries and make them explode…..ask me how I know.

those battery heating pads cause more problems than there worth.

**Comment by grsthegreat** [comment]
I tried to add photos of the pad inplace to warm stator, but they don’t show up

**Comment by jgyates** [comment]
If yo use a desktop browser you can drop the photo in the comment window.

**Comment by grsthegreat** [comment]
heres the place i install them.


![Uploading 20221213_151419.jpg…]()

**Comment by STiFTW** [comment]
> heres what i do
> 
> ![20221213_151419](https://private-user-images.githubusercontent.com/50511024/300050570-1c1fe65d-df60-4d21-a24f-3d7603888ff5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NDY5MTIsIm5iZiI6MTcwNjc0NjYxMiwicGF0aCI6Ii81MDUxMTAyNC8zMDAwNTA1NzAtMWMxZmU2NWQtZGY2MC00ZDIxLWEyNGYtM2Q3NjAzODg4ZmY1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAwMTY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNGQ0MjhiZDIyMmVlNDA2NjBhOTU5ZTYwMGE4NTFiNjc0YTdlZjU0NThjZTAzODAyY2FmYTY1NjBkZjQ2OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tfC6Mzn6koI7Qxgj3WxhtrMaasWIgZJZ6v1jk7ssq2M)

Thanks for the picture, I appreciate the tip!  Here's hoping that solves my issue in the future. 

<img width="1110" alt="image" src="https://github.com/jgyates/genmon/assets/6237846/336fafee-960c-495b-9a2a-69ecb0225528">
