### ISSUE TITLE
Unable to clone genmon wiki to a windows repository due to embedded colons in file/directory names

### ISSUE THREAD

**Issue by weffz** [jgyates/genmon#104]
I have spent the last few hours puzzling as to why I haven't been able to create a new clone of the genmon wiki repository under Windows - and have finally found the reason why.  It has been a while since I came back to working on genmon and hopefully plan to complete the installation once I have installed some Acoustiblok noise absoption walls around my Generac generator (while still allowing sufficient ventilation.) So when I went to create a new clone of the Wiki which has worked previously I found it no longer did.

This Issue is as a result of the "recent" inclusion of colon characters in the Wiki headings that are disallowed in directory and filenames under Windows. 

It is currently not possible to clone the Wiki in a Windows environment due to the embedded colons now present in most of the section headings of the Wiki.

Windows does not allow directory or file names to include an embedded colon nor a number of other reserved characters such as < > : " / \ | ? *   plus some other restrictions (see https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx for the details of the File and Directory naming conventions)

So entries in the top level of the genmon Wiki like "1: Software Overview" and "2: Hardware" essentially create directories in their Unix repository on github that cannot be cloned under Windows.
Instead Windows treats the 1: as a drive letter that does not exist so the directory creation fails and you get a git listing  as follows:

W:\rasp-pi-project\wiki> git clone https://github.com/jgyates/genmon.wiki.git
Cloning into 'genmon.wiki'...
remote: Counting objects: 1015, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 1015 (delta 4), reused 0 (delta 0), pack-reused 1006
Receiving objects: 100% (1015/1015), 161.12 KiB | 0 bytes/s, done.
Resolving deltas: 100% (651/651), done.
error: unable to create file 1:-Software-Overview.md: No such file or directory
error: unable to create file 2:-Hardware.md: No such file or directory
error: unable to create file 3.1:-Making-a-Cable.md: No such file or directory
error: unable to create file 3.2:-Setup-Your-Pi-and-Serial-Port.md: No such file or directory
error: unable to create file 3.3:-Setup-genmon-software.md: No such file or directory
error: unable to create file 3.4:-Manually-installing-genmon-software-(not-using-the-setup-script).md: No such file or directory
error: unable to create file 4:-Updating-to-the-Latest-Version.md: No such file or directory
error: unable to create file Appendix-1-:-Design.md: No such file or directory
error: unable to create file Appendix-2:-Generator-Controller-Information-(Registers,-Protocol,-etc.).md: No such file or directory
error: unable to create file Appendix-3:-Interfacing-GenMon-to-External-Applications.md: No such file or directory
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

This used to work and allowed Windows users to have a local copy of the Wiki - but since the addition of the colons as pseudo section headings this now fails.

It is still possible to clone the Wiki under Unix as colons are legal under Unix within filenames- but for those of us that had Windows copies they will no longer work.

Can this be changed please - and the colons removed ? There are 10 colons in the Section Headers but there may also be other colons within filenames and/or directory names I am not aware of.

As an alternative you could change the headings to be "[1] Software Overview"  and "[2] Hardware" etc. as the characters [ and ] are allowed which looks fairly similar as a separator.

Regards

Geoff

**Comment by jgyates** [comment]
Colons are now removed.
