### ISSUE TITLE
Switch position under "Maintenance" not showing the status

### ISSUE THREAD

**Issue by nrm94ee330** [jgyates/genmon#1051]
### Steps to Reproduce

![image](https://github.com/jgyates/genmon/assets/44410964/2fd7a117-21c7-4cbb-984d-afa0c769566c)

![image](https://github.com/jgyates/genmon/assets/44410964/b7ebb732-6492-4aa6-b4da-e9508fc7858a)

Since recently, the switch position color has gone away.. the clicking seems to be working though, as it shows correctly under "Status page correctly"

### Expected Result

The button used to show the colored button based on the switch status

### Actual Result

The buttons are always the same color and do not change based on the switch status

### Version Info

Genmon Version V1.19.01

**Comment by jgyates** [comment]
what is your generator model? It is and evolution liquid cooled or a Nexus liquid cooled? It helps if I can test simulating the same model. Not all models have this setting on the Maintenance page.

**Comment by nrm94ee330** [comment]
> what is your generator model? It is and evolution liquid cooled or a Nexus liquid cooled? It helps if I can test simulating the same model. Not all models have this setting on the Maintenance page.

Model : RG03224ANAX
Controller : Evolution, Liquid Cooled

**Comment by jgyates** [comment]
Thanks for finding this. I checked in an update that corrects this issue. The version number has not changed so just update from the about page and refresh your browser.

Let me know if you have any issues.

**Comment by nrm94ee330** [comment]
awesome!  thank you

**Comment by nrm94ee330** [comment]
![image](https://github.com/jgyates/genmon/assets/44410964/2e605b97-9ba5-46c1-9e85-1ddbccab5657)
 Is this changed now, does it not show green color button ?

**Comment by jgyates** [comment]
No you are not crazy. I downloaded a few versions back and found a build that had the disabled buttons colored green,
<img width="780" alt="Screenshot 2024-02-13 at 6 53 04 PM" src="https://github.com/jgyates/genmon/assets/4513286/96d8a775-7c4b-45ab-8a27-0197c022a50a">

Not sure where or why this got dropped but I will look into it. There is the possibility that this was intentional, I honestly don't remember. I will update this thread when I have more info.

**Comment by jgyates** [comment]
I checked in an update that corrects this issue and reverts it back to the the way it was originally. Thanks for pointing this out. Let me know if you have any issues.

**Comment by nrm94ee330** [comment]
Yup, just updated.. worked perfectly..Thank you very much. BTW, I started seeing actual power usage in the recent updates not just 0 and max value.. Thank you for an amazing project!
