### ISSUE TITLE
paho-mqtt 2.0 compatibility

### ISSUE THREAD

**Issue by sahlawat** [jgyates/genmon#1054]
### Steps to Reproduce

new installation now pulls in paho-mqtt 2.0.0

need to downgrade to 1.6.1
sudo pip3 install paho-mqtt==1.6.1

### Expected Result

mqtt client should work

### Actual Result

mqtt client does not work

### Version Info

V1.19.01

### Logs

Error in MyMQTT init: __init__() missing 1 required positional argument: 'callback_api_version' : genmqtt.py:496

**Comment by jgyates** [comment]
done. Let me know if you have any issues.
