### ISSUE TITLE
Export per-leg current readings via MQTT

### ISSUE THREAD

**Issue by gmn42** [jgyates/genmon#1062]
It's great to be able to check the per-leg current on Evo controllers in the latest version of the genmon, thank you!  However, these values don't seem to be exported via MQTT; I still only see the `generator/Status/Engine/Output Current/value` messages containing what seems to be the combined 240V current. It would be great if the individual 120V currents were exported, so I could add them to my Home Assistant display to monitor the balance.

**Comment by jgyates** [comment]
I added this ability. Note that it is also in the text at the bottom of the status page (Status/Engine) and the MQTT topic path is based on this so it would be generator/Status/Engine/Current L1/value

Let me know if you have any issues or questions.
