### ISSUE TITLE
Web update was not successful

### ISSUE THREAD

**Issue by hokie21** [jgyates/genmon#1070]
### Steps to Reproduce

I ran a web update with current version V1.18.14 and expected new version v1.19.02. Everything appeared to be fine. No errors were shown during the update process.

### Expected Result

Current version: V1.19.02

### Actual Result

Following the unsuccessful update, the current version is shown as V1.18.14 on the about web page.
I then tried to run bash .genmonmaint.sh update from the SSH command line.
This script gives  me just a prompt with nothing else shown. No error was shown, but no text from the script was shown either.
startgenmon.sh works just fine to start or stop genmon.
Should I just reload everything and start over?

### Version Info

current version V1.18.14 and expected new version v1.19.02. 

### Logs

[genmon_logs (2).tar.gz](https://github.com/jgyates/genmon/files/14498778/genmon_logs.2.tar.gz)

**Comment by jgyates** [comment]
Have you ever updated genmon successfully before? If you did not install per the wiki instructions then the upgrade process will not work.

You mentioned a prompt when running genmonmaint.sh, can you provide more details or a screen shot? I don't have enough info to provide any suggestions.

**Comment by hokie21** [comment]
I've updated it in the past. I was able to look at the "history" command and I confirmed that I did use the git command for the installation. Here is what I see when I run genmonmaint.sh. 

![image](https://github.com/jgyates/genmon/assets/37786152/bf7dc7a5-be99-492f-9fa7-765bb4def152)

**Comment by jgyates** [comment]
Try this:

     bash ./genmonmaint.sh -u

**Comment by jgyates** [comment]
Once you update then you must restart genmon like this.

    bash ./strartgenmon.sh restart

**Comment by hokie21** [comment]
That fixed it. Thank you!
