### ISSUE TITLE
Firmware 1.18 ? 

### ISSUE THREAD

**Issue by farberm** [jgyates/genmon#1072]
I had my generator year maintenance and the service guy updated my firmware from 1.09 to 1.18 without asking me. Is there gong to be any issues? I do not see a website as to the changes in the firmware etc?

**Comment by jgyates** [comment]
Yes, this version works with genmon. You will see a few random modbus exceptions orruring in the comm stats but it works well other than that. See the wiki page regarding Known Issues for more details.

**Comment by jgyates** [comment]
https://github.com/jgyates/genmon/wiki/Appendix-D-Known-Issues
