### ISSUE TITLE
Status page not showing any detail during outage

### ISSUE THREAD

**Issue by jonathanpisarczyk** [jgyates/genmon#109]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below.

### Expected Behavior

Status page isn't showing any details during outage.  

### Actual Behavior

Status page is blank during outage.  

### Screenshot on This Problem (if possible)

![genmon outage no status](https://user-images.githubusercontent.com/36710072/39643396-9b701bde-4fa2-11e8-821a-6b1ea43c9a3c.png)

### Your Environment

- Genereator Model: Evolution Air Cooled 20kw
- Generator Registers: 
![genmon registers](https://user-images.githubusercontent.com/36710072/39643462-da03d76e-4fa2-11e8-862f-d973c02145a2.png)

- Genmon Version: 1.7.5

**Comment by jgyates** [comment]
Hi @jonathanpisarczyk 

I will need the following info:

* Your /var/log/genmon.log file. You can attached this file to your reply in this thread.
* Your register list ( the picture you sent was only a partial list and I can not simulate your generator with this screen capture, so I will need your registers in text form)

You can send your registers a few ways:

1) run ClientInterface.py

    python Clientinterface.py
    generator: registers

Then copy the output of the listed registers to a file, then paste them into this issue thread. 

2) run ClientInterface.py

    python Clientinterface.py
    generator: sendregisters

this will email the registers to me.

**Comment by jgyates** [comment]
One other question: Do you see any output when you issue this command with ClientInterface?

    generator: status

Can you view other pages on the web page or is the status page the only issue?

**Comment by jonathanpisarczyk** [comment]
[genmon.log](https://github.com/jgyates/genmon/files/1975502/genmon.log)

**Comment by jgyates** [comment]
OK. that helps with the registers and log. do see a problem. 

Do you see any errors in Chrome if you view the developer tools console? To view the browser console on Windows press CTRL-SHIFT-J and paste the windows to this thread. What version of Chrome are you using?

What method did you use to update genmon?

**Comment by jonathanpisarczyk** [comment]
I updated genmon with browser. 
Google Chrome is up to date Version 66.0.3359.139 (Official Build) (64-bit)
I don't see any erros.

![genmondevconsole](https://user-images.githubusercontent.com/36710072/39646194-9e53a892-4fa8-11e8-99b9-3081032f13b5.png)

**Comment by jgyates** [comment]
OK. I found the problem. Give me a few min to fix and test....

**Comment by jgyates** [comment]
OK, the update is checked in. This was a bug I introduced on the 3rd. Thanks for helping find this.

**Comment by jgyates** [comment]
Let me know if you still have any issues.

**Comment by jonathanpisarczyk** [comment]
Back in business thanks @jgyates !!!
![genmonstatusworking](https://user-images.githubusercontent.com/36710072/39648812-8b7b6274-4fb1-11e8-82b5-6add51d5b2b8.png)
