### ISSUE TITLE
Backup/Restore

### ISSUE THREAD

**Issue by jcleek** [jgyates/genmon#1109]
Can you add a feature to back up and restore settings?

**Comment by jgyates** [comment]
you can backup your genmon settings from the About page on the web interface. This will download a zip file with the genmon config and data files. The restore is not currently automated but the procedure is written in the wiki: https://github.com/jgyates/genmon/wiki/Appendix-M-Tips-and-Tricks-useful-for-Genmon#restoring-settings-from-a-backup
