### ISSUE TITLE
Donation via Google Pay

### ISSUE THREAD

**Issue by TikiGuy** [jgyates/genmon#111]
I couldn't find a good way to contact you directly but I'd like to donate to you because this project is awesome.  The issue is I don't use PayPal.  Is it possible to get a donation to you via Google Pay?

**Comment by jgyates** [comment]
Hi @TikiGuy 

You can contact me on google at firstname.lastname@gmail.com (See below) You should get an email with this message so I will delete this thread shortly to keep spammers at bay. 

thank
Jason Yates
