### ISSUE TITLE
Can you support some sort of auth token or basic authentication for API calls

### ISSUE THREAD

**Issue by ericsmith66** [jgyates/genmon#1123]
I am making a plugin for HomeKit to allow the generator to appear as a switch in Apple Home. Unfortunately I have been unable to make API call into the genome server when SSL and Login ID/Password are enabled. I tried using Basic Auth and that did not work. 

It would be great if there was a way to authenticate via an API or use basic AUTH.

Thanks 
Eric Smith

**Comment by skipfire** [comment]
I integrated by calling the login with a FormPost and then using the same connection to call the status json, it isn't API or basic auth but it does work.

**Comment by ericsmith66** [comment]
Thanks , I will give it a shot

**Comment by ericsmith66** [comment]
It worked fine. you need to copy the session cookie to authenticate between calls. There are a couple of redirects that happen on login. but other than that it worked fine. I have SPAN.io breaker panels which also has an API so I am wiring the two together.  Still early days.

**Comment by jgyates** [comment]
Sounds good. Thanks for the update
