### ISSUE TITLE
R200 Controller Support?

### ISSUE THREAD

**Issue by tracerrx** [jgyates/genmon#113]
I have a Generac 45kw propane genset equipped with an R200 controller ([manual here](http://soa.generac.com/manuals/4376695/0F9784)).  Has anyone tested with this?  If so is there a wiring diagram?

**Comment by jgyates** [comment]
The short answer is, no. This project will not work with the R200. 

The R200 does not appear to have a serial port interface, which is the method that is used to support the other Generac controllers in this project. In theory one could attempt to connect to the LEDs on the controller board with GPIO inputs with a raspberry pi, but this project does not support that.
