### ISSUE TITLE
Output Voltage graph nominal value not matching

### ISSUE THREAD

**Issue by rsockanc** [jgyates/genmon#1139]
### Steps to Reproduce

![image](https://github.com/jgyates/genmon/assets/24508741/6a2148c0-4c78-467e-a695-5a7404806f93)

![image](https://github.com/jgyates/genmon/assets/24508741/be7cfe6d-18f3-4afa-964d-45563d3ce826)

### Expected Result

graph green center would be at 220

### Actual Result

is set to 240

### Version Info

Version V1.19.03

**Comment by jgyates** [comment]
You did not include your generator / controller type or logs so I am assuming you have a Evoution/Nexus.

Do you have "Use Nominal Volts Override" enabled on the Advanced Setting page?

**Comment by rsockanc** [comment]
How embarrassing, I have the checkbox for that value and hit, save, but forgot to restart services. Issue can be closed.On Jun 22, 2024, at 10:10 AM, jgyates ***@***.***> wrote:﻿
You did not include your generator / controller type or logs so I am assuming you have a Evoution/Nexus.
Do you have "Use Nominal Volts Override" enabled on the Advanced Setting page?

**Comment by jgyates** [comment]
No worries. Have a good one.
