### ISSUE TITLE
Status color key

### ISSUE THREAD

**Issue by griffths** [jgyates/genmon#1151]
I would be helpful to have a key that indicters what the different status colors on the monitor page represent.

I believe this is what the different colors represent and likely overlooked it, but couldn't find it mentioned anywhere in the Wiki.

In either case, it would be useful to have it on the monitor page somewhere.

Yellow - Service Due
Green - Nominal
Blue - Running (exercise or outage?)
Red - Trouble

Other colors?

**Comment by jgyates** [comment]
@griffths 

This info is tucked away in the docs related to the web server (genserv.py) as this is the component that determines the colors:

https://github.com/jgyates/genmon/wiki/1----Software-Overview#genservpy-web-applicationoptional

The web interface menu will change colors based on your generators status:

Gold / Yellow - Service Due
Green - Switch in Auto / Ready
Red - Alarm
Blue - Exercise
Black - Switch Off
Gray - Running in Manual
Dark Green (Blue / Green ) Running

note that not all generators support controller initiated exercise cycles (e.g. some industrial models) so some of these colors may not apply to non Generac Evolution / Nexus models.
