### ISSUE TITLE
Pushover

### ISSUE THREAD

**Issue by darkstar2002** [jgyates/genmon#116]
When trying to get pushover to work on startup it will fail with a connection refused in the logs.  If I kill the pushover part and start it manualy it will work correctly.  Maybe there needs to be some kind of delay on the pushover script startup?

**Comment by jgyates** [comment]
I checked in an update that should help. I made the libraries used by the support programs retry three times is they fail to connect. The base issue is that the way python schedules threads is a bit unpredictable so the thread in genmon that accepts client connections has not been tasked yet. The updated myclient.py and mynofity.py should correct this issue. Let me know if you still have a problem after an update.

**Comment by darkstar2002** [comment]
Just upgraded and then did a reboot and looks like it works.
