### ISSUE TITLE
Pre-Nexus Controller. Genmon won't report RPM or frequency to webui it's just stuck at 0 rpm and 0 Hz but everything else works and monitors fine

### ISSUE THREAD

**Issue by TheawesomeMCB** [jgyates/genmon#1188]
### Steps to Reproduce

1. Plug into control panel
2. boot up genmon
3. turn on generator so engine is running
4. No output on page

### Expected Result

It shows rpm and frequency

### Actual Result

It's at 0 for both
![rpm and hz](https://github.com/user-attachments/assets/602995f6-f4cf-487f-bc36-86b0759ec869)

### Version Info

V1.19.03

**Comment by jgyates** [comment]
I would need to see your logs/registers, which can be submitted from the about page in the web ui.  Preferably submit the logs when your generator is running. 

You need to have outbound email setup and functional on the settings page to submit your logs/registers.

This is just a guess but it could be that some versions of the Pre Nexus firmware did not support full functionality.

**Comment by TheawesomeMCB** [comment]
> I would need to see your logs/registers, which can be submitted from the about page in the web ui. Preferably submit the logs when your generator is running.
> 
> You need to have outbound email setup and functional on the settings page to submit your logs/registers.
> 
> This is just a guess but it could be that some versions of the Pre Nexus firmware did not support full functionality.

Okay I just sent them. It's the one that was submitted at 2:33:11PM

**Comment by jgyates** [comment]
I got your logs. It looks like the modbus registers for RPM and Frequency are all zeros. I also compared your firmware version (1.10) to the other two sets of registers that people have submitted for Pre-Nexus models. Yours is not the lowest firmware. I do not have another set of Pre-Nexus registers while the generator is running so this could be a limitation of the pre-nexus firmware. 

If anyone else using a Pre-Nexus with genmon can weigh in that would be helpful.

**Comment by TheawesomeMCB** [comment]
> I got your logs. It looks like the modbus registers for RPM and Frequency are all zeros. I also compared your firmware version (1.10) to the other two sets of registers that people have submitted for Pre-Nexus models. Yours is not the lowest firmware. I do not have another set of Pre-Nexus registers while the generator is running so this could be a limitation of the pre-nexus firmware.
> 
> If anyone else using a Pre-Nexus with genmon can weigh in that would be helpful.

Soooo good news, it actually did start reporting. So compared to the other gauges it takes anywhere from 45-60 seconds before it starts reporting the RPM and frequency. It updates fast enough that the generator will say: “Running” but in terms of the rpm and hertz it takes a bit before it starts reporting that. So there’s just an massive delay before it starts reading the rpm and frequency.

![IMG_4245](https://github.com/user-attachments/assets/b8fdd559-409e-4344-86d9-1f6759c53f6c)

**Comment by jgyates** [comment]
That is great. Thanks for letting me know. I am going to close this for now but feel free to post any follow up to this thread.
