### ISSUE TITLE
External Temperature Sensor

### ISSUE THREAD

**Issue by philruel** [jgyates/genmon#1204]
Hi,
What values should I put to have a dial from -40 to 50 C.  Right now, I have 170 Nominal and 250 Maximum and the dial is shown bellow.

![image](https://github.com/user-attachments/assets/add2c3bd-c5a9-42a8-aba9-87c28056dc71)

![image](https://github.com/user-attachments/assets/a8c2403c-6e7a-499e-8abf-0a97bb894aca)

Thank you!

**Comment by jgyates** [comment]
I will have to make a mod to gentemp.py to accommodate a gauge that starts at a value below zero. I will update this thread when I have made the change.

**Comment by jgyates** [comment]
I updated the software to support non zero minimum values from this add on. 

first, update the software from the about page, then add the minimum value to the add on settings. Let me know if you have any issues or questions.

**Comment by zachliu** [comment]
So the maximum value is the max on the dial. Then what exactly is the "nominal" value? The almighty internet explains it as "the typical value of the sensor's output". But I still don't understand why we need them here. Shouldn't we only need min and max for a dial?

**Comment by jgyates** [comment]
Nominal values help determine where the gauge green area ends and the yellow begins. The external temp method does not allow the input of the exact tuning of the gauge coloring (to keep things simple) so it just added a fixed value to the nominal to determine where the yellow starts and another fixed value to where the red starts.

**Comment by zachliu** [comment]
ohhh, so the fixed values are 20F and 40F

![oh that's why](https://github.com/user-attachments/assets/47f5754b-e811-486f-87f4-16d9fc98c42e)

**Comment by jgyates** [comment]
:)

**Comment by zachliu** [comment]
i naively thought i could submit a PR to add this info to the tool tip :joy: 
 
![2024-10-20_22-13](https://github.com/user-attachments/assets/3f0a1e1d-3493-4ddb-a0fc-55f8f987530f)

**Comment by jgyates** [comment]
fyi, the latest update corrects the typo and added a sentence to give more details on the nominal, max and minimum values

**Comment by zachliu** [comment]
yep, i noticed. but the tool tip doesn't get texts from `conf/gentemp.conf` right?

**Comment by jgyates** [comment]
correct. The [add on tool tips are in genserv.py](https://github.com/jgyates/genmon/blob/b5a81ca12d1b1d7fe00e9b6bcf9ce350b0ab521e/genserv.py#L2087)

**Comment by zachliu** [comment]
damn, forgot to add `""` when i did the search, that's why i couldn't find where they are...
