### ISSUE TITLE
External Tank Gauge shows zero 

### ISSUE THREAD

**Issue by lampe208** [jgyates/genmon#1218]
### Steps to Reproduce

![image](https://github.com/user-attachments/assets/44d49ecc-3e24-4710-a366-fc0f2052d087)

### Expected Result

Tank utiliity app shows correct reading but gen mon is zero.  The batteries were low and were replaced prior to replacing all of a sudden the gauge was zero. 

### Actual Result

[genmon_logs.tar.gz](https://github.com/user-attachments/files/18170450/genmon_logs.tar.gz)

### Version Info

v1.19.04

**Comment by lampe208** [comment]
actual reading should be 30%

**Comment by lampe208** [comment]
Im also getting notices that the tank is below zero?   I confirmed tank reading at tank visual at 30%

**Comment by jgyates** [comment]
I don't really have enough info to make anything but a guess.

You mentioned that you are getting notices that the tank is below zero. What is the message? Is this sent from genmon or and add on or the tank utility app.

You logs show that the request is being rejected by the tank utility server. your gentankutility.log file is filled with this error:

2024-12-17 13:27:08,798 : tankutility: Error logging in, error code: 400
2024-12-17 13:27:08,800 : Error logging in in TankCheckThread, retrying

This error should have nothing to do with the tank sensor batteries as the add on does not read from the sensor directly but from the online readings stored by the tank utility. Has your password changed recently and if so did you update the add on setting?

**Comment by lampe208** [comment]
Time: 02:04:19 PM
Date: Tue 17-Dec-2024
Warning: The estimated fuel in the tank is at or below 10%. Fuel Level is
0.0%



Above is the email .  What’s weird is it’s sending the notice but it’s in
accurate. I’ll check the password.

**Comment by lampe208** [comment]
thank you very much. I fixed it. I changed the password. It's not accurate.

**Comment by lampe208** [comment]
Now accurate

**Comment by jgyates** [comment]
I have not received any logs today. Is your outbound email setup and functional? This is required to submit logs from the About page.

What version of the software are you using?

**Comment by lampe208** [comment]
You are not running the latest version.
    Current Version: V1.19.05
    New Version: V1.19.06
[image: image.png]
Im getting error on the email as well when I test it.

**Comment by jgyates** [comment]
you did not mention or show the scree capture of the error. 

If you are responding to this thread in email, github will strip any attached photos. To submit a screencap or photo you have to attach it from the github web interface.

Have you ever updated the software successfully before? If not, did you follow the directions for installation here: https://github.com/jgyates/genmon/wiki/3.3--Setup-genmon-software

if you did not use the "git clone" command as mentioned in the link then your software updates will not work.

**Comment by lampe208** [comment]
[](

<img width="1558" height="844" alt="Image" src="https://github.com/user-attachments/assets/18be8d8e-2b14-4a3e-811c-f70769a0ceae" />

this is the error when i do a test email settings

**Comment by lampe208** [comment]
ok will do

**Comment by lampe208** [comment]
This morning I started getting emails that the tank is low so I know it’s
communicating. I did a test email that works. I did the update that works.
However now I have no dashboard no visuals like a hand with all the gauges.

**Comment by lampe208** [comment]
I have not refreshed the browser. I do have gauges visible, but no readings
on any gauges. I do have CPU tip, which is my raspberry pie temperature
that’s it

**Comment by jgyates** [comment]
I received you logs. You have several issues.

You first issue is that your serial comms are not working. From the logs you send here is the summary of communication stats:

Comm Stats :
   Packet Count : M: 77, S: 5
   CRC Errors : 0
   CRC Percent Errors : 0.00%
   Timeout Errors : 70
   Timeout Percent Errors : 90.91%
   Modbus Exceptions : 3
   Validation Errors : 0
   Sync Errors : 0
   Invalid Data : 0
   Discarded Bytes : 1
   Comm Restarts : 0
   Packets Per Second : 0.38
   Average Transaction Time : 0.0412 sec
   Modbus Transport : Serial
   Serial Data Rate : 9600

You should be able to see these your self on the Monitor page. You logs indicate that genmon is only running for 3 minutes so I would not expect the web interface to come up yet with not serial data. The software would need to attempt every modbus read at least once so if you waited about 10 - 15 min you will see a default web page. If serial comms are not working the software can not detect any thing about the controller so all of your data displayed will be zero or default values.

The next issue is that you email still has a configuration error. You have this error in /var/log/mymail.log:

2025-07-25 06:48:06,405 : Error selecting mail folder! (select)

This indicates that you have an inbound email folder that does not exist. If you are not using inbound email command then do not enable the option "Optional - Inbound Email Commands Processing"

I also noticed that there are several add on programs enabled that do not appear to be configured correctly. I would recommend disabling any add on programs that you are not using as this just takes system resources. For example, you have the "Notifications via SMS - LTE Hat" add on enabled, but you do not appear to have the additional hardware requried to run this add on.

You also have the SMS Twillio add on enabled, not sure if you are using this but there are errors in the log. This could be caused by your previous network issuse, but if you are not using and active Twillio account you should disable this add on.

You have the tank utility enabled but the error in /var/log/gentankutil.log is this:

2025-07-25 06:44:38,311 : tankutility: Error logging in, error code: 400
2025-07-25 06:44:38,312 : Error logging in in TankCheckThread, retrying

Has this add on worked for you before?

The add on for Slack, Alexa and email to SMS are also enabled, all of these have errors related to network isseus which may be related to your previous netowrk problem that was solved with a reboot, but I would recommend disabling any add that you are not using.

Your main issue is that your  serial comms are not working. I would inspect your cabling and then see the serial troublshooting guide: https://github.com/jgyates/genmon/wiki/3.6---Serial-Troubleshooting

Regarding your tank reading zero, if you still see this after you serial comms are restored, the next question is this: is your tank utility a LTE or Wifi version. If it is the LTE version, you may have the issue described here: https://github.com/jgyates/genmon/issues/1284

**Comment by lampe208** [comment]
I have resolved the issues .  Simply rebooting the pi has pretty much
solved the problem.

**Comment by lampe208** [comment]
Thank you sir.  I did send a separate email.  I managed to ssh into the pi
remotely and it all seems to be working.  I will disable those add ons.  I
do use slack, but twilo is not working so I will disable that as well.

Thanks again.

**Comment by lampe208** [comment]
I have also lost my tank monitor window

**Comment by lampe208** [comment]
Thanks a bunch. I will check it out.

**Comment by lampe208** [comment]
***@***.****:*~ $*  ls -la /dev/ser*

lrwxrwxrwx 1 root root 5 Dec 13 14:24 */dev/serial1* -> *ttyS0*

***@***.****:*~ $* ls -la /dev/ttyA*

ls: cannot access '/dev/ttyA*': No such file or directory

***@***.****:*~ $* cd genmon

***@***.****:*~/genmon $* cd OtherApps

***@***.****:*~/genmon/OtherApps $* sudo python3
serialconfig.py -c


Using files: /boot/config.txt and /boot/cmdline.txt


Model: Raspberry Pi 3 Model B Rev 1.2


Checking : Is enable UART in boot config: Fail

Checking : Is BT overlay disabled: Fail

Checking : Serial console command line removed: OK

Checking : Serial console service disabled: OK

Checking : BT service disabled: OK


Serial port may not work as expected. Not all required settings changes
were detected.

**Comment by lampe208** [comment]
Still cannot access the 192.168.4.181 via chrome or safari or firefox.

**Comment by jgyates** [comment]
So what changed? Your serial ports were not present before and now they are. Did you do anything to make that happen or did they just show up after not being there? This information is required to determine if you still have a problem that can be solved without replacing hardware.

You mentioned "After redoing the software here is the output". Can you give more details on what you did to redo the software?

You also posted contradictory data with the output of the ClientInterface.py command. 

You appear to have an underlying issue of your serial port went away and then came back. That behavior will cause all of the behavior you are seeing (no serial ports, genmon not loading successfully, genmon reporting communication failures if the port goes away after genmon is loaded).

It is possible you have a failing SD card and this is causing the serial port to not be recognized by the OS, which would cause genmon to fail. 

The data you are posting needs context, for example if you show the serial ports with the "ls" command, is genmon working at that time? If genmon stops working are the serial ports active?

**Comment by lampe208** [comment]
i just reloaded the software then ran thru the checks .

**Comment by lampe208** [comment]
so esentially i reloaded the genmon software as if I just started to do this project.   I then ran the check of the serial ports after you sent me how to see what kind I had.  So the last post is the checking of what serial port i have.   What now should I do now that we know what type of serial port I have according to my last post.?

**Comment by lampe208** [comment]
pi@raspberrypigenerator:~/genmon/OtherApps $ sudo python3 serialconfig.py -c

Using files: /boot/config.txt and /boot/cmdline.txt

Model: Raspberry Pi 3 Model B Rev 1.2

Checking : Is enable UART in boot config: OK
Checking : Is BT overlay disabled: Fail
Checking : Serial console command line removed: OK
Checking : Serial console service disabled: OK
Checking : BT service disabled: Fail

Serial port may not work as expected. Not all required settings changes were detected.

This is the latest as of now .

**Comment by lampe208** [comment]
>generator: monitor


Monitor :


    Generator Monitor Stats :

        Monitor Health : OK

        Controller : Evolution 2.0, Air Cooled

        Run time : Generator Monitor running for 5:16:01.

        Power log file size : 0.22 MB of 15.00 MB

        Generator Monitor Version : V1.19.07

        Update Available : No



    Communication Stats :

        Packet Count : M: 611332, S: 611331

        CRC Errors : 0

        CRC Percent Errors : 0.00%

        Timeout Errors : 0

        Timeout Percent Errors : 0.00%

        Modbus Exceptions : 40

        Validation Errors : 0

        Sync Errors : 0

        Invalid Data : 0

        Discarded Bytes : 0

        Comm Restarts : 0

        Packets Per Second : 64.48

        Average Transaction Time : 0.0306 sec

        Modbus Transport : Serial

        Serial Data Rate : 9600



    Platform Stats :

        CPU Temperature : 60.80 F

        Pi Model : Raspberry Pi 3 Model B Rev 1.2

        Pi CPU Frequency Throttling : OK

        Pi ARM Frequency Cap : OK

        Pi Undervoltage : OK

        CPU Utilization : 1.4%

        OS Name : Raspbian GNU/Linux

        OS Version : 10 (buster)

        System Uptime : 10:32:44

        Network Interface Used : wlan0

        WLAN Signal Level : -65 dBm

        WLAN Signal Quality : 45/70

        WLAN Signal Noise : -256 dBm

        WLAN ESSID : FBI Access point

        System Time : Sunday December 14, 2025 18:41:05

**Comment by lampe208** [comment]
So what changed? Your serial ports were not present before and now they
are. Did you do anything to make that happen or did they just show up after
not being there? *I simply renistalled the software as if I was starting
from scratch*. This information is required to determine if you still have
a problem that can be solved without replacing hardware.

You mentioned "After redoing the software here is the output". Can you give
more details on what you did to redo the software?  *I installed the genmon
software from https://github.com/jgyates/genmon
<http://github.com/jgyates/genmon>*You also posted contradictory data with
the output of the ClientInterface.py command.* Not sure what you mean by
contradictory data?*

You appear to have an underlying issue of your serial port went away and
then came back. That behavior will cause all of the behavior you are seeing
(no serial ports, genmon not loading successfully, genmon reporting
communication failures if the port goes away after genmon is loaded).

It is possible you have a failing SD card and this is causing the serial
port to not be recognized by the OS, which would cause genmon to fail.

The data you are posting needs context, for example if you show the serial
ports with the "ls" command, is genmon working at that time? If genmon
stops working are the serial ports active?  *Please tell me what I need to
do to get you this information.  I sent some information what exactly as
far as commands do i need to do to see where we are at now?*

**Comment by lampe208** [comment]
Is your web interface working?  *NO*

In not, if you use ClientInterface.py can you still get status from the
"generator: monitor" command?  *Yes, I can get the status from this command*
If you are not seeing the web interface then show the last 10 lines in both
/var/log/genmon.log and /var/log/genserv.log:

See Below the last lines



2025-12-14 08:01:38,723 : Possible cause is invalid serial port specified.

2025-12-14 08:09:02,914 : Selected Controller: generac_evo_nexus

2025-12-14 08:09:03,254 : GenMon Loaded for site: SiteName using python
3.7: VEnv: False

2025-12-14 08:21:21,047 : Generator Monitor Shutdown

2025-12-14 08:21:23,795 : Selected Controller: generac_evo_nexus

2025-12-14 08:21:24,134 : GenMon Loaded for site: SiteName using python
3.7: VEnv: False

2025-12-14 08:41:49,320 : Selected Controller: generac_evo_nexus

2025-12-14 08:41:49,653 : GenMon Loaded for site: SiteName using python
3.7: VEnv: False

2025-12-14 13:24:30,975 : Generator Monitor Shutdown

2025-12-14 13:25:04,586 : Selected Controller: generac_evo_nexus

2025-12-14 13:25:04,922 : GenMon Loaded for site: SiteName using python
3.7: VEnv: False

2025-12-14 18:54:24,837 : Selected Controller: generac_evo_nexus

2025-12-14 18:54:25,170 : GenMon Loaded for site: SiteName using python
3.7: VEnv: False

2025-12-14 19:10:54,620 : Selected Controller: generac_evo_nexus

2025-12-14 19:10:54,647 : Error opening modbus device: Error opening modbus
device. : generac_evolution.py:331

2025-12-14 19:10:54,647 : Possible cause is invalid serial port specified.cat
/var/log/genmon.log

 cat /var/log/genserv.log

—



 cat /var/log/genmon.log
 cat /var/log/genserv.log

—

**Comment by lampe208** [comment]
Help me understand why i can use the generator monitor command and see data, but my browser is still not allowing me to log into genmon .

**Comment by lampe208** [comment]
*Does this mean its running?*


***@***.****:*~ $* ps -ef | grep genserv.py

root       922     1  0 10:45 ?        00:00:06 /usr/bin/python3
/home/pi/genmon/*genserv.py* -c /etc/genmon/

pi        2094  1672  0 13:32 pts/1    00:00:00 grep --color=auto
*genserv.py*

***@***.****:*~ $*

**Comment by lampe208** [comment]
![Image](https://github.com/user-attachments/assets/9897b6f0-c010-4704-8c85-8fe12befaf60)

**Comment by lampe208** [comment]
making some progress.  Just no data now 

![Image](https://github.com/user-attachments/assets/9280005f-82ff-41db-87ae-4459861152bf)

**Comment by jgyates** [comment]
I have not received any logs. You have to have outound email setup and working to be able to submit logs. Also, you should get email when genmon starts if you have your email setup correctly.

By default genmon uses port 8000. If you enable secure HTTPS option in the web interface then it will use the default port (i.e. not use 8000 at the end) with a user name and password. The default settings (which I assume you got when you reinstalled if you told the installer to copy the config files) do not use a user name and password.
 
do you have any output when you type the following

   cat /var/log/genserv.log 

Before you said there was nothing, but if the web server is loading you should be getting something. 

What you are describing is normal considering you reinstalled. What is not normal is you say you don't have anything in the genserv.log file. If that is true something is very wrong with your file system and I would not trust the system to run genmon. If you do have data in /var/log/genserv.log then you *might* can run this reliably.

You can see the serial data stats on the monitor page.

**Comment by lampe208** [comment]
So how do i get back to my normal screen I had a week ago when i log in and
can see my voltage , tank monitor, email etc... I dont have any of that
just wifi signal and CPU temp.,,, its not reading my generator

**Comment by lampe208** [comment]
/dev/serial0

lrwxrwxrwx 1 root root 7 Dec 15 10:41 /dev/serial0 -> ttyAMA0
lrwxrwxrwx 1 root root 5 Dec 15 10:41 /dev/serial1 -> ttyS0

pi@raspberrypigenerator:~ $   ls -la /dev/ttyA*
crw--w---- 1 root tty 204, 64 Dec 15 18:29 /dev/ttyAMA0

**Comment by lampe208** [comment]
how do i get the voltage gauges to work?  i had that even though i had not
receiving data  i posted a pic of what i had before
