### ISSUE TITLE
Not getting data from the generator

### ISSUE THREAD

**Issue by jcherney** [jgyates/genmon#124]
Hello - I just finished setting everything up and I'm not receiving data from my liquid cooled generac QT048. Nexus controller 

I'm using raspberry pi 3 running stretch lite.  Installed the latest version of genmon.
serial port test passed without errors.
Tested continuity between battery negative and Pin 6 on the PI3 

monitor screenshot attached.
![genmon-monitor](https://user-images.githubusercontent.com/37984103/40816131-202555c0-6519-11e8-9efa-66b540975c4a.JPG)

I verified all the serial port settings on the wiki page as well.  made sure to remove console redirect.
Not sure what else I can check.

mymodbus.log entries:
pi@raspberrypi:/var/log $ tail mymodbus.log
2018-05-31 21:20:45,085 : Error: timeout receiving slave packet for register 052 Buffer:1
2018-05-31 21:20:48,087 : Error: timeout receiving slave packet for register 01 Buffer:1
2018-05-31 21:20:51,092 : Error: timeout receiving slave packet for register 5f1 Buffer:1
2018-05-31 21:20:54,104 : Error: timeout receiving slave packet for register 09 Buffer:1
2018-05-31 21:20:57,108 : Error: timeout receiving slave packet for register 054 Buffer:1
2018-05-31 21:21:00,118 : Error: timeout receiving slave packet for register 02b Buffer:1
2018-05-31 21:21:03,127 : Error: timeout receiving slave packet for register 0e Buffer:1
2018-05-31 21:21:06,136 : Error: timeout receiving slave packet for register 0f Buffer:1
2018-05-31 21:21:09,147 : Error: timeout receiving slave packet for register 021 Buffer:1
2018-05-31 21:21:12,155 : Error: timeout receiving slave packet for register 02f Buffer:1

any suggestions on what else this could be?

Thank you

Jack

**Comment by jgyates** [comment]
Hi Jack,

Were you able to perform a loopback test by connecting tx and rx at on your cable (i.e. looping back through your cable when you cable is disconnected from the generator). Use the program serialtest.py

https://github.com/jgyates/genmon/wiki/1----Software-Overview#otherappsserialtestpy-optional

Let me know if you have and what the result of the test is.

**Comment by JustApu** [comment]
`serial port test passed without errors.`

@jcherney  - note that serialtest.py can check that the Pi can talk to/through the TTL/232 adapter (where you made your loopback connection). But you could still have TX/RX reversed between your adapter and the generator. Been there, done that.

**Comment by jcherney** [comment]
@jgyates- haven’t done that test, thanks. Will try tomorrow and advise. 

@justapu- have switched those wires back and forth so many times they are wearing thin! I’ll keep doing so to get this resolved, thanks.

**Comment by jgyates** [comment]
@jcherney , once we get this up and running, if you don't mind I would like to get a copy of your registers since I don't have a QT048, you can send them to me on the Monitor page in the web interface. Let me know if you have any questions.

**Comment by jcherney** [comment]
I Would be happy to provide that info

**Comment by jcherney** [comment]
ok just did a test on my cable.  Just to double check i remove the molex connection from the generator and jumpered pins 7 and 8 on the molex end.  then ran serial port test script.  Is this the correct way of testing loopback?
looks like its sending but not 
pi@raspberrypi:~/genmon/OtherApps $ sudo python serialtest.py

Loopback testing for serial port /dev/serial0...

Serial port opened
write data: sent test string
waiting to received data....
FAILED: Sent data does not match receive. Received 0 bytes
pi@raspberrypi:~/genmon/OtherApps $

so it looks like cable is not working.   Going to cut the molex and just twist both cables together to see if that helps.

**Comment by jcherney** [comment]
just tested without molex and got the same error:
pi@raspberrypi:~/genmon/OtherApps $ sudo python serialtest.py

Loopback testing for serial port /dev/serial0...

Serial port opened
write data: sent test string
waiting to received data....
FAILED: Sent data does not match receive. Received 0 bytes
pi@raspberrypi:~/genmon/OtherApps $

So so far loopback on gpio pins is working but these do not.
does this point to a bad ttl converter and/or bad rs232 breakout?

**Comment by jgyates** [comment]
It could possibly be a bad converter, bad break out or incorrect wiring of the convert / breakout. Pictures of your wiring would help.

Do the LEDs on your converter light up? If memory serves, there is one for power, tx and rx.

**Comment by jcherney** [comment]
How do I post pics on this board?

**Comment by jgyates** [comment]
In the text at the bottom of the window you are typing in there are directions on how to post pictures.
<img width="738" alt="screen shot 2018-06-02 at 4 53 34 pm" src="https://user-images.githubusercontent.com/4513286/40880804-898dcf02-6685-11e8-8688-147f4a7545ca.png">

**Comment by jcherney** [comment]
I guess that doesn’t show up on an IPhone.  I’ll do not from my desk top. Thanks.

**Comment by jcherney** [comment]
![719705ae-20be-4e60-ae85-2570966be58e](https://user-images.githubusercontent.com/37984103/40880839-6abeabc2-6686-11e8-88a0-9c29dae4c4e7.jpeg)
![baec7e0e-95f9-457a-9014-26e61fe4e43c](https://user-images.githubusercontent.com/37984103/40880840-6ad2d476-6686-11e8-956e-00c77dbae871.jpeg)
![3353b4bf-14e4-440b-9778-e37884b24a6d](https://user-images.githubusercontent.com/37984103/40880841-6ae11a90-6686-11e8-86d9-459cc3a225d8.jpeg)

The other end of the green and yellow wires are stripped and twisted together.

**Comment by jgyates** [comment]
It is hard to tell from the angel of the pictures but you may have both power and ground on the converter tied to power on the pi.

![raspberry-pi-gpio-layout-model-b-plus-rotated-2700x900](https://user-images.githubusercontent.com/4513286/40880905-b9389c30-6687-11e8-8a77-34d652b90832.png)

Try connecting VCC to 3.3V (pin 1 on the pi). It should work on either 5V or 3.3V, but 3.3V is probably a little safer to have it on 3.3V.  Connect ground to pin and Ground to pin 6 on the pi header. pin 8 on the pi goes to pin TDX on the converter, pin 10 on the pi goes to RDX on the converter. 

If that checks out and the loopback still does not work you may want to make sure you connections on the screw terminal are good, a multi-meter to check continuity between the two screws on TX and RX on the green terminal screws should validate that.

**Comment by jcherney** [comment]
Getting closer! Ran Serialtest.py and got “Sent data does not match receive. Received 15 bytes”

**Comment by jgyates** [comment]
Depending on how recent your code is you can run this test:

     sudo python ./OtherApps/serialconfig.py -c

If it don't have this program then update your software with this command:

     bash ./genmonmaint.sh update

The output of serialcheck.py should look like this:

     Checking : Serial console command line removed: OK
     Checking : Is enable UART in boot config: OK
     Checking : Is BT overlay disabled: OK
     Checking : Serial console service disabled: OK

     Serial port settings are OK. A reboot is needed if changes were made.

**Comment by jcherney** [comment]
Looks like I have to update the program. I'll do so and advise.. Thank you.

**Comment by jcherney** [comment]
Just updated and ran serialcheck.py  Everything shows as OK

**Comment by jcherney** [comment]
Is there a reason the serialtest.py showed a problem before updating, and then not after? Do I still have an issue? (I havent rebuilt my molex yet).

**Comment by jgyates** [comment]
I would need to know more info about the problem it is showing. The following command:

     sudo python ./OtherApps/serialconfig.py -c

will just check your settings. I am just trying to determine if you have something else trying to use the serial port. You can take a screen shot and post it here or copy and past the output here if you are accessing your system remotely. We have not changed anyting so I would assume your system still has the same issue. Does the loopback test still fail? If you are accessing your system via ethernet or wireless  or with a keyboard and monitor?

**Comment by jcherney** [comment]
System is accessed via wifi, using my desktop keyboard and monitor.

**Comment by jgyates** [comment]
ok. just copy and past the output of the problem you saw with serialconfig.py if you still have that on your ssh console. Also lets see the output of this command:

     ls -la /dev/ser*

**Comment by jcherney** [comment]
pi@raspberrypi:~/genmon $ sudo python ./OtherApps/serialtest.py

Loopback testing for serial port /dev/serial0...

Serial port opened
write data: sent test string
waiting to received data....
error communicating...: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

Now I'm not getting any response. Did I run this correctly?

**Comment by jgyates** [comment]
I need to see the output of this command:

     ls -la /dev/ser*

It should look like this:

<img width="467" alt="screen shot 2018-06-02 at 6 17 48 pm" src="https://user-images.githubusercontent.com/4513286/40881317-52756c4e-6691-11e8-8dbc-e5bbabb3ba4b.png">

If serial0 is not linked to ttyAMA0 then your port is not on serial0. It could be on serial1, depending on how you setup your port.

If you pi serial port is not on /dev/serial0 then you may see this error or if your serial port is not configured properly you could see this error.

**Comment by jcherney** [comment]
See above 4 posts.

**Comment by jgyates** [comment]
OK, got it. looks like serial0 is indeed pointing to ttyAMA0. That is how it is suppose to be. 

1) Do you have a multimeter?
2) How are you powering your pi, form the battery? If your ground connection is not making a good connection then you could have power issues on the pi, which will make all sorts of things have odd results. If you have a multimeter you can test continuity between the ground on the pi and the ground terminal on your batter.
3) When you ran serialtest.py and got "device reports readiness" was this with the converter or loopedback at the pi connector or thought the cable? Please include these details as it helps with keeping the details of what is working and what is not straight.
4) Let's fall back to the loopback test at the pi connector. What is the result of that with serialtest.py

**Comment by jcherney** [comment]
1. I do have a multimeter.
2. Pi is powered from the generator battery. We (Kalex is helping me immensely!) did the ground test yesterday and continuity tested fine. 
3. The cable (yellow and green wire) are twisted where the molex was (I cut and stripped them). The other end are attached to the converter. 
4. How do I run that?

**Comment by jgyates** [comment]
Disconnect the converter board
Connect pin 8 to pin 10 on the raspberry pi connector
Run this test:

     sudo python ./OtherApps/serialtest.py

Also, let's see the output of this command:

     vcgencmd get_throttled

**Comment by jcherney** [comment]
Do you want the output after I disconnect, or before?

**Comment by jgyates** [comment]
we are going to run three tests with serialtest.py.

1) looping back tx to rx at the raspberry pi header with no converter attached (loop pin 8 to 10).
2) looping back tx to rx at the green terminal connector with the converter attached (looping back Tx to Rx on the terminal connector)
3) looping back tx and rx at the molex cable with the converter and cable attached.

Run these in order, if any of these fail, then stop. Run each test 5 times in a row to make sure we have consistent results.

**Comment by jcherney** [comment]
Ok, jumped 8 & 10 and got this:

pi@raspberrypi:~/genmon/OtherApps $ sudo python serialtest.py

Loopback testing for serial port /dev/serial0...

Serial port opened
write data: sent test string
waiting to received data....
error communicating...: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

**Comment by jcherney** [comment]
Ran first one 4 times with same output as above.

**Comment by jgyates** [comment]
OK. Send another picture of your connections. I can't tell from your original pic what pin you connected to your pi. Maybe angle you camera a bit instead of a shot directly above..

**Comment by jgyates** [comment]
also what is this output:

     vcgencmd get_throttled

**Comment by jcherney** [comment]
pi@raspberrypi:~/genmon/OtherApps $ vcgencmd get_throttled
throttled=0x0

**Comment by jcherney** [comment]
![728b9076-8ba9-419b-83b7-9ef2d1e45b53](https://user-images.githubusercontent.com/37984103/40881475-4e2b8cf0-6695-11e8-978c-8787c0d51a0c.jpeg)
![Uploading E63F1BDF-8F41-4D98-9E54-08985BE9F557.jpeg…]()
Do these work?

**Comment by jcherney** [comment]
Those pics were taken yesterday before you had me move pin 2 to pin 1.

**Comment by jcherney** [comment]
![efd19339-2dc1-44b6-a76a-b9621aca562b](https://user-images.githubusercontent.com/37984103/40881491-a1b1a4a4-6695-11e8-821b-60f5b2264971.jpeg)

**Comment by jcherney** [comment]
I'll take a pic of the loopback also in a minute.

**Comment by jgyates** [comment]
Since you initially setup your serial port my modifying /boot/config.txt and /boot/cmdline.txt, have you rebooted your system?

**Comment by krisasmith** [comment]
Check /boot/cmdline.txt for “console=serial0,115200", I had the same serial test errors and this was why.

**Comment by jcherney** [comment]
Did it reboot after updating?

**Comment by jgyates** [comment]
good point Kris,

type this:

     cat /boot/cmdline.txt

**Comment by jcherney** [comment]
pi@raspberrypi:~/genmon/OtherApps $ cat /boot/cmdline.txt
dwc_otg.lpm_enable=0 console=tty1 root=PARTUUID=672f8420-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait

**Comment by jcherney** [comment]
![13b39eed-cb17-477c-ab49-be56760a3ba8](https://user-images.githubusercontent.com/37984103/40881509-528f9c18-6696-11e8-81c8-763428a80688.jpeg)
![4266632f-0b4a-425d-9b42-265e4aead32b](https://user-images.githubusercontent.com/37984103/40881510-529d022c-6696-11e8-9c19-22604db7997b.jpeg)

**Comment by jgyates** [comment]
No, did you manually reboot you pi after modifying /boot/config.txt and /boot/cmdline.txt

**Comment by jgyates** [comment]
OK. Let's try this.

1) reboot your pi. It is not acting like the serial port settings are in effect. Once it comes backup log back in to you pi
2) Run the loopback test, looping back pin 8 to 10 on the pi connector, but remove all other connections

What are the results of this test?

**Comment by jcherney** [comment]
pi@raspberrypi:~/genmon/OtherApps $ sudo python serialtest.py

Loopback testing for serial port /dev/serial0...

Serial port opened
write data: sent test string
waiting to received data....
FAILED: Sent data does not match receive. Received 94 bytes

**Comment by jcherney** [comment]
Ran it again and got this, again:


pi@raspberrypi:~/genmon/OtherApps $ sudo python serialtest.py

Loopback testing for serial port /dev/serial0...

Serial port opened
write data: sent test string
waiting to received data....
error communicating...: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

**Comment by jcherney** [comment]
Pin 8&10 are jumped

**Comment by jcherney** [comment]
Let me test the ground again, just to make sure. Output is not consistent.

**Comment by jgyates** [comment]
ok. I think I know at least one of the problems. I am guessing that you already have genmon loading from your crontab, we need to stop genmon to run serialtest.py.

Type this command from the genmon directory:

    bash ./startgenmon.sh stop

Then type this:

   python ./OtherApps/serialtest.py .   

If you reboot, genmon will load again if you already did that step so we need to make sure it is stopped when running serialtest.py

**Comment by jcherney** [comment]
Well, that made a difference:

pi@raspberrypi:~/genmon $ python ./OtherApps/serialtest.py

Loopback testing for serial port /dev/serial0...

Serial port opened
write data: sent test string
waiting to received data....
PASSED! Loopback successful

**Comment by jcherney** [comment]
BTW- ground tested and good.

**Comment by jgyates** [comment]
Yes, let's run the loopback test with the converter connected, looping back the Tx and Rx  on the terminal connector.

**Comment by jcherney** [comment]
Failed: sent data does not match receive. Received 0 bytes

**Comment by jcherney** [comment]
I’m using one of the wires for this loop back test. I pulled #8 from the pi. Is that an issue?

**Comment by jgyates** [comment]
I don't know what that means. If it means that pin 8 has nothing connected to it then yes. That will cause things to fail the loopback test. Describe or show a picture of how you have everything wired when running this test.

**Comment by jcherney** [comment]
Well, 8 is empty so I will have to find another way to jump. 

Sent from my mobile


On Jun 2, 2018, at 7:42 PM, jgyates <notifications@github.com> wrote:

I don't know what that means. If it means that pin 8 has nothing connected to it then yes. That will cause things to fail the loopback test. Describe or show a picture of how you have everything wired when running this test.

**Comment by jcherney** [comment]
![6fb26859-455c-4a16-a951-77634e5f9ca4](https://user-images.githubusercontent.com/37984103/40881800-98619644-669e-11e8-99b6-da9d41201c8c.jpeg)
![Uploading 18921553-4CDD-4C14-959B-96841F0F84EA.jpeg…]()
Still no data received

**Comment by jgyates** [comment]
I am not following you. You said 8 was empty then you posted a picture of you pi with 8 connected. Please understand that I can not help if I don't know exactly what you are doing. More details in your description are needed for me to help you.

**Comment by ts4s** [comment]
@jcherney Jumper needs to be on the other board with the terminal block... jump pin 2 & 3

**Comment by jcherney** [comment]
I just reconnected 8. Then used a wire to jump tx and Rx on the connector. I realized after you commented about 8 that it had to be connected. Sorry for the confusion.

**Comment by jcherney** [comment]
@ts4s- ok, thanks.

**Comment by jgyates** [comment]
OK. You need to have all of the connections from your pi to the converter board. The loopback test we are trying to do requires that you have all of the connections from the pi to the converter board connected. What needs to be loopedback is on the green break out board with the screw terminals.

**Comment by jcherney** [comment]
Yep. Just did that. Failed Send data does not match received. received 15 bytes

**Comment by jgyates** [comment]
picture please.

**Comment by jcherney** [comment]
![d374ee18-c74c-4f98-adb5-bef3a12611db](https://user-images.githubusercontent.com/37984103/40881908-c0e06c74-66a0-11e8-9c31-5a5ab6a84841.jpeg)

**Comment by jgyates** [comment]
Check continuity with the meter between the two screws on pin 2 and 3 of the green break out board.

**Comment by jcherney** [comment]
Perfect

**Comment by jcherney** [comment]
I havent looked. I will try it from my Iphone and let you know. Would they be the lights on either side of the power led that I'm looking for?

**Comment by jcherney** [comment]
No lights light up when I run the command

**Comment by jcherney** [comment]
Hit wrong button. How do I reopen

**Comment by jgyates** [comment]
If you have checked your wires between the pi and the converter board, the it looks like your converter board is bad.

**Comment by jcherney** [comment]
I had that feeling. I’m going to order another one. Im so sorry to take up all this time for a bad board. Many thanks!

**Comment by jgyates** [comment]
OK. Feel free to reopen this issue if you have any problems once you get your new board.

**Comment by jcherney** [comment]
Back again. Brand new serial port and breakout board. NOT attached to generator. Stopped genmon and jumped screws 2&3. No data received. Did a loopback of pins 8&10 on the PI and worked correctly:
pi@raspberrypi:~/genmon/OtherApps $ sudo python serialtest.py

Loopback testing for serial port /dev/serial0...

Serial port opened
write data: sent test string
waiting to received data....
PASSED! Loopback successful

re:attached Pi to Serial and detached serial from breakout board  , jumped pins 2&3, and nothing:
pi@raspberrypi:~/genmon/OtherApps $ sudo python serialtest.py

Loopback testing for serial port /dev/serial0...

Serial port opened
write data: sent test string
waiting to received data....
FAILED: Sent data does not match receive. Received 0 bytes
![img_3661](https://user-images.githubusercontent.com/37984103/41010709-23c91d96-6907-11e8-8531-ea9b872a9c41.jpg)
![img_3662](https://user-images.githubusercontent.com/37984103/41010719-3c0dcce4-6907-11e8-886d-72bf1bb51823.jpg)
![img_3663](https://user-images.githubusercontent.com/37984103/41010720-401125f2-6907-11e8-90f5-148b8e56fd50.jpg)

I'm at a loss. Any ideas what I'm doing wrong?

**Comment by jgyates** [comment]
swap your transmit and receive connects from the pi to the red converter board.

**Comment by jgyates** [comment]
I am not familiar with this converter board but based on the picture it has an arrow on the TXD pin pointing out. To me this indicates that this should go to the receive pin, but that is a guess. 

Does this converter board expect 3.3V or 5V?

**Comment by jcherney** [comment]
Swapped TX and RX- same result.   I'm not sure about the power requiement. Should I move VCC to pin 4 on PI?

**Comment by jcherney** [comment]
Swapped it to pin 4. No change. Switched TX and RX back and forth. No change.

**Comment by jgyates** [comment]
Is the chip on the converter a MAX3232 ?

As I said I know nothing about this board so it may not work with the raspberry pi.

**Comment by jcherney** [comment]
![img_3664](https://user-images.githubusercontent.com/37984103/41011592-9cbed160-690b-11e8-9882-ae1a63141a6a.jpg)
Does this help?

**Comment by jgyates** [comment]
We can try the one you have, but this one is known to work:

https://www.amazon.com/dp/B072KJSS5C/ref=sspa_dk_detail_3?psc=1&pd_rd_i=B072KJSS5C&pd_rd_wg=Nd6FS&pd_rd_r=VZ5RZZSGJ0JP5JMS1AYK&pd_rd_w=UqGO1

**Comment by jcherney** [comment]
![img_3669](https://user-images.githubusercontent.com/37984103/41011793-7fc1b9a0-690c-11e8-9be1-731a8b0b5d60.jpg)
Let me know if this is correct. If not, I'll buy another one from your link.

**Comment by jgyates** [comment]
According to (this)[https://www.exar.com/ds/sp3222e_sp3232e.pdf] it can be powered for 3 - 5V so use 3.3V

These are the connection from the pi to the red board, in order, as labeled on the red board

VCC to Pi 3.3V pin 1
Gnd to Pi Ground pin
TXD to pi pin 10 Receive
RXD to pi p9n 8 Transmit

Once these are connected, loop TX to RX on the DB-9 connector side and try serialtest.py. Pay attention to the LEDs labled LED_RXD and LED_TXD.

**Comment by jcherney** [comment]
I have no idea what we just changed, but it worked!!

pi@raspberrypi:~/genmon/OtherApps $ sudo python serialtest.py

Loopback testing for serial port /dev/serial0...

Serial port opened
write data: sent test string
waiting to received data....
PASSED! Loopback successful

**Comment by jcherney** [comment]
I'm going out in the dark to put this thing back on the generator! Thank you for whatever you did to get this to work!

**Comment by jcherney** [comment]
If I get data from the generator, you mentioned you wanted registers. How do I get those for you?

**Comment by jgyates** [comment]
Pull up the web interface, go to the Monitor page, click on the button at the bottom of the page named "Submit Registers"

**Comment by jcherney** [comment]
Will do- again- thank you for your help! Hopefully the gen spits out some data....

**Comment by jcherney** [comment]
Working!!! Registers sent! Thank you so much for your patience!!

**Comment by jgyates** [comment]
I have not received them. Do you have your mail configured? Are you receiving email notices when the software starts? If not you can go to the Settings page and setup your email. You will know it is working when you receive emails when the settings are applied or when the software is started. Once your email sending is setup then you can re-click the "Submit Registers" button.

**Comment by jcherney** [comment]
I thought I had it set up and it wasn't sending because it wasn't working. I'm not getting any emails at all. I'll check that out. Is there a way to manually send you the registers?

**Comment by jcherney** [comment]
You should be getting them now. I'll resend. I am getting emails after the change I made

**Comment by jcherney** [comment]
Any time! Many thanks again!

**Comment by jcherney** [comment]
On the website it shows it needs an upgrade. Is that to the website software, or the monitor software?

**Comment by jgyates** [comment]
This will update the software for the monitor and the web interface.

**Comment by jcherney** [comment]
Thanks.
