### ISSUE TITLE
Wiki addition: Software overview Twilio missing info

### ISSUE THREAD

**Issue by smeisner** [jgyates/genmon#134]
**Documentation update**

The wiki page [https://github.com/jgyates/genmon/wiki/1----Software-Overview](https://github.com/jgyates/genmon/wiki/1----Software-Overview) that describes setting up Twilio is missing (I think) a little bit of data. In the `gensms.py (optional)` section, before the two pip commands, I found I need to do an additional command first:

`apt-get install build-essential libssl-dev libffi-dev python-dev`

Then the pip commands work fine. I have found this after doing a fresh Rasbian 9  Lite install.

**Comment by jgyates** [comment]
Done.
