### ISSUE TITLE
CPU temps high after update 

### ISSUE THREAD

**Issue by jcherney** [jgyates/genmon#139]
Hi,

Just updated to 1.9 from 1.1. Previously CPU temps were in the 57-60 deg range. Now they are in the 118-121 deg range. Seems really high.

Any thoughts on why I’m seeing this?

**Comment by jcherney** [comment]
![5ac61b2f-eb04-4a33-95fd-a623eea08721](https://user-images.githubusercontent.com/37984103/41631114-d1d6e4dc-7400-11e8-80ed-1de86229015a.png)

**Comment by jgyates** [comment]
I am guessing what you were  reading before was Celsius and what you are reading now is Fahrenheit. The UI has an option to display Fahrenheit. If you go to the settings page there is an option to "Use Metric Units" If enabled it will display in  Celsius. 60 C is normal for a pi, so is 116 F.

When the platform stats first rolled out it was metric only, then we added the weather stuff and gave an option to display metric or imperial units.

**Comment by jcherney** [comment]
Well that makes sense- thanks! I’ll check that out.
