### ISSUE TITLE
Note: Battery to USB power supply fuse

### ISSUE THREAD

**Issue by jgyates** [jgyates/genmon#140]
Just a note to let people know of this experience: I had lightening strike near my generator and fried my controller ( a new one is on the way). It also killed my pi. I have since replaced the pi and changed the fuse in the Battery to USB power supply to a 2A fuse. It comes with a 7.5A fuse, which is a bit high. They say lightening does not strike twice, but I am changing my fuse to be on the safe side.

**Comment by krisasmith** [comment]
You should consider getting one of these. If you are comfortable putting a circuit breaker into your panel it can be installed easily.

https://www.amazon.com/gp/product/B01AQAKRSS/
