### ISSUE TITLE
Checking Compatibility with controller???

### ISSUE THREAD

**Issue by cblknittights** [jgyates/genmon#146]
Looking to determine compatibility with my Generac genset, as the Generac device at $300+ is ludicrous! ;) 

### Your Environment

- Genereator Model: Guardan Series see photo below.
- Generator Registers: N/A
- Genmon Version: N/A

This is the model:

![Model](http://www.imagebam.com/image/308ea9912813334)
http://www.imagebam.com/image/308ea9912813334
Controller 

![Controller](http://www.imagebam.com/image/9e1f5e912813364)
http://www.imagebam.com/image/9e1f5e912813364

Any ideas on compatibility and where or if there is a serial port on this controller. Not seeing any stickers to remove to get to it... 

Thanks!

**Comment by jgyates** [comment]
@cblknittights 

Based on the data I have I would say no, this will not work. See note 6 on this page for details:

https://github.com/jgyates/genmon/wiki/Appendix-4-Known-Issues
