### ISSUE TITLE
Sent registers

### ISSUE THREAD

**Issue by jcherney** [jgyates/genmon#153]
Hi- not an issue. I sent registers a couple hours ago for a QT04842ANAX showing an unknown error. In reality, the error was lack of fuel.

They replaced our gas lines and disconnected for a while today, this setting off the error. 

Just another data point for you.

**Comment by jgyates** [comment]
Got it. Thanks. I will include this in the next update in a few days.

**Comment by jgyates** [comment]
@jcherney 

Question: Do you use propane or Natural Gas for fuel?

**Comment by jcherney** [comment]
Natural gas 

Sent from my mobile


On Aug 2, 2018, at 5:37 PM, jgyates <notifications@github.com> wrote:

@jcherney

Question: Do you use propane or Natural Gas for fuel?
