### ISSUE TITLE
Feature Request: BCC email

### ISSUE THREAD

**Issue by USAFPride** [jgyates/genmon#154]
It would be a nice feature to have the option to send messages to multiple email addresses via BCC.  I'm thinking the best place to make the option is a checkbox on the Notifications page. I'm not sure whether it should be a universal (all emails, easiest) or a separate choice for each address.  Currently I'm just changing to To line in `mymail.py` (line 258) to `msg['Bcc']`

**Comment by jgyates** [comment]
Hi @USAFPride 

Let me think on this. You can already send to multiple addresses, it just does not use BCC. Is there a reason why you want to use BCC.

**Comment by USAFPride** [comment]
@jgyates, I use email to send SMS notifications (most providers have an email option) and multiple addresses show up via SMS.  In addition, the most pressing version, I monitor my parents genset and it eliminates the "reply all" email of "did you see this?"
