### ISSUE TITLE
Not really an issue...

### ISSUE THREAD

**Issue by dakegg** [jgyates/genmon#17]
Cannot find specifics on where this connects on the Evolution controller.  Any screen shots of the molex connection to the controller...  thanks

**Comment by jgyates** [comment]
[Here](https://github.com/jgyates/genmon/blob/master/Diagrams/Cable%20(End%20that%20connecets%20to%20Evolution%20Controller)%20(2).jpg) is a picture of the cable that connects to the controller. I believe this one is an air cooled model. Some liquid cooled models the placement of the controller is may not be visible (like on my unit). I will try to puy some better descriptions of the cable in the wiki with pictures.

[This](https://github.com/jgyates/genmon/issues/15) thread has a picture of the controller receptacle 

Some other threads have question and some pictures of cables people have made.

There are two versions of the Evolution controller (liquid cooled and air cooled) so the placement may be different. I believe it is the only connector on the back of the unit with 8 pins, it also could have a sticker or cover over it.

**Comment by madisdev** [comment]
On my Evolution controller it was under the panel that has the small LCD display. It also had a sticker over it that said something like port 1.

**Comment by dakegg** [comment]
Thanks, I'll take a look.   Mine (11k aircooled) was manufactured in Nov 2016, so it's fairly new.  I saw a usb connection on the top, by the LCD and fuse, but wasn't able to see behind \ underneath without pulling the side panel...

**Comment by madisdev** [comment]
I have a 22k and I can just lift up the front panel to gain access. Not sure if yours is similar. But it should be on the underside of the panel that has the USB and the LCD screen.

**Comment by dakegg** [comment]
Now I wish I was at home, it didnt look like the panel lifted up, but I didn't think to try.  I figured I'd have to open the side panel where the battery is located and look up underneath from inside there...   I'll report back tonight when I've had a chance to check.  Thanks!

**Comment by jgyates** [comment]
I added this page to the wiki
https://github.com/jgyates/genmon/wiki/Making-a-Cable

The part numbers for the connector are here:
https://github.com/jgyates/genmon/wiki/Hardware

**Comment by dakegg** [comment]
Ok, so on the 11Kw Generac Guardian air-cooled, if you lift the lid and remove the front panel, you can look up underneath the control panel on the right and see the bottom of the controller.  There are two ports, each covered with a sticker.  One say Accessory Port 1, the other Accessory Port 2.  

I am going to build the solution and then try both, I'll report back in a week or so...   It's a brand new activation, and it's throwing a lot of white smoke when it runs, so I have to dig into that issue first.

**Comment by jgyates** [comment]
Sounds good. Let me know if you have any questions. The smoke could be several things, one common thing  could be adding too much oil If you check your oil level and it is over the fill line try removing some oil.

**Comment by rhombixt** [comment]
Your molex pinout is wrong in your diagram. The pin 1 is on the lower right . The pin 7 and 8 are correct

**Comment by jgyates** [comment]
Thanks, I will try to get that fixed, one of the users created that. I don't have the original.

**Comment by rhombixt** [comment]
I sent you an email with the repair manual molex details
________________________________

**Comment by jgyates** [comment]
I updated the wiki with the pinout diagram you sent. Hopefully we will get the other diagram fixed shortly.

**Comment by rhombixt** [comment]
Great thanks.
________________________________

**Comment by jgyates** [comment]
The diagram with the error has been updated. Thanks for finding that rhombixt. Good catch!

**Comment by rhombixt** [comment]
I got my generator installed... just waiting on parts still from china. They have been held up with canada customs now for almost 2 months.
________________________________
