### ISSUE TITLE
Issue with battery draining - looking for troubleshooting help?

### ISSUE THREAD

**Issue by kalex1114** [jgyates/genmon#170]
Hello
I had genmon running great for few months and on august 18th my house either got struck by lightning or there was a power surge from the grid.  Had damaged electrical equipment at the house.  I was away for the weekend so not sure exactly what happened.  When i came back my genmon wasn't getting any data and my battery was showing low.  I took it to autozone and they said it was below 5% charged. I bought a new battery and put that in.  reconnected the pi but it was still not getting data from the controller.  fast forward to today and battery was dead.  generator was off.  I took it back to autozone and they said it was at 1% charged.  They charged it back to 100%.  This time i disconnected raspberry and adapters completely from generator and tested charging from the controller.  It was showing 2.30A (DC) on the multimeter.  So everything seems to be ok on the generator side.

How do i go about testing what got damaged on the raspberry/adapters side?

I have G0070370 generac 17KW model.
Thank you

Alex

**Comment by jgyates** [comment]
Some suggestions:

1) You can disconnect the pi from the generator and see if you can login via ssh
2) You can bring the pi inside and connect it to a keyboard and monitor
3) You can disconnect the pi from the generator and do a loopback test with the cable attachdd to see if the RS-232 converter is working.

I had a lightning strike earlier this year. In addition to some other electronic equipment outside the house it damaged the pi and RS-23 converter. It also took out my controller. The tech who replaced the controller said that was rare but does happen from time to time.

**Comment by jgyates** [comment]
if you can ping the pi then your pi and network should be good. If you are not receiving data from the controller it could be the cable or RS-232 converter.

**Comment by kalex1114** [comment]
Sorry forgot to mention - pi itself was operational.  i was able to ssh to it and was getting emails from genmon that it was trying to start.  Controller on the generator seems fine.  no errors except for the battery drain.  I took the pi and cables out of the enclosure will connect it locally and see if i can figure out.  I'm guessing its the rs-232 converter that got damaged.  So having a lightning strike is not far fetch if it happened to you as well.

**Comment by liltux** [comment]
Dido what @jgyates has to say.  I would bet since your battery keeps discharging and the controller does not keep the battery charged it is damaged internally.  N1 and N2 wires are direct connection to Utility mains, so any surges or large transients such as lightning strikes, exploding transformers, etc. could damage the controller on the generator.

**Comment by jgyates** [comment]
could be the RS-232 and the batter charger. If you are not charging regularly the pi will drain the battery will drain quickly. Normally the battery is charged every 18 hours by the controller.

**Comment by kalex1114** [comment]
I tested the battery charging and it seems to work.  followed the instructions from generac.  Its also possible that controller is damaged as well.  i disconnected it for now and will see if battery is discharging

**Comment by kalex1114** [comment]
Hmm.  So just booted up my pi and it seems that the first loopback test fails crossing 8 and 10 on the gpio headers.

Loopback testing for serial port /dev/serial0...

Serial port opened
write data: sent test string
waiting to received data....
FAILED: Sent data does not match receive. Received 0 bytes

**Comment by jgyates** [comment]
Make sure genmon.py is not running when running the loopback test.

Is the only thing connected to the GPIO header your loopback (i.e. you have removed the RS-232 converter)? That would be quite odd since that component is in the chipset. I would doubler check thaty your loopback is making a good connection before you assumed the pi is bad. 

You may want to reboot your pi if you have not already, then stop genmon, then run the serial test.

**Comment by kalex1114** [comment]
yep i did bash ./startgenmon.py stop first.  made sure it wasn't running.
disconnected all cables from GPIO and connected only one cable between pins 8 and 10.  plugged in all the way as well.  also disabled crontab job for genmon start and rebooted.  same result

**Comment by jgyates** [comment]
The only other thing I would suggest is to run this from the OtherApps directory:

     sudo python serialconfig.py -c

It should give you and output like this:

     Checking : BT service disabled: OK
     Checking : Serial console command line removed: OK
     Checking : Is enable UART in boot config: OK
     Checking : Is BT overlay disabled: OK
     Checking : Serial console service disabled: OK

If it does not then run 

     sudo python serialconfig.py -e

Then reboot, stop genmon and run the loopback test again.

**Comment by kalex1114** [comment]
ran serailconfig.py -c and all came back without issues.  this was working perfectly fine for 3 months before the lightning strike

**Comment by jgyates** [comment]
Looks like your pi serial port is not working, but the rest of the pi is functional. I had Ethernet go out on a pi once and SD cards. I guess it is possible that something is corrupt on the SD card,... either that or your pi is bad is my guess

**Comment by kalex1114** [comment]
Thats what it looks like. Weird.  Could be bad soldering job as i did solder the GPIO headers :)

**Comment by kalex1114** [comment]
Got a new pi zero wh and loopback is sucessfull.  switched microsd from original pi to new one.  and connected same cable to 8/10 pins

pi@genmon:~/genmon/OtherApps $ python serialtest.py 

Loopback testing for serial port /dev/serial0...

Serial port opened
write data: sent test string
waiting to received data....
PASSED! Loopback successful

**Comment by jgyates** [comment]
Good new.  Now you just need to test with the RS-232 converter.

**Comment by kalex1114** [comment]
I'm having a brain fart.  Is this a correct way of doing loopback on rs232 ttl adapter?

![screenshot 2018-09-02 14 32 33](https://user-images.githubusercontent.com/17240236/44959492-0f16bb00-aebd-11e8-85bf-b5356d905836.png)
![screenshot 2018-09-02 14 32 25](https://user-images.githubusercontent.com/17240236/44959493-0f16bb00-aebd-11e8-91e5-c8b59bad7cd6.png)

**Comment by kalex1114** [comment]
Or is this a proper loopback test?
![screenshot 2018-09-02 14 44 11](https://user-images.githubusercontent.com/17240236/44959566-b6e0b880-aebe-11e8-89a2-f6688173fd48.png)

**Comment by kalex1114** [comment]
Nevermind.  just replaced rs232-ttl and db9 breakout with new ones and entire chain including generator aux cable passed loopback test.  Now I'm having my dealer come in to test the evolution controller as well
