### ISSUE TITLE
Cannot access settings in web interface after update to 1.10

### ISSUE THREAD

**Issue by lmackley** [jgyates/genmon#179]
When clicking in settings "button" nothing happens.  All others appear to be fine.

**Comment by lmackley** [comment]
Issue seems to be fixed.  The /var/log/genserv.log indicated a missing 'tanksize'.  I entered a 0 for the tank size since my generator runs on natural gas and everything appears to be working now.

**Comment by jgyates** [comment]
ok. that is good info. I will test this and see if I can make it a bit smoother...
