### ISSUE TITLE
Non-Issue PowerPact Support

### ISSUE THREAD

**Issue by liltux** [jgyates/genmon#190]
Has anyone set up a genmon on a PowerPact unit??  I just learned that they are supported by MobilLink, so there should be a serial communication port.  @jgyates, would you be interested in adding support for another controller type?  The PowerPact is a bare minimum controller.  I had someone ask if it is supported on the ebay page for a prebuilt component.  I don't have a PowerPact at my disposal to send you register information or log files but maybe someone on here might see this post and be interested in giving it a shot.

**Comment by jgyates** [comment]
Sure, I would be happy to add support for the PowerPact

**Comment by liltux** [comment]
@jgyates, I have recieved pictures of the cable connecting the mobillink to the powerpact unit.  It appears it still uses the same 8-pin molex and pins 7 and 8 for serial communication.
![powerpactplug1](https://user-images.githubusercontent.com/17954856/46667806-62e98380-cb90-11e8-9008-c59b64df6ff0.jpg)
![powerpactplug2](https://user-images.githubusercontent.com/17954856/46667807-62e98380-cb90-11e8-9345-3ab17115689c.jpg)

**Comment by jgyates** [comment]
PowerPact is now supported
