### ISSUE TITLE
Outage Duration Log

### ISSUE THREAD

**Issue by zekyl314** [jgyates/genmon#206]
### Expected Behavior

When an outage is over, the elapsed time is shown from the time the outage started.

### Actual Behavior

Under normal circumstances this has not been an issue.  However, yesterday during a long outage, I realized I wasn't on the newest version and the new version had some new features I took advantage of using.  When I loaded the new software the service restarted.  When the outage was over, the duration was the time in which the software thought power was out since the last restart.  

It might be nice, if possible, for the software to recognize when the outage occurred and determine the length of outage in case the PI restarts or service restarts during this time window.

### Steps to Reproduce (including precondition)

- During power outage, restart genmon service
- When power is back, you can see the difference in duration from when utility power was actually lost.

**Comment by jgyates** [comment]
Hi @zekyl314 

Let me think on this. I will add this to the list of possible features. I like the idea, I just want to assess the impact on maintainability and the potential of introducing new issues.

**Comment by zekyl314** [comment]
Thanks, it isn't a huge deal, just something I noticed and thought I'd point it out if there was a way to change it.

**Comment by nah2323** [comment]
@zekyl - couldn’t the reboot be avoided by connecting the Pi to the 12v power source in the generator like the battery?  Then the Pi would stay live, even if the net drops.

**Comment by zekyl314** [comment]
@nah2323, it was not a reboot, it was me updating the version of the genmon software during an outage.  So it was something I did on purpose.  My power source is the battery for the pi and that works well.

**Comment by jgyates** [comment]
@nah2323 , I believe the issue is that the software keeps track of the duration of the outage and if the software is restarted the duration of the outage will only be from the moment the software was restarted. What @zekyl314  is describing is the current behavior of the software (outage durations are not kept in non volatile storage until the outage is over)
