### ISSUE TITLE
Non Issue - Program suggestion.

### ISSUE THREAD

**Issue by liltux** [jgyates/genmon#216]
@jgyates, I am currently troubleshooting an email issue.  One thing I noticed that would be handy in this case is a way to force an emial notification from the WebUI.  Like say a test notification.  That would verify that just the email is working.  Rather having to go through a complete restart or reload of the application to try and trigger an event.  Just a thought.

**Comment by liltux** [comment]
@jgyates I am going to send you the logfiles.  something does not look right to me.  It was working saturday, but now is not.  Not sure, but would like a second opinion.  Thanks.

**Comment by jgyates** [comment]
Sounds good.

There is a chicken and egg problem with the test email. If the user has not saved their settings then the backend would need to get the settings from the web interface, which is doable, just not the way the code is currently structured. Right now we just save settings to a file and restart to make changes. I will likely make this change at some point, it is just more time consuming than it appears to implement it correctly.

**Comment by liltux** [comment]
It was just a thought, I have seen a few different user interfaces that have a similar feature.  By the way have you had a chance to look at the logfiles I sent?  I looked into it a little and it says it has to do with the emial formating but I did not change anything on the webUI between Saturday and Today.  I even went as far to run the "genmonmaint.sh install" to see if something had changed.  Nope, still getting syntax errors.  I just dont get it.  I refers to line 323 in mymail.py, which is around were the email is sent.

**Comment by jgyates** [comment]
The last logs I got from your were for you 50kw unit yesterday. I have not received any today. I looked at line 323 and there is a bug there. I checked in an update. It looks like you are getting an  error fetching the email from the server and the error handler had a function that was removed a while back.

**Comment by liltux** [comment]
That took care of it, thanks.  Was that problem related to me or do to one of the email recipients had an auto response turned on and the code didn't like it?

**Comment by jgyates** [comment]
When trying to read IMAP email, an error was generated by the IMAP library (probably due to the auto response I assume, not exactly sure at this point what causes the initial error condition). The way I was handling that error was just bad code that should not be there.

**Comment by jgyates** [comment]
If you have any other errors  they will be reported in /vat/log/mymail.log

**Comment by liltux** [comment]
Sounds good, thanks.
