### ISSUE TITLE
Cat6 for cable?

### ISSUE THREAD

**Issue by rastam4n** [jgyates/genmon#224]
Hi All
I am making my cable and I wonder if Cat6 could be used for the two wires between the generator and the db9 connector. Also is there any reason not to locate the pi3 away from the generator... for example in the house approximately 20’ of cable.
Thanks
Peter

**Comment by rastam4n** [comment]
Hi All
I am making my cable and I wonder if Cat6 could be used for the two wires between the generator and the db9 connector. Also is there any reason not to locate the pi3 away from the generator... for example in the house approximately 20’ of cable.
Thanks 
Peter

**Comment by trimixdiver1** [comment]
I used outdoor grade cat5e and my run is 50ft, no problems

**Comment by krisasmith** [comment]
I put my pi3 in a electrical box next to the transfer switch in my garage about 20ft away from the generator. I power the pi with PoE (using an adapter from amazon) and use a shielded 4 conductor security wire from home depot for the data (send/receive) an a common ground. The wire is much smaller in diameter then cat6 so its easier to run though the conduit with the rest of the wires for the generator.
