### ISSUE TITLE
Can I modify layout of Status Screen on Webserver

### ISSUE THREAD

**Issue by jimland58** [jgyates/genmon#226]
Is it possible for me to modify one of the files so I can move the Time: section on the Status page in the webserver to just below the kW Output chart instead of where it is now on the bottom of the Status page?

**Comment by jgyates** [comment]
Yes,  but there are trade offs in complexity.

To simply move the time to the top of the text output items you can change the lines in /genmon/genmonlib/generac_evolution.py (lines 3378) from this:

            Status["Status"].append({"Engine":Engine})
            Status["Status"].append({"Line":Line})
            Status["Status"].append({"Last Log Entries":self.DisplayLogs(AllLogs = False, DictOut = True)})
            Status["Status"].append({"Time":Time})

To this:

            Status["Status"].append({"Time":Time})
            Status["Status"].append({"Engine":Engine})
            Status["Status"].append({"Line":Line})
            Status["Status"].append({"Last Log Entries":self.DisplayLogs(AllLogs = False, DictOut = True)})

To make the time immediately under the graph would require modifications to the javascript and css files. Also be aware that if you make changes they will be overwritten when you perform and software update.

**Comment by jimland58** [comment]
On top of the text will work and understand it will overwrite on updates.  Thanks Jason!
