### ISSUE TITLE
GENMON all of a sudden stops communicating with generator after several months of working???

### ISSUE THREAD

**Issue by jimland58** [jgyates/genmon#228]
### ACTUAL BEHAVIOR

Was working great for the last several months and then all of a sudden yesterday I got a text message stating Generator Monitor Communication Warning not communicating with the controller

Status webpage not showing any generator data.  Shows monitor time but nothing for Generator Time.   Monitor webpage showing Packet Timeouts and continually climbing.

### TROUBLESHOOTING
Did a reboot of the Genmon and same results, not communication with Generator.

Pulled the Generator Monitor out and ran the serial test jumpering pin 7 & 8 from the cable end that plugs into the controller and it passed.  Connected it back to the generator and still get the same thing, Communication Warning, no data, no generator time, and packet timeouts.    

From mymodbus.log: (get same message every 3 seconds)
2019-01-19 12:08:04,551 : Error: timeout receiving slave packet for register 0245 Buffer:0

Ran serialconfig -c test and everything shows ok:

Checking : BT service disabled: OK
Checking : Serial console command line removed: OK
Checking : Is enable UART in boot config: OK
Checking : Is BT overlay disabled: OK
Checking : Serial console service disabled: OK

### Screenshot or Pictures relating to the problem (if possible)

{Please write here}

### Your Environment

- Generator Model: 2018 Generac 22kW
- Generator Registers: Submit via the About page
- Genmon Version: V1.12.11

**Comment by jimland58** [comment]
FYI, looking at closed Issues, saw that Issue #205 has a problem with the RS232/TTL converter.  I have the same one that he had a problem with, the DZS Elec version but doing the serial loop back test it works???

**Comment by jgyates** [comment]
@jimland58 

Since you have an Evolution 2.0 I would first suggest restarting your controller. This appears to have worked for @beschaaflh 

https://github.com/jgyates/genmon/issues/198

**Comment by jimland58** [comment]
Performed the controller reset and it fixed the problem!  Thanks Jason!

liltux, it showed Firmware V1.06, Hardware V1.00.   I was worried it may have stopped working because of some automatic firmware update but doesn't look like that was the issue.

**Comment by jgyates** [comment]
I am glad it is working. Thanks for the feedback. This helps others with Evo 2.0.

**Comment by jgyates** [comment]
Hi Jim,

Just out of curiosity, have you been able to use the software with wifi turned off?  I have heard of one person who had and issue where they could not get serial port data from the controller if the wifi was off, but this . was not using genmon so it may be another issue or it may be related to the issue you have seen (serial output stops randomly with Evo2.0, but a controller power cycle corrects the problem.)

**Comment by jimland58** [comment]
Sorry for the late reply.  I'm from Louisiana and was busy watching the Saints get screwed by the referees yesterday!!!!!!!!!

So I turned the wifi off today around 4pm and verified it was off by seeing the MobileLink App go from On-line to Not Connected.   It's now 7pm and Genmon is still working perfect.

**Comment by jgyates** [comment]
Thanks for doing this test. This helps.
