### ISSUE TITLE
Enhancement request: Remove TLS from mail config

### ISSUE THREAD

**Issue by ToltingColtAcres** [jgyates/genmon#232]
mymail.py contains the following code:

        try:
            if self.SSLEnabled:
                 session = smtplib.SMTP_SSL(self.SMTPServer, self.SMTPPort)
                 session.ehlo()
            else:
                 session = smtplib.SMTP(self.SMTPServer, self.SMTPPort)
                 session.starttls()
                 session.ehlo
                 # this allows support for simple TLS
        except Exception as e1:
            self.LogErrorLine("Error SMTP Init : SSL:<" + str(self.SSLEnabled)  + ">: " + str(e1))
            return False

thus, it assumes if you are not running ssl on your mail server, you're running TLS.

Some of us run neither (internal mail server w/o external communication capabilities) so tls and ssl really are not necessary. However, genmon will not allow this configuration. The workaround at the moment is to simply comment out the starttls and ehelo lines, but that's sort of a pain as it requires shelving changes each time you want to pull updates from the repo.

Please consider adding a

disabletls = true/false

option to /etc/mymail.conf

and changing genmonlib/mymail.py to wrap the tls code in an if statement.

**Comment by jgyates** [comment]
@ToltingColtAcres 

It did not occur to me that this could be an issue. I will make this update. I should have it completed later today or tomorrow. I will let you know when it is complete.

**Comment by hokie21** [comment]
While it still works if an IP address is entered for the SMTP server, the GUI makes it red which would lead you to believe that only FQDN is supported.
![by ip](https://user-images.githubusercontent.com/37786152/52907151-cd868c00-3220-11e9-8551-e68f647bf685.jpg)
