### ISSUE TITLE
ERR_CONNECTION_RESET after latest update

### ISSUE THREAD

**Issue by SethL** [jgyates/genmon#233]
### Expected Behavior
Web console up 100% of the time

### Actual Behavior
After the most recent update, genmon will fail to load the webpage after a period of time with this error:
ERR_CONNECTION_RESET

### Steps to Reproduce (including precondition)
Reboot pi, everything works great.  eventually (minutes hours etc) the page will not load.  I submitted my logs but I had to reboot before submission because the webconsole wouldn't load until I did

### Your Environment

- Generator Model: G0070421
- Generator Registers: Submitted
- Genmon Version: 1.12.15

**Comment by SethL** [comment]
Thanks so much for looking at this.  It has been really cold here, almost below freezing now.  Maybe that has something to do with it.  I don’t really use the weather part so I just disabled that.  I’ll open up the gen cabinet tomorrow and check all of the connections, maybe something is not making good contact.

 

Thanks again!

**Comment by SethL** [comment]
Could the serial packet drops cause the fuel counters to reset to 0?  This has happened 2 times in the past couple of weeks?  I had 425 gal to start with and it was down to 422 when it reset to zero.  I set it at 422 and then it slowly went down every 2 weeks when it exercised.  Now it is back to 422 again and it says I have consumed 0 gal.

**Comment by jgyates** [comment]
@SethL 

I don't know of any correlation in the code that would cause that to happen.  Also, the logs do not report any errors except the ones I mentioned earlier. Resetting the power / fuel monitoring logs will just delete the file genmon/kwlog.txt so I don't think that would cause the problem.

**Comment by SethL** [comment]
The first time it happened I got an email saying that I had low fuel on the generator and it said I had 0gal remaining.  I about had a heart attack until I reminded myself I didn’t have a fuel sensor lol.  I always take the updates so maybe something got screwy during one of them or something.

**Comment by jgyates** [comment]
The fuel email notice is not from a fuel sensor, but from the estimated fuel calculation. It calculates the load (0-100%) of the generator and uses the fuel consumption numbers provided by generac to calculate how much fuel is being used, then it subtracts this from the tank size.

More details are here:

https://github.com/jgyates/genmon/wiki/Appendix-8-Monitoring-Fuel-and-Power-Usage

**Comment by jgyates** [comment]
I am closing this issue for now. Feel free to comment here if you have any other data or questions.
