### ISSUE TITLE
NON-issue wifi questions

### ISSUE THREAD

**Issue by liltux** [jgyates/genmon#246]
Does anyone have a good link to a working wifi adapter for using with raspberry pi.  I need to mount an external antenna for better range in wifi.  I did some looking through old issues and found broken links or items no longer available.  Just wanted to throw out there to everyone see which adapters work.  I just received one, assumed it should work, and it does not.  Thanks.

**Comment by jgyates** [comment]
[This](https://smile.amazon.com/Connecting-Wireless-Adapter-150Mbps-Raspberry/dp/B073J3HXZH/ref=sr_1_8?crid=1D3XICLWFQO82&keywords=raspberry+pi+usb+wifi+antenna&qid=1552402646&s=gateway&sprefix=raspberry+pi+usb+%2Caps%2C160&sr=8-8) one has worked for me.
