### ISSUE TITLE
Liquid Cooled Nexus Data

### ISSUE THREAD

**Issue by liltux** [jgyates/genmon#261]
Nexus liquid cooled.  Rpi Zero W.  No Alarm Log or Service Log display on Log page, only event/status Log.

@jgyates I just got around to plugging up to a liquid cooled Nexus at the shop.  I found that the remote start button, start/transfer both work on Liquid Cooled Nexus.

Although I did get an unknown register value/change and setup auto feedback.  

I also do not have any alarm or service logs on the Logs Screen, but I do have Run logs.  I have submitted several registers/logs under Rpi zeroW.

I do not have an air cooled nexus to use for data points.

![image](https://user-images.githubusercontent.com/17954856/57337543-6e356b00-70ef-11e9-8eb1-d66588373310.png)

Oh and by the way, I believe I have a loose/bad connection on my max232 board as lost comms during on of the register/log submittal.  So I tapped on my enclosure and comms came back up and sent more logs, just fyi.

**Comment by jgyates** [comment]
I got your logs. One thing that jumps out is the software currently thinks the underlying controller is an Air Cooled Evolution yet Register 0000 = 0x0006 which indicates a Nexus Air Cooled. The logs also indicate this (Nexus only has two logs, Evolution has three). One of two things could cause this:

1) The /etc/genmon.conf file is using the controller detetion override settings (evolutioncontroller=true, liquidcooled=false, these two should be empty, not true or false by default).
2) Genmon was not restarted after connecting the serial link after having been previously connected to another controller. Early on in the load process the software detects the controller and sets flags accordingly. If you unplug serial from one controller and reconnect it to another the genmon needs to be restarted. To resolve this just reastart genmon.

Let me know if a restart does not correct the problem.

**Comment by liltux** [comment]
@jgyates I will looking into the settings prolly hard coded as this was one of my original builds prior to some of the new settings and still using the original genmon conf file.  Thanks

**Comment by liltux** [comment]
@jgyates , got it all up to date.  So I have a few values not recorded.
0x0D - Missing Cam Pulse alarm
0x10 - Ignition Fault alarm

**Comment by jgyates** [comment]
Thanks, I will add these to the next release.
