### ISSUE TITLE
Any way to send mail to multiple addresses?

### ISSUE THREAD

**Issue by derekatkins** [jgyates/genmon#27]
Is there any way to configure mymail to send to multiple recipients?
Does a space or comma separated list work as expected?

**Comment by jgyates** [comment]
No, not at this time. I can add this to the new feature list.

**Comment by jgyates** [comment]
I just checked in the change to allow sending to multiple recipients. Just delimit them with a comma.

**Comment by derekatkins** [comment]
Oooh!  Awesome.  Thank you
