### ISSUE TITLE
locating controller connection help

### ISSUE THREAD

**Issue by farberm** [jgyates/genmon#274]
I have a new Evolution 2 22KW air cooled generator
I cannot identify the controller connection to hook up the serial connection
I took a few pictures and would appreciate any input.
One connection has a black/grey end connector on it (upper left part of picture). Does the grey cap need to be removed and connect into there?

I do not see an accessory port 1 sticker?

- Generator Model: 7043-2 - Evolution 2 
- Generator Registers: N/A
- Genmon Version: 1.13.14

![IMG_1919](https://user-images.githubusercontent.com/16128857/59554027-8066bc80-8f6b-11e9-8ac4-844cc4dc100a.jpg)
![IMG_1916](https://user-images.githubusercontent.com/16128857/59554042-a2f8d580-8f6b-11e9-8a96-88df32f7d174.jpg)
![IMG_1917](https://user-images.githubusercontent.com/16128857/59554069-0125b880-8f6c-11e9-93b5-b4b47ac22f2d.jpg)

**Comment by swvalenti194** [comment]
Peal off the orange tape on bottom of controller?

**Comment by farberm** [comment]
Is that a question or are you sure?

**Comment by jgyates** [comment]
These posts have some pictures of Evo2.0 connections:

https://github.com/jgyates/genmon/issues/234

https://github.com/jgyates/genmon/issues/198

https://github.com/jgyates/genmon/issues/149

**Comment by farberm** [comment]
thanks

**Comment by jgyates** [comment]
No problem. FYI you can search the issues by the tag "Evolution 2.0" to find all of the posts related to Evolution 2.0.

**Comment by swvalenti194** [comment]
It looks like red white blue and black next to the orange tape is where it should be. That feeding genlink?  Where does it go?

**Comment by swvalenti194** [comment]
Power. Ground. TX. RX. pinout looks right

**Comment by jgyates** [comment]
In the links above it shows it going to the built in wifi unit.
