### ISSUE TITLE
[Feature Request] User/Pass on HTTP

### ISSUE THREAD

**Issue by JMVS** [jgyates/genmon#277]
Hello @jgyates 

I was wondering if it was possible to have the user and password login option without having to enable https.

I've tried modifying genserv.py myself, and was able to get the auth page over http but I'm stuck there.

Thanks.

**Comment by jgyates** [comment]
If you setup via the web interface to use https and selected self signed certificate, save it, then If you edit /etc/genmon/genmon.conf directly and add a # to comment out the useselfsignedcert like this:

    #useselfsignedcert = True

If the software does not find this value it will revert back to http but keep the username and password.
