### ISSUE TITLE
Controller wire

### ISSUE THREAD

**Issue by farberm** [jgyates/genmon#278]
What gauge wire would be acceptable for going from the controller connection to the serial connectors. I am think about housing everything inside my basement and running a 25 foot section of 18/2 outdoor wire to the generator. 

That way I can route it is between the housing without even drilling holes in the housing of the generator.

Is 18/2 large enough or do I need to get 16/2 or 14/2?

**Comment by jgyates** [comment]
18 should be fine. This page specifies the gauge wire and other hardware.

https://github.com/jgyates/genmon/wiki/2--Hardware
