### ISSUE TITLE
Final Project Completion - minor issue with CRONTAB

### ISSUE THREAD

**Issue by rhombixt** [jgyates/genmon#28]
I have completed the Genmon install and have the genmon.py, gengpio.py, and gengpioin.py running successfully. Attached are some pictures of the final board and relay controller. I have used a fiber optic paired modem (bi-directional) for the connection between genmon and the generator. This solved the issue for distance (72 feet) and dealt with the issues regarding CRC errors and EMI issues from the genset. There is actually a great deal of data moving between the two systems constantly so having this unit connected with low-cap cable would have resulted in CRC issues I think. The unit has a crossover cable in between the Pi and the Fiber Modem, and then a second cross over between the genset and the second fiber modem. I have added my generator to your information request posting. I have also attached some pictures of the final board, and fiber modem pair. If you want to know where the gear is sourced from, I can add that to this posting.
The only issue I have - I can't seem to get the crontab gui to run the .sh script you posted. I have the gui based plugin added and I added the script as posted but it does not run automatically at boot up. What might I be missing?

**Comment by rhombixt** [comment]
![img_1071](https://user-images.githubusercontent.com/26971367/27519693-3a7958d2-59b6-11e7-86a8-2bcf563a71d4.JPG)
![img_1073](https://user-images.githubusercontent.com/26971367/27519694-3a79b37c-59b6-11e7-9ea1-2cc5ebb77217.JPG)

**Comment by jgyates** [comment]
That is great, I am glad it is working for you.

I have not used the crontab gui. I use the console to setup crontab jobs. The end of this page describes setting up crontab:

https://github.com/jgyates/genmon/wiki/Setting-up-your-Pi-and-genmon

in general you are just editing a text file with the nano editor. The command listed in the link above (sudo crontab -e) will start a text editor (choose nano if you are prompted) with the proper crontab script. Then just add the line listed in the above link and save the file.

**Comment by rhombixt** [comment]
One other small issue, when using the genserv.py application, I get "undefined" on the web page with no data..

**Comment by jgyates** [comment]
Does /var/log/genserv.py contain any errors? What is the full URL that you are using to access the web server?

Assuming you have an IP address of 192.168.1.10 on the PI running genmon and genserv you should use this as your URL:

http://192.168.1.10:8000

Also, can you use ClientInterface.py to access the pi? This tool allows you get get the same information that genserv displays.

**Comment by rhombixt** [comment]
017-06-25 17:32:45,186 : Error in app.run:[Errno 98] Address already in use

Client Interface works fine.

**Comment by rhombixt** [comment]
fixed it - update flask :-)

**Comment by jgyates** [comment]
Great! Let me know if you have any other issues
