### ISSUE TITLE
[Cosmetic] Web Interface gauges color indicators limits not correctly set for my country

### ISSUE THREAD

**Issue by JMVS** [jgyates/genmon#287]
### Expected Behavior

Have gauges at the web interface show the correct limits for voltage for my country (Argentina). Our standard supply voltage is 220VAC with a range of 200-230 for yellow.

### Actual Behavior

Gauges show miplaced limits (green/yellow/red) for my country.

### Steps to Reproduce (including precondition)

Set the voltage output of the generator to 220VAC

### Screenshot or Pictures relating to the problem (if possible)

![2019-07-06 (2)](https://user-images.githubusercontent.com/7751148/60762177-84e53900-a030-11e9-85ab-9fcfcc3a9d12.png)

### Your Environment

- Generator Model: 0062710 (Generac Evo 13KVA Air Cooled)
- Generator Registers: Sent via the About page
- Genmon Version: 1.13.21

### Suggestion

Maybe have an option in the advanced settings to set the limits for each gauge and band limit.

**Comment by jgyates** [comment]
Hi @JMVS 

I checked in v1.13.22 that has two new options on the advanced page.

Use Nominal Volts Override - Set to true to enable this feature
Override nominal line voltage in UI - set to 220 in your case 

If you make these two settings and save them then the gauges will use 220 as the nominal. The green will span +/- 5% of the nominal and the yellow will span +/- 10% of the nominal.

Let me know if you have any issues or questions.

**Comment by JMVS** [comment]
Working perfectly @jgyates. Thank you.
