### ISSUE TITLE
Incorrect displacement value for engine displayed on web interface

### ISSUE THREAD

**Issue by JMVS** [jgyates/genmon#289]
### Expected Behavior

Show correct displacement number in Maintenance Page (992 cc).

### Actual Behavior

Shows incorrect value (999 cc)

### Steps to Reproduce (including precondition)

Have a 0K3757 OHVI Engine?

### Screenshot or Pictures relating to the problem (if possible)

![Screenshot_2019-07-07 Generator Monitor](https://user-images.githubusercontent.com/7751148/60773047-8583db00-a0d5-11e9-97f2-0db89d1fe6f8.png)
![MVIMG_20190706_101557](https://user-images.githubusercontent.com/7751148/60773049-887ecb80-a0d5-11e9-8cb6-4e227e25a19b.jpg)

### Your Environment

- Generator Model: G0062710
- Generator Registers: Sent via the About page on July 6th 19
- Genmon Version: 1.13.22

**Comment by jgyates** [comment]
I checked in an update for this. Since this is only a displayed string I did not bump the version so you you can just do an update it it should show up correctly.
