### ISSUE TITLE
Can Not Connect Serial over TCP/IP  	 

### ISSUE THREAD

**Issue by wackyhobo** [jgyates/genmon#308]
I am trying to connect Genmon (V1.13.2) to my Generac Guardian 22kW Generator (G0065521) using Serial RS232 to Ethernet Converter (USR-TCP232-410S).

I was successful connecting Genmon serially to the generator.

I have the Serial RS232 to Ethernet Converter setup and I can connect with Modscan32 and see live values in the registers.

I enabled Serial over TCP/IP, set Serial Server TCP/IP Address and port. I then save changes. When that was unsuccessful, I reboot the Raspberry PI.

<img width="1920" alt="Screenshot 2019-08-10 20 53 44" src="https://user-images.githubusercontent.com/53457057/62828718-d5f9c700-bbb2-11e9-80ed-1f8653d15eb4.png">
<img width="1920" alt="Screenshot 2019-08-10 20 53 54" src="https://user-images.githubusercontent.com/53457057/62828719-d5f9c700-bbb2-11e9-8460-0b421f240c2e.png">
<img width="1920" alt="Screenshot 2019-08-10 20 54 19" src="https://user-images.githubusercontent.com/53457057/62828720-d5f9c700-bbb2-11e9-8b4d-dbd74c7a7d95.png">
<img width="1920" alt="Screenshot 2019-08-10 20 54 29" src="https://user-images.githubusercontent.com/53457057/62828721-d5f9c700-bbb2-11e9-9d05-1aa58a18a973.png">
<img width="1375" alt="Screenshot 2019-08-10 20 56 20" src="https://user-images.githubusercontent.com/53457057/62828722-d6925d80-bbb2-11e9-9417-4a42010667df.png">
<img width="561" alt="Screenshot 2019-08-10 21 00 11" src="https://user-images.githubusercontent.com/53457057/62828723-d6925d80-bbb2-11e9-94a4-d2b4f83159f7.png">
<img width="384" alt="Screenshot 2019-08-10 21 00 18" src="https://user-images.githubusercontent.com/53457057/62828724-d6925d80-bbb2-11e9-9e4e-babdaf49a760.png">

- Generator Model: {Generac Guardian 22kW Generator (G0065521e}
- Generator Registers: Submit via the About page
- Genmon Version: {Version V1.13.28}

**Comment by wackyhobo** [comment]
<img width="1920" alt="Screenshot 2019-08-10 21 18 15" src="https://user-images.githubusercontent.com/53457057/62828813-8b794a00-bbb4-11e9-844c-5e5643a1fc6c.png">
<img width="972" alt="Screenshot 2019-08-10 21 18 21" src="https://user-images.githubusercontent.com/53457057/62828814-8c11e080-bbb4-11e9-9b67-70928e4f5503.png">
<img width="972" alt="Screenshot 2019-08-10 21 18 33" src="https://user-images.githubusercontent.com/53457057/62828815-8c11e080-bbb4-11e9-9b50-f6437e637e77.png">

**Comment by jgyates** [comment]
@wackyhobo 

It looks like you have the USR device setup to be a modbus TCP server. Genmon expects the USR device to act as a simple serial TCP server (i.e. genmon handles the modbus protocol and the serial over IP device is just a pass through of the data).  Try changing the "Work Mode" parameter to TCP Server / None instead of TCP Server Modbus TCP.

This page has the requirements for serial over IP functionality.

https://github.com/jgyates/genmon/wiki/Appendix-F----Serial-over-IP

Let me know if this works for you.

**Comment by wackyhobo** [comment]
Perfect. It works now! Thanks!
