### ISSUE TITLE
Feature Request: Edit Journal Entries

### ISSUE THREAD

**Issue by lmackley** [jgyates/genmon#319]
A nice feature would be the ability to edit or delete individual journal entries.  Currently the only option is  to clear the entire journal and recreate if there is an error or a misspelling.

**Comment by jgyates** [comment]
@lmackley 

I  have this on the list for new features. I agree that this is a needed feature. Hopefully I will be able to get to this soon.

**Comment by lakee911** [comment]
I think this would be fantastic. An added benefit would be to provide a setting to disable clearing the journal entries. While not foolproof, it could simply hide the button and provide an extra level of safety (multiple-step process).

Does the backup feature also store the journal?

**Comment by jgyates** [comment]
Yes, the journal is backed up.

**Comment by jgyates** [comment]
This has been implemented with V1.14.28.

**Comment by lakee911** [comment]
Thank you!
