### ISSUE TITLE
Number of outages listed from log

### ISSUE THREAD

**Issue by dennis48755** [jgyates/genmon#320]
Hi,

Are the quantity of outages listed from the Outage Log restricted? I would like to be able to view all of them.

In GenMon under Outage, I have 50 log entries listed (with a scroll bar). However my outage.txt file contains 68 entries.

I did manually edit my outage.txt to add outages that occurred before I installed GenMon, but believe I did it correctly.

Thanks,
Dennis

Added: The last entry from outage.txt displayed by GenMon is 2018-05-04 15:56:43,1 day, 4:57:08

[outage.txt](https://github.com/jgyates/genmon/files/3795633/outage.txt)

**Comment by jgyates** [comment]
outage.txt will hold more than 50 outages and does not have a limit. The web interface will only display the last 50 entries for optimization reasons.

**Comment by dennis48755** [comment]
Jason, is there any way to make the truncated log data available from within the web interface. Maybe a drop-down selection to optional display 100 or all log entries?

Dennis

**Comment by jgyates** [comment]
Hi Dennis,

I checked in V1.13.30 that should make the display limit 100 instead of 50. Let me know if you have any issues.

Jason

**Comment by dennis48755** [comment]
Thanks Jason.

Dennis
