### ISSUE TITLE
Unsupported sensor info?

### ISSUE THREAD

**Issue by scyto** [jgyates/genmon#325]
Are you looking for more info or data from the unsupported sensors or is that generally a closed thread of investigation?

Today was first time I actually fired the gen up. I note that the RPM sensor was reporting consistent data and sensor 1 reported the value 115 consistently too.

The other sensors seemed to be all over the place, guess that is noise?
Also interesting to see the impact of quiet mode testing on the voltage outputs, what a cool tool, thanks!

**Comment by jgyates** [comment]
I am not actively looking into  these unsupported sensors. I have spent a lot of time  on this already and have come to the conclusion that this is internal data (raw sensor data that needs to be converted before it is useful for something, like RPMs, etc)
