### ISSUE TITLE
genserv.py problem with webpage

### ISSUE THREAD

**Issue by drandyhaas** [jgyates/genmon#33]
Other things working fine, but the genserv.py script gives a webpage problem for me, at http://192.168.55.105:8000/. See attached pic. This was from google chrome, but I also tried iexplore, and it's the same...

![clipboard01](https://user-images.githubusercontent.com/13686048/28235374-683b6fa2-68da-11e7-981f-75d9554a950d.png)

**Comment by jgyates** [comment]
Hi drandyhaas,

You may have an old version of Flask. Try this:

Flask version 0.12 or higher is recommended. You can validate your version of Flask by the following command:

 pip freeze | grep Flask

The output should show Flask==0.12.0 or higher. If your version of flask is not at least 0.12.0 then update your Flask with the following command:

 sudo pip install Flask -U

Then restart genserv.py

**Comment by drandyhaas** [comment]
That did it! Who are you?! Amazing software, and lightning-fast support, for free! I thank you again, sir.
