### ISSUE TITLE
USB to RS485 Adapter

### ISSUE THREAD

**Issue by USAFPride** [jgyates/genmon#34]
Currently I'm using [this](https://www.amazon.com/gp/product/B00NKAJGZM) adapter to modbus with my boiler.  Would this project also work with this device?

**Comment by jgyates** [comment]
Hi,

Unfortunately, no. While the communications from the controller does use the MODBUS protocol the electrical interface is RS-232, not RS485, so this adapter will not work.

**Comment by jgyates** [comment]
Closing issue. Feel free to reopen if you have any questions on this thread.
