### ISSUE TITLE
Add NG Usage graph or line item on status page. Maybe (3) broken down into Outage vs non outage and total

### ISSUE THREAD

**Issue by Appfrontier** [jgyates/genmon#341]
Based on the post here: https://github.com/jgyates/genmon/issues/302#issuecomment-513499326

I can use the `cmd/power_log_json?power_log_json=0,fuel` to get a result

I have not had an outage since I installed the genmon but I did manually run the gen. When I use that command I get 

**3.35 cubic feet**

The problem is I cannot find this anywhere in the genmon ui.

Reading this thread: https://github.com/jgyates/genmon/issues/293

it appears the usage is only shown for outages.

IMHO it would be useful to know how much NG is being consumed or has been consumed since reset.

Ideally for those of us with NG there would be three categories:

1. Exercise or non-outage (manual)
2. Outage
3. Combined usage

Having a graph like the kW output or similar over a period of time would be great. At a minimum having these values on the status page as line items would be a good start.

**Comment by jgyates** [comment]
The maintenance page shows the following:

    kW Hours in last 30 days : 
    Fuel Consumption in last 30 days : 
    Total Power Log Fuel Consumption : 
    Run Hours in last 30 days : 

I have opted not to include this info in a graph for performance reasons (i.e. there is a lot of data to transfer for the graph on top of the kw log data currently being used).

**Comment by jgyates** [comment]
If yours does not show this let me know.

**Comment by Appfrontier** [comment]
> The maintenance page shows the following:
> 
> ```
> kW Hours in last 30 days : 
> Fuel Consumption in last 30 days : 
> Total Power Log Fuel Consumption : 
> Run Hours in last 30 days : 
> ```
> 
> I have opted not to include this info in a graph for performance reasons (i.e. there is a lot of data to transfer for the graph on top of the kw log data currently being used).

Mine does not show that info:

<img width="225" alt="image" src="https://user-images.githubusercontent.com/16980522/72106948-5f4a2c80-32fe-11ea-86ab-bb0653c1f3d3.png">

**Comment by jgyates** [comment]
If you have outgoing mail setup you can send me your logs on the About page. With this data I can likely determine why this is occuring. My guess is that it is due to a logic error. NG systems do not show the fuel gauge since this only applies to stored fuel, but they can still show how much fuel is used.

**Comment by Appfrontier** [comment]
> If you have outgoing mail setup you can send me your logs on the About page. With this data I can likely determine why this is occuring. My guess is that it is due to a logic error. NG systems do not show the fuel gauge since this only applies to stored fuel, but they can still show how much fuel is used.

Done

**Comment by jgyates** [comment]
I checked in an update that should fix this issue. The problem caused the fuel stats listed above not to be displayed for NG systems (or any system with a tank sizes of zero, NG systems do not allow the tank size to be modified). This would also prevent fuel calculation from showing up in the outage log for NG system. Let me know if you have any issues.

**Comment by Appfrontier** [comment]
> I checked in an update that should fix this issue. The problem caused the fuel stats listed above not to be displayed for NG systems (or any system with a tank sizes of zero, NG systems do not allow the tank size to be modified). This would also prevent fuel calculation from showing up in the outage log for NG system. Let me know if you have any issues.

That fixed it. Thanks
