### ISSUE TITLE
Unauthenticate SMTP Feature Request

### ISSUE THREAD

**Issue by zbourdeau** [jgyates/genmon#342]
First off, this is a great effort. Thank you for putting this together for the community! I have been using your genmon project successfully with a <a href="https://www.usriot.com/products/serial-wifi-converter.html">USR serial to Wifi convertor</a> using the TCP /IP option with great success.

I would like to respectfully request the addition of a boolean value to allow an unauthenticated SMTP server for outbound email. For those setups where an on premise SMTP server may be present this would be very helpful.

- Generator Model: Generac 17Kw- 2016 model
- Genmon Version: V1.13.33

**Comment by zbourdeau** [comment]
@jgyates can you add me as a collaborator on this project? I created a branch for the unauthenticated SMTP change and got it working and would like to submit a PR for you to take a look at.

**Comment by jgyates** [comment]
you are now a collaborator.

**Comment by zbourdeau** [comment]
It looks like I am still missing permissions to push/ create a branch:

Opening repositories:
S:\Sources\genmon
Pushing smtpauthoption
Error encountered while pushing branch to the remote repository: Git failed with a fatal error.
unable to access 'https://github.com/jgyates/genmon/': The requested URL returned error: 403
Pushing to https://github.com/jgyates/genmon

I'm not sure what is up. Here is a link to a document which may help though: https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository

**Comment by jgyates** [comment]
You have to accept the collaborator invitation.

<img width="735" alt="Screen Shot 2020-01-10 at 12 50 54 PM" src="https://user-images.githubusercontent.com/4513286/72174648-32eaea80-33a8-11ea-90c0-e5d484d05c5e.png">

**Comment by jgyates** [comment]
you should have received a link via email. You may check your spam folder.

**Comment by zbourdeau** [comment]
Ack. I accepted and added my PR. Please review it.

**Comment by jgyates** [comment]
Looks great! It is merged. The only thing I added was I created a tool tip for the setting, all other changes were taken unchanged. Thanks for your help!
