### ISSUE TITLE
Openweather API Rain total issue

### ISSUE THREAD

**Issue by Appfrontier** [jgyates/genmon#344]
The OpenWeather API seems to only return rain for the last 1h

The monitoring always shows Rain last 3 hours as 0

<img width="245" alt="image" src="https://user-images.githubusercontent.com/16980522/72208210-495b7980-346e-11ea-97ba-1ca383c033e6.png">

When making a call to the api as follows:

api.openweathermap.org/data/2.5/weather?id=5161911&APPID=XXXXX

The returned JSON for the rain object is as follows

<img width="194" alt="image" src="https://user-images.githubusercontent.com/16980522/72208224-642dee00-346e-11ea-841c-83c680ecf0fd.png">

The docs show that either could be returned. Not sure why it is showing rain for 1h but 0 for 3h as shouldn't the 3h total include the 1h total lol...

The docs show:

<img width="386" alt="image" src="https://user-images.githubusercontent.com/16980522/72208273-d272b080-346e-11ea-8fa0-47a7c0418e87.png">

So I guess it would be nice to see both the 1h and the 3h as the docs state if the event has no data it will not be shown hence why 3h is missing.

**Comment by jgyates** [comment]
I checked in V1.13.36 that should fix this problem. Good find. Thanks for the feedback. In testing it looks like this data can be returned from the openweather servers as only 1h. The code is now setup to show 1h and 3h if both are returned from the server. In my testing I am only seeing the 1h returned. Let me know if you have any issues or questions.

**Comment by Appfrontier** [comment]
Thanks. May be a small bug but each one is an opportunity to review code :)

**Comment by JeanB51** [comment]
FWIW, I see on the openweathermap site, that you can either query 4day-hourly forecasts, or 5-day/3-hour forecasts...maybe this is why only one of the fields is filled in ?
https://openweathermap.org/api


Jean

    Le samedi 11 janvier 2020 13 h 49 min 52 s UTC−5, Appfrontier <notifications@github.com> a écrit :  
 
 
Thanks. May be a small bug but each one is an opportunity to review code :)


.

**Comment by Appfrontier** [comment]
The 5 day forecast does indeed return 3h rain (forecast) for each 3 hour time block. I would assume the hourly forecast would return the 1h but cannot prove it since my API key does not allow access to the pro endpoint.
