### ISSUE TITLE
New Model, no open molex port on board

### ISSUE THREAD

**Issue by TikiGuy** [jgyates/genmon#350]
I set up an 11KW model a few years back with zero issues.  Moved into a new house and had a 16KW model installed and the connection point under the sticker appears to not have the molex connector soldered in.  It looks like port 1 is the proper connection type but is already in use.

Model: G0071760
16KW GUARDIAN-NO T/SW AL

![Capture](https://user-images.githubusercontent.com/39140328/73017362-b0bde580-3ded-11ea-8249-9fcab074963d.PNG)

**Comment by liltux** [comment]
@TikiGuy does your unit have an Evolution 2 controller?  If so that is for the mobillink wifi module.  You will have to either remove the mobile link and go with yours or use a splice cable that will allow both to be connected.

**Comment by TikiGuy** [comment]
Yeah Evolution 2 controller.  Guess they connect to it with their included wifi now.  I'll unplug that one and give it a go later tonight.  Thanks for the quick reply.

**Comment by TikiGuy** [comment]
I was able disconnect the right connector in the picture above and plug in there.  Didn't work until I remembered about shared ground, hooked up to battery for power and it started working.

Thanks for your assistance.
