### ISSUE TITLE
Typo in SNMP support description

### ISSUE THREAD

**Issue by magomez96** [jgyates/genmon#352]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below.

***NOTE:*** If you are having issues with your serial connection, please read this page before posting:

https://github.com/jgyates/genmon/wiki/3.6---Serial-Troubleshooting

If you are having other issues, please see the following page:

https://github.com/jgyates/genmon/wiki/3.5---General-Troubleshooting

If you need to send you logs and registers to the developer, if you email is setup and working properly you can click send your logs on the About page in the web interface.

### Expected Behavior

SNMP support add on should read “ Allow Genmon to respond to SNMP requests”

### Actual Behavior

SNMP support add on description reads “ Allow Genmopn to respond to SNMP requests”

### Steps to Reproduce (including precondition)

Open add ons page

### Your Environment

- Generator Model: 7043
- Generator Registers: Submit via the About page
- Genmon Version: 1.14.00

**Comment by jgyates** [comment]
I checked in a fix. I did not change the version as this was a simple typo and not executable code changed so you can just use the update button and it will fix it. Thanks for the feedback.
