### ISSUE TITLE
Verify Setup

### ISSUE THREAD

**Issue by farberm** [jgyates/genmon#354]
1. I am not receiving any data from the generator to the Pi. I have tested the cable and it passes without any issues. I suspect it may have to do with the grounding setup. Could you please verify that I have this correct. 
2. If my ground wiring is correct,  do I have to have wifi turned on to receive data. I currently have not set the wifi on the generator up at all?

Wiring Setup as follows:
GPIO Board to RS232
Pin 4 --> Black Wire --> VCC
Pin 6 --> White Wire --> GND
Pin 8 --> Grey Wire --> TX
Pin 10 --> Purple Wire --> RX

This the the board I ordered: https://www.amazon.com/gp/product/B01JYNHNW6/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

Generator Battery --> Motorcycle USB Power cable (Red positive.Black Ground)--> Power to PI

Generator Battery GND --> Clear Wire --Breakout DB-9 Pin 5

Molex 8 --> Red Wire --> Breakout DB-9 Pin 2
Molex 7 --> Black Wire --> Breakout DB-9 Pin 3
![B6A8D899-2B61-49D3-8A35-0301D4974BD3_1_105_c](https://user-images.githubusercontent.com/16128857/74580164-0e69cb80-4f6f-11ea-8a17-5645eec4c494.jpeg)
![FC08BBF5-34C9-4181-8A72-C18410DD6F23_1_105_c](https://user-images.githubusercontent.com/16128857/74580172-14f84300-4f6f-11ea-849b-0e2a8a503880.jpeg)
![D0F2B3A3-B473-4D3F-BB43-809C5CB58D00_1_105_c](https://user-images.githubusercontent.com/16128857/74580175-19bcf700-4f6f-11ea-826e-21878d21f795.jpeg)
![7184BE62-BDAC-4228-977C-7A9D00E8EACD_1_105_c](https://user-images.githubusercontent.com/16128857/74580181-25a8b900-4f6f-11ea-8716-c5b1e66f41a0.jpeg)

### Actual Behavior
No data passed from Generator
### Steps to Reproduce (including precondition)
Tested the serial connection and it passes. I have tested the cable all the way to the molex connector.

### Screenshot or Pictures relating to the problem (if possible)

See attached.
Generator Evolution 2

- Generator Model: Evo 2
- Generator Registers: 
- Genmon Version: 1.13.38

**Comment by jgyates** [comment]
I can't make out the pin connections on your molex to verify the pin numbers are correct from the picture.

Try swapping pin 2 and 3 on the green breakout connector. If the loopback works and the ground is good this would be the next thing to try.

The pinout for a male vs female DB9 connector is different (pins 2 and 3 are reversed depending on if the connector is male or female). Assuming you have a female DB9 you should be using the lower example in this picture.

https://raw.githubusercontent.com/jgyates/genmon/master/Diagrams/Cable_Connections.jpg

Also, the clear wire does not appear to be going to the ground pin on the green breakout connector (unless there are two ground pins).

**Comment by farberm** [comment]
Here are some more pictures.

Red Wire is going to Pin 2, Red wire going to Molex Pin 8 top left on picture
Black Wire is going to Pin 3, Black wire going to Molex Pin 7 second to the left on the top row

Here is a picture of my RS 232 Female correct?


**********
Clear wire may be the issue. I have it going to Pin 5 on the DB-9... I realize that the GND is listed on the other side of the DB-9 but Pin 5 is GND on the RS 232 according to your diagram? Am I misreading which GND you are referring to?


 Is this my problem?
********

**Comment by jgyates** [comment]
Yes, pin 5 is ground on the RS-232 DB-9 connector. If you screw down connector labeled 5 goes to ground you should be OK.

The pictures get stripped off if you send them as attachments. You have to attach them from the github web interface.

**Comment by jgyates** [comment]
Were you able to get this working?

**Comment by farberm** [comment]
Will reinstall tomorrow

**Comment by jgyates** [comment]
I am closing this issue. If you have any other questions on this topic feel free to post them to this thread.
