### ISSUE TITLE
Unknown Alarm

### ISSUE THREAD

**Issue by JeremyStevenson** [jgyates/genmon#37]
Got the following unknown alarm. I cleared the "check battery" and it went away. (Nice note in this email to do that!)

Time: 08:02:12 PM
Date: Sun 27-Aug-2017

Notice from Generator:

Switch State: System in Alarm
Engine State: Cranking in Alarm

Current Alarm: UNKNOWN ALARM: 00020014
System In Alarm: 0001:00020014

Last Log Entries:
    Start Stop Log: 08/23/17 20:31:35 Stopped - Auto
    Alarm Log:      08/23/17 20:31:35 Check Battery

To clear the Alarm/Warning message, press OFF on the control panel keypad followed by the ENTER key.

**Comment by jgyates** [comment]
Hi Jeremy,
I just uploaded a new version of genmon.py that added this to the alarm logic. Thanks! Let me know if this does not fix it the next time a check battery alarm occurs.

-Jason

**Comment by jgyates** [comment]
I updated Genmon to version 1.12.11 to include this alarm condition.

**Comment by JeanB51** [comment]
Thanks for this, and the overall great support

Jean
