### ISSUE TITLE
Please add error code text to Alarm logging

### ISSUE THREAD

**Issue by jeepjungle** [jgyates/genmon#372]
Alarm log error code: 0x0E

Generator displays text:  Missing Crank Pulse

### Your Environment
Generator Monitor Stats :
        Monitor Health : OK
        Controller : Nexus, Liquid Cooled
        Run time : Generator Monitor running for 20 days, 0:33:07.
        Generator Monitor Version : V1.14.03

- Genmon Version: Current Version: V1.14.03

**Comment by jgyates** [comment]
Done. Version 1.14.06 contains this update.

**Comment by jeepjungle** [comment]
Thank you.  You rock.
