### ISSUE TITLE
Info on how to get and add free LetsEncrypt signed certificates to genmon..

### ISSUE THREAD

**Issue by rnatalie** [jgyates/genmon#375]
wrote a brief addition to the WIKI to explain how to install free LetsEncrypt certificates into GENMON so chrome and other browsers stop griping about the self-signed certificate.

Alas github doesn't handle forks for the wiki like it does the sources.   Here's the link into my fork

https://github.com/rnatalie/genmon/wiki/Appendix-K----Adding-LetsEncrypt-certificates-to-Genmon

I'm thinking of fixing the genmon code itself to handle the "webroot" authentication so that the update of the certifciate can be automatic.

**Comment by jgyates** [comment]
I can add you to the project if you like. Just make the webroot authentication and optional feature. Let me know if you have any questions if you decide to jump in.

**Comment by jgyates** [comment]
I added your wiki entry to the project:

https://github.com/jgyates/genmon/wiki/Appendix-K-Adding-LetsEncrypt-certificates-to-Genmon

**Comment by hokie21** [comment]
@rnatalie Can the certificate renewal step be automated with cron so that it is done automatically just shy of every three months?

**Comment by rnatalie** [comment]
I’m working on that!  

 

@rnatalie <https://github.com/rnatalie>  Can the certificate renewal step be automated with cron so that it is done automatically just shy of every three months?

**Comment by jgyates** [comment]
I am closing this for now. Feel free to post to this thread on related issues.
