### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by sjbader** [jgyates/genmon#38]
Is anyone interested in push notifications versus SMS notifications? I've implemented this using the Pushover app. There is a one-time fee to Pushover (I think it's $4.99, but you get a free 7 day trial) and then it's free for all your devices.

I already have the code and I'm already using it with Genmon. If you guys are interested, I can work with Jgyates and see if I can get it included and get some documentation together.

**Comment by jeepjungle** [comment]
I am interested.  I am planning to switch all my home automation communications to pushover.  Good timing!

**Comment by jgyates** [comment]
Sounds good. I would be glad to add it.

On a side note, I have an Android app and a module that runs on the PI that will use Google Firebase Messaging for push notifications to the android app. I have not written any documentation yet. The catch is that it requires one to register with google and get a Firebase app ID, set the corresponding IDs in the app and on the server, so this is not a simple run the app and go, you need to recompile the app for each installation to tie the unique ID you registered to the android app. If there is interest I can try to clean this up and add some docs and post it.

**Comment by sjbader** [comment]
As promised, here is the code and config file. Install is super simple.

1) pip install chump
2) Copy genpushover.py to the root directory where all your other genmon files are.
3) Copy genpushover.conf to /etc and configure as following:
    appid is generated when you log into pushover.net and at the bottom next to "Your applications" click on "Create Application/API Token". I don't recall exactly, but I'm pretty sure I chose the 'application' type from the dropdown that is provided. I don't think it much matters. Once you create your app, you're provided with a long and unique application/API token. That's what you provide from the appid value.
   userid is your user key and is provided when you log into pushover.net.
   pushsound is the custom sound field. I want my genmon to sound different than other alerts, so I don't choose the default. There is a link to the list of options in the .conf file.

4) Add the following in the 'start' case in startgenmon.sh:
sudo python /home/pi/genmon/genpushover.py &
5) Add the following in the 'stop' case in startgenmon.sh:
    sudo pkill -f genpushover.py

That should be it. Run 'sudo python genpushover.py' to see it in real time. You can add an & at the end to run it in the background, just like all the other scripts.

Let me know if there are any questions or problems!

-Steve


[Archive.zip](https://github.com/jgyates/genmon/files/1290893/Archive.zip)

**Comment by jeepjungle** [comment]
This is awesome.  Thank you so much.  All set up.  Only problem I had was after "pip install chump" running genpushover.py exited on a chump error, then I did "sudo pip install chump" and it worked fine after that.

Thanks,
Rob

**Comment by sjbader** [comment]
Awesome! Glad it worked. I don't want to pay for SMS so this was an easy fix. Glad someone else is using it! 

-Steve

**Comment by jgyates** [comment]
Added to the repository, read.me and wiki. Thanks @sjbader! Let me know if I missed anything in the writeup.

**Comment by sjbader** [comment]
Looks good! Thanks!

**Comment by proppilot** [comment]
@sjbader, fantastic add to the project.  Just got mine up and running today and enabled this off the bat.  Excellent !

**Comment by jgyates** [comment]
Closing issue now that this has been added to the wiki. Feel free to continue discussion on this thread as needed.

**Comment by proppilot** [comment]
Did anything break or change after the upgrades (say since December) that may have affected pushover ?  My push no longer works since I upgraded.  The genpushover.conf file in /etc looks intact yet not working ?  Email is fine

**Comment by jgyates** [comment]
Nothing that I can think of. There should be a log file in /var/log/genpushover.log that would have any errors specific to genpushover.

One thing that it could be is that if you updated the startgenmon.sh file has changed and you would need to uncomment the lines for genpushover.py in the startgenmon.sh file. Now there are three places that would need to be uncommented rather than two. If you did not do this then genpushover is not running.

The new startgenmon.sh now has three command line options (start, stop and restart) it used to only have two (start and stop).

**Comment by proppilot** [comment]
Thanks Jason.  Right after I posted this and watched a bit of TV I thought of exactly that and it was the issue.
