### ISSUE TITLE
Making a cable wiki suggestion

### ISSUE THREAD

**Issue by skipfire** [jgyates/genmon#385]
On the wiki for making a cable, I would suggest updating the text above the molex pinout from

`Molex Pinout (Digikey P/N WM3703-ND):`

to

`Molex Female Pinout (Digikey P/N WM3703-ND):`

I spent hours trying to figure out my serial issues and why I was seeing my Pi's ground as 13.4v higher than the battery ground.  I'm really glad I was powering the Pi from a battery pack for testing so it wasn't trying to tie the generator battery terminals together.

**Comment by jgyates** [comment]
Done

**Comment by skipfire** [comment]
@jgyates thanks a ton, this is really great stuff and fairly easy to get working, when I got out of my own way.
