### ISSUE TITLE
Can't stop an exercise from the webpage

### ISSUE THREAD

**Issue by lakee911** [jgyates/genmon#397]
When generator runs its exercise, the running condition is shown on the webpage, however, the stop button doesn't work. Can this be fixed? Occasionally, we like to stop the exercise if we're outside when it runs. Placing generator in stop, at its control panel, and then back to auto is the only way to stop the exercise.

**Comment by jgyates** [comment]
No, not that I am aware of. These start, stop, start/transfer commands are just codes that are sent to the firmware so the controller is in charge of executing these commands. Unless I can figure out a way to remotely change the off, auto, manual buttons on models other than the liquid cooled Evolution, I don't know of a way to do this.
