### ISSUE TITLE
Remote Start Register and Value? 

### ISSUE THREAD

**Issue by granttoth** [jgyates/genmon#399]
First off... Really fantastic software!

I don't have a specific issue and I didn't see a way to direct message you. I apologise if this is not the appropriate way to contact you.  Please allow me to ask you a question about control with the H-100.

Unfortunately I'm in a position where a Raspberry Pi won't be ideal for my situation but a simple microcontroller will be great.  I've programmed an Arduino using the registers listed and so far everything is working well except for the remote start, remote stop and acknowledge alarms. Can you clarify this for me?  

I see you use the write multiple registers command, there is an input listed at 0x0080 and the bit in that register at 0x1000. This does not work for me.  I noticed another section where you have what looks to be start, stop, and start transfer code that builds the data to send based on the value, value2, and value3 data.  Then your writing 3 registers.  

I've tried all sorts of various combinations of writing to these registers in an attempt to start, stop and acknowledge alarms, but I'm missing something here.  Do you have any advice?  Oh I should mention that the generator does work as expected when using a Raspberry Pi with Genmon.  Also my Arduino is writing as expected when I test it with a modbus simulator... I'm simple missing something.

Thanks for your time!

**Comment by jgyates** [comment]
the 0x0080, 0x1000 are just status bits. You want to look at the code in generac_HPanel.py line 2056. 

https://github.com/jgyates/genmon/blob/master/genmonlib/generac_HPanel.py#L2056

This code is writing three consecutive registers in one modbus transaction. The starting modbus address is 019c (START_BITS). You will notice that the code has more functionality that is exposed from the UI as not all of this has been validated and some of it depends on the type of transfer switch that is used by the H100 or Gpanel generator. You can look at the data like this:

Reg - > DataHigh: DataLow
019c  > ValueHigh: ValueLow
019d - > Value2High: Value2Low
019e -> Value3High: Value3Low

The modbus packet would look like this:

ADDRESS,COMMAND, REGISTER, NUM_REGISTERS,  NUM_BYTES, DATA, CRC

Using the values from the code (Value, Value2, Value3) the packet should look like this:
0x64 - Modbus Address
0x10 - Write Modbus register command
0x01 - High byte of starting register 019c
0x9c - Low byte of starting register 019c
0x00 - Number of registers high byte (0x0003)
0x03 - Number of registers Low byte (0x0003)
0x06 - Number of Low (0x06)
Data - Value High byte
Data - Value Low Byte
Data - Value2 High byte
Data - Value2 Low Byte
Data - Value3 High Byte
Data - Value3 Low byte
CRC
CRC

you can contact me at generatormonitor.software (at) gmail

**Comment by liltux** [comment]
@granttoth would you be interested in sharing your Arduino code?

**Comment by granttoth** [comment]
Yes absolutely.  I had planned on reporting back here once I add the control commands, and I can add my Arduino sketch too.

Heads up, I'm not great at writing code, however it's working great so far. I would love some more eyes on it to help fine tune things.  I'm going to try to find the time to add the start, stop, and alarm reset commands tomorrow.

**Comment by granttoth** [comment]
@liltux I finally got around to this.  Here is what I have so far.  I started adding a struct array with all the registers and such, however I'm debating on if I need to do that or not.   If you have any advice or thoughts, please jump on in and make some changes.   

`/*
    This sketch is intended to work with a TTL to RS232 shield/board and a relay board or two.
    You will also need some sort of relay/button to trigger the start, stop, and to reset the alarms.

    Make sure to install the ModbusMaster library in the Arduino IDE.
    Tools > Manage Libraries

    The registers in the testing function are used to force the generator to show results. Pulling a sensor and such.  I haven't tested this part yet.

*/

#include <ModbusMaster.h>

int startPin = 19;
int stopPin = 18;
int ackAlarmPin = 17;

// Timer used to set the metering interval
const unsigned long eventInterval = 3000;
unsigned long previousTime;

// Generator slave ID
const int genId = 100;

// Initiate ModbusMaster object
ModbusMaster node;

void setup()
{
  
  // Pins 0 & 1 are used for the serial communication
  // Set pins 3 through 16 as outputs
  for (int thisPin = 2; thisPin < 16; thisPin++) {
    pinMode(thisPin, OUTPUT);
    // Make sure pins default off
    digitalWrite(thisPin, LOW);
  }

  pinMode(startPin, INPUT_PULLUP);
  pinMode(stopPin, INPUT_PULLUP);
  pinMode(ackAlarmPin, INPUT_PULLUP);

  Serial.begin(9600);
  node.begin(genId, Serial);
}


void loop() {
  unsigned long currentTime = millis();

  inputPoll ();

  if (currentTime - previousTime > eventInterval) {
    registerRead ();
    //testing ();
    previousTime = currentTime;
  }
}

void inputPoll () {

  // Input Pins
  int startPinValue = digitalRead(startPin);
  int stopPinValue = digitalRead(stopPin);
  int ackAlarmPinValue = digitalRead(ackAlarmPin);

  if (startPinValue == LOW) {
    startGen ();
  }

  if (stopPinValue == LOW) {
    stopGen ();
  }

  if (ackAlarmPinValue == LOW) {
    resetAlarms ();
  }

}

void startGen () {
  uint8_t startgen;
  node.clearTransmitBuffer();
  node.setTransmitBuffer(0, 0x00FF);
  node.setTransmitBuffer(1, 0x00FF);
  node.setTransmitBuffer(2, 0x00FF);
  startgen = node.writeMultipleRegisters(0x019c, 3);
}

void stopGen () {
  uint8_t stopgen;
  node.clearTransmitBuffer();
  node.setTransmitBuffer(0, 0x0000);
  node.setTransmitBuffer(1, 0x0000);
  node.setTransmitBuffer(2, 0x0000);
  stopgen = node.writeMultipleRegisters(0x019c, 3);
}

void resetAlarms () {
  uint8_t resetalarms;
  node.clearTransmitBuffer();
  node.setTransmitBuffer(0, 0x0001);
  resetalarms = node.writeMultipleRegisters(0x012e, 1);
}

void registerRead () {
  static uint8_t i, j, result;
  uint16_t data[3];

  // Read 4 registers starting at 0x0082
  result = node.readHoldingRegisters(0x0082, 4);

  // Put results in to array
  if (result == node.ku8MBSuccess)
  {
    for (j = 0; j < 2 ; j++)
    {
      data[j] = node.getResponseBuffer(j);
    }

    // Engine Running
    if ((data[0] & 0x2000) == 0x2000) {
      digitalWrite(2, HIGH);
    } else {
      digitalWrite(2, LOW);
    }

    // Key not in Auto - Note the not equal (!).  Anything other than auto will alarm.
    if ((data[0] & 0x0040) != 0x0040) {
      digitalWrite(3, HIGH);
    } else {
      digitalWrite(3, LOW);
    }

    // Overcrank Alarm
    if ((data[0] & 0x0010) == 0x0010) {
      digitalWrite(4, HIGH);
    } else {
      digitalWrite(4, LOW);
    }

    // Oil Temp High
    if ((data[0] & 0x0002) == 0x0002) {
      digitalWrite(5, HIGH);
    } else {
      digitalWrite(5, LOW);
    }

    // Oil Temp Low
    if ((data[0] & 0x0001) == 0x0001) {
      digitalWrite(6, HIGH);
    } else {
      digitalWrite(6, LOW);
    }

    // Coolant Temp High
    if ((data[1] & 0x1000) == 0x1000) {
      digitalWrite(7, HIGH);
    } else {
      digitalWrite(7, LOW);
    }

    // Coolant Temp Low
    if ((data[1] & 0x0800) == 0x0800) {
      digitalWrite(8, HIGH);
    } else {
      digitalWrite(8, LOW);
    }

    // Oil Pressure High
    if ((data[1] & 0x0080) == 0x0080) {
      digitalWrite(9, HIGH);
    } else {
      digitalWrite(9, LOW);
    }

    // Oil Pressure Low
    if ((data[1] & 0x0040) == 0x0040) {
      digitalWrite(10, HIGH);
    } else {
      digitalWrite(10, LOW);
    }

    // Coolant Level high
    if ((data[1] & 0x0004) == 0x0004) {
      digitalWrite(11, HIGH);
    } else {
      digitalWrite(11, LOW);
    }

    // Coolant Level Low
    if ((data[1] & 0x0002) == 0x0002) {
      digitalWrite(12, HIGH);
    } else {
      digitalWrite(12, LOW);
    }

    // Throttle Position High
    if ((data[2] & 0x0008) == 0x0008) {
      digitalWrite(13, HIGH);
    } else {
      digitalWrite(13, LOW);
    }

    // Throttle Position Low
    if ((data[2] & 0x0004) == 0x0004) {
      digitalWrite(14, HIGH);
    } else {
      digitalWrite(14, LOW);
    }

    // Battery Charge Voltage High
    if ((data[3] & 0x0010) == 0x0010) {
      digitalWrite(15, HIGH);
    } else {
      digitalWrite(15, LOW);
    }

    // Battery Charge Voltage Low
    if ((data[3] & 0x0002) == 0x0002) {
      digitalWrite(16, HIGH);
    } else {
      digitalWrite(16, LOW);
    }

    node.clearResponseBuffer();
  }
}

void testing () {
  static uint8_t i, j, result;
  uint16_t data[7];

  // Read 7 registers starting at 0x0082
  result = node.readHoldingRegisters(0x0082, 7);

  // Put results in to array
  if (result == node.ku8MBSuccess)
  {
    for (j = 0; j < 2 ; j++)
    {
      data[j] = node.getResponseBuffer(j);
    }

    // Genertor in Alarm
    if ((data[0] & 0x8000) != 0x8000) {
      digitalWrite(2, HIGH);
    } else {
      digitalWrite(2, LOW);
    }

    // Stopped in Alarm
    if ((data[0] & 0x0200) == 0x0200) {
      digitalWrite(3, HIGH);
    } else {
      digitalWrite(3, LOW);
    }

    // Oil Temp Fault
    if ((data[1] & 0x2000) == 0x2000) {
      digitalWrite(4, HIGH);
    } else {
      digitalWrite(4, LOW);
    }

    // Coolant Temp Fault
    if ((data[1] & 0x0100) == 0x0100) {
      digitalWrite(5, HIGH);
    } else {
      digitalWrite(5, LOW);
    }

    // Oil Pressure Fault
    if ((data[1] & 0x0008) == 0x0008) {
      digitalWrite(6, HIGH);
    } else {
      digitalWrite(6, LOW);
    }

    // Coolant Level Fault
    if ((data[2] & 0x4000) == 0x4000) {
      digitalWrite(7, HIGH);
    } else {
      digitalWrite(7, LOW);
    }

    // Throttle Position Fault
    if ((data[3] & 0x8000) == 0x8000) {
      digitalWrite(8, HIGH);
    } else {
      digitalWrite(8, LOW);
    }

    // Emergency Stop
    if ((data[6] & 0x0200) == 0x0200) {
      digitalWrite(9, HIGH);
    } else {
      digitalWrite(9, LOW);
    }

    node.clearResponseBuffer();
  }
}

`

**Comment by liltux** [comment]
@granttoth thanks!  I will take a look and see what I can do.

**Comment by liltux** [comment]
@granttoth is it ok that I can email about the arduino stuff?  If so you can reach me at liltux [at] liltux dot com.

**Comment by granttoth** [comment]
Yeah no problem. Heads up though I'm not great at this stuff, but I'll help however I can. granttoth [at] gmail.com is me.
