### ISSUE TITLE
Web Page Modification

### ISSUE THREAD

**Issue by pridesleap** [jgyates/genmon#407]
What files contain the Web Page configuration? I would like to modify the layout of some of the data points.

**Comment by jgyates** [comment]
The web interface is controller via these files:

     /static/index.html
     /static/genmon.js
     /static/genmon.css


genmon.js is where be bulk of the layout occurs. The text on the status, outage, maintanance, logs and monitor pages is controlled by the underlying genserv.py and genmon.py. The genmon.py sends JSON formatted data to genserv.py which then sends to to the javascript code in genmon.js. genmon.js then formats and displays the JSON data.
