### ISSUE TITLE
Generac 25Kw NG (QT02524GNSNA) H-100 connection help wanted

### ISSUE THREAD

**Issue by usmc124** [jgyates/genmon#411]
- Generator Model: QT02524GNSNA

**Comment by usmc124** [comment]
I have a couple 11kw generators running with genmon with no issues.  However, i would like to monitor my 25kw generator.  I am not finding a serial connector (molex) port like the others i have used.  There is a serial port in the front of the H-100 panel.  Do i connect to that?  Is there a setup procedure specifically for the H-100?  I am only finding Nexus and Evolution.  I have all the hardware ready to go.  Thanks- help is greatly appreciated as this product has been a major life saver for me.

**Comment by jgyates** [comment]
The H-100 is configurable so it is my understanding that you could use either the front or the back connector, depending on your settings of the controller. I believe most use the front. This page has info on the H-100 setup:

https://github.com/jgyates/genmon/wiki/Appendix-G-Generac-H-100--and-G-Panel-Controllers

**Comment by usmc124** [comment]
Awesome thanks. That was dumb on my part- i didnt hit the link that says "view 6 more" which is where Appendix G is located.  Ill give it a shot.
