### ISSUE TITLE
Can't get email to work

### ISSUE THREAD

**Issue by cmanion1983** [jgyates/genmon#412]
Using the outgoing mail settings, I'm unable to send test emails. I've used many different email address (as sender) all with the correct passwords and port settings. I haven't used gmail, only yahoo and aol. The error I most commonly get is 

An error occured: 
Error sending test email : Connection unexpectedly closed

Please try again.

Any ideas?

**Comment by jgyates** [comment]
This thread has some info on gmail security settings. 

https://github.com/jgyates/genmon/issues/351

Most email providers have the equivalent of this now (OAuth vs "less secure apps"). 

The short answer is that you have to change a setting on your account to allow external apps that do not use the OAuth protocol. These are considered "less secure apps" as they only use a username and password for authentication.

**Comment by cmanion1983** [comment]
It doesn't seem like they do that anymore, now you select an "app" and gmail, yahoo, etc generates a password for the account. You can select other. I have already done this and get the same result.

**Comment by jgyates** [comment]
You must have two factor authentication enabled. With gmail, if you have two factor authentication enabled then you can setup application specific passwords, however you can not have two factor authentication enabled and use less secure apps. what most people do is create a separate email account just for sending, then make sure two factor authentication is disabled and then you can enable "less secure apps"

**Comment by jgyates** [comment]
I just validated this on two gmail accounts. Two factor must be off before you get the option to enable less secure apps.

**Comment by cmanion1983** [comment]
I created another gmail account. Turned on the less secure apps option. Double and tripled checked my settings, now i get this 


  | An error occured: Error sending email: (535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8 https://support.google.com/mail/?p=BadCredentials p53sm2835565qtc.85 - gsmtp')Please try again.
-- | --

**Comment by jgyates** [comment]
these are the settings I use for gmail:

<img width="719" alt="Screen Shot 2020-07-05 at 5 25 22 PM" src="https://user-images.githubusercontent.com/4513286/86542546-8b78eb80-bee4-11ea-8302-a6961ab836df.png">


In addition I have two factor authentication disabled and "use less secure apps" enabled.

**Comment by cmanion1983** [comment]
Okay that fixed it!
