### ISSUE TITLE
Code review gensnmp.py

### ISSUE THREAD

**Issue by liltux** [jgyates/genmon#427]
@jgyates just a rough look through I noticed the following:
UpateSNMPData
Just curious, was this intentional or accedental.  It is the same spelling throughout.  As far as aesthetics go, adding the "d" to Up**d**ateSNMPData reads better to me.

**Comment by jgyates** [comment]
That is 100% accidental. Thanks for the review. More eyes are always better. I checked in a corrected version of this file.
