### ISSUE TITLE
Visual issue for MQTT plugin

### ISSUE THREAD

**Issue by bdwilson** [jgyates/genmon#428]
It appears the MQTT plugin complains about a root topic of "home". Then again, I couldn't get it not to complain with a longer one. 

Running v1.14.23. 

![image](https://user-images.githubusercontent.com/317946/90347617-92287180-dfff-11ea-9b55-386142cf4ce5.png)

**Comment by jgyates** [comment]
Good find! I checked in an update to fix this. I did not update the version number so just update from the About page. Let me know if you have any other issues.
