### ISSUE TITLE
MQTT Question generator/Status/Alarms/

### ISSUE THREAD

**Issue by liltux** [jgyates/genmon#434]
MQTT data missing or not getting formatted well.
This is on an H-100 controller.
Using MQTT to publish information to a subscribed service, I am trying to collect the actually current fault condition.  Looking through the code and MQTT data I have, I would suspect I should be able to get the information from generator/Status/Alarms/Alarm List.  But I get no data.
When I run MyClientInterface for generator:status_json, I see the Alarms/Alarm List/ and it has data.  The problem I think is the data is represented as a list and then runs through another round of place holders but no data.  Does this make sense?
![image](https://user-images.githubusercontent.com/17954856/92971451-17a81180-f446-11ea-8f2d-f5635a708a1f.png)
![image](https://user-images.githubusercontent.com/17954856/92971587-5d64da00-f446-11ea-9355-34aeb7319c95.png)

Just curious if there is a nice work around to check if it is a list of dictionaries, if not then the list is treated as a list of values?

**Comment by jgyates** [comment]
Can you send me registers for testing. My guess is that it is in the parsing in genmqtt.py

**Comment by jgyates** [comment]
I checked in V1.14.30 that should correct this issue. Let me know if you have any issues.

**Comment by jgyates** [comment]
I am closing this issue. Let me know if you have any problems with the fix I checked in.

**Comment by liltux** [comment]
That worked!  Thanks.
