### ISSUE TITLE
Different Sleeve source

### ISSUE THREAD

**Issue by LynnSchott** [jgyates/genmon#44]
I thought I would put in a few different items as an alternative for your sleeve.
#1 An inside sleeve to help reduce RFI interference 
https://www.amazon.com/gp/product/B06VYFGKKY/ref=crt_ewc_title_huc_11?ie=UTF8&psc=1&smid=A38Z015AJ7I755

#2 An outside sleeve to deter direct electrical shorts.
https://www.amazon.com/gp/product/B071WF5K2X/ref=crt_ewc_title_dp_1?ie=UTF8&psc=1&smid=A2N7NRZ9X3BHHN

**Comment by jgyates** [comment]
Thanks, I added these links to the readme and wiki.
