### ISSUE TITLE
Feature Request: view past power output in 1 hour chunks

### ISSUE THREAD

**Issue by skipfire** [jgyates/genmon#443]
It would be nice to be able to view a 1 hour section that isn't the last 60 minutes.  I had a power outages on September 1st, 15th, and 21st, but I don't have any way to go back and view them with anything other than the 30 day scale to see if I find consistencies or differences, but the 30 day scale is pretty useless if you want to look at any power usage detail as the datapoints are so close together.  I have attached the graph I can see, and it is useful to tell me the days that my generator ran with load and for self-test, but I can't see much for duration, how long it was running at given levels, etc.  If I could go back and zoom into September 1st, then zoom in further and view whatever hours those were it would be great.

<img width="567" alt="kWOutput" src="https://user-images.githubusercontent.com/10307327/94551597-36b2eb80-021b-11eb-94bc-35ab1af8178f.PNG">

**Comment by jgyates** [comment]
I am tracking the feature request list here: https://github.com/jgyates/genmon/blob/master/feature_requests.md

I will be closing this thread for now but the request is still on the master request list.
