### ISSUE TITLE
SOLVED - Unable to identify Molex connection in generator

### ISSUE THREAD

**Issue by DJT1423** [jgyates/genmon#446]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below.

***NOTE:*** If you are having issues with your serial connection, please read this page before posting:

https://github.com/jgyates/genmon/wiki/3.6---Serial-Troubleshooting

If you are having other issues, please see the following page:

https://github.com/jgyates/genmon/wiki/3.5---General-Troubleshooting

If you need to send you logs and registers to the developer, if you email is setup and working properly you can click send your logs on the About page in the web interface.

### Expected Behavior

I have configured the Pi and have my cable but I have been unable to identify a free 8 pin Molex connector in the generator that it is supposed to attached to. See photos. Can you point me in the right direction? Thoughts, suggestions?

### Actual Behavior

{Please write here}

### Steps to Reproduce (including precondition)

{Please write here}

### Screenshot or Pictures relating to the problem (if possible)

See photos

### Your Environment
![IMG_20200714_163002](https://user-images.githubusercontent.com/68388280/95092187-5bb0ce00-06f5-11eb-9008-89ecaae305b3.jpg)
![IMG_20200714_163009](https://user-images.githubusercontent.com/68388280/95092190-5ce1fb00-06f5-11eb-8339-1a018084177c.jpg)
![IMG_20200714_163013](https://user-images.githubusercontent.com/68388280/95092194-5e132800-06f5-11eb-9ab3-6d8b2b3d6fc9.jpg)
![IMG_20200714_163018](https://user-images.githubusercontent.com/68388280/95092196-5eabbe80-06f5-11eb-83b6-ffb52e9e9d59.jpg)
![IMG_20200714_163023](https://user-images.githubusercontent.com/68388280/95092202-5eabbe80-06f5-11eb-8d9f-91d456dfac7d.jpg)
![IMG_20200714_163030](https://user-images.githubusercontent.com/68388280/95092205-5f445500-06f5-11eb-9f80-2a7fd4f62438.jpg)

- Generator Model: G0070310, 11KW
- Generator Registers: Submit via the About page
- Genmon Version: {Please write here}

**Comment by JustApu** [comment]
Look behind the "Accessory Port" stickers.

**Comment by jgyates** [comment]
As @JustApu  mentioned it should be behind Accessory Port sticker. Port 1 if memory serves. These threads have some pictures:

See this thread:
https://github.com/jgyates/genmon/issues/85

or this one:
https://github.com/jgyates/genmon/issues/274

**Comment by jgyates** [comment]
FYI you can search the issues on keywords. Just remove the search phrase "is:open" from the search window and add something like "Accessory"

**Comment by DJT1423** [comment]
Awesome. Thanks for the quick help (and the search instruction!). David
