### ISSUE TITLE
New GenMon install not communicating with Controller

### ISSUE THREAD

**Issue by DJT1423** [jgyates/genmon#448]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below. This is a template so feel free to remove any of this text. Try to include the info below when applicable.

***NOTE:*** If you are having issues with your serial connection, please read this page before posting:

https://github.com/jgyates/genmon/wiki/3.6---Serial-Troubleshooting

If you are having other issues, please see the following page:

https://github.com/jgyates/genmon/wiki/3.5---General-Troubleshooting

You can search past issues by removing the "is:open" keywords from the search window and adding any keywords that are relevant to your issue.

If you need to send you logs and registers to the developer, if your email is setup and working properly you can click send your logs on the About page in the web interface.

### Expected Behavior

{Please write here}

### Actual Behavior

I have a new Pi/Genmon installation with version V1.15.01. Serial loop test passed. All looks good until I connect to the Generac Evolution Controller. Genmon still works of course, however I am getting no communication with the controller. I powered off the Controller as per issue #228, however nothing has changed. Logs and registers submitted. Thoughts, suggestions?

### Steps to Reproduce (including precondition)

{Please write here}

### Screenshot or Pictures relating to the problem (if possible)

{Please write here}

### Your Environment

- Generator Model: Generator Model: G0070310, 11KW
- Generator Registers: Sumitted
- Genmon Version: V1.15.01

**Comment by DJT1423** [comment]
PS, I am using the following for the connection:
-Uxcell a14041500ux1216 MAX232CSE Transfer Chip RS232 to TTL Converter Module COM Serial Board
-uxcell uxcellDB9 D-SUB 9 Pin Male Adapter RS232 to Terminal Connector Signal Module
-StarTech.com EPS 8 Pin Power Extension Cable - Power extension cable - 8 pin EPS12V (F) to 8 pin EPS12V (M) - 7.9 in - EPS8EXT

David

**Comment by jgyates** [comment]
If you performed a loopback on the far end of the cable and it passes then you likely have your tx and rx backwards in the cable. 

If this test passes but you still can not receive data with the Generator Monitor, then try swapping your transmit and receive connections in your cable (not the converter board). Note: the diagram for the cable in the repository has wiring for both a DTE and DCE serial connector. The wiring is different for a DTE vs a DCE connector. Another thing that could be wrong if you fail this test is a bad connection in your molex connector.

This link has this info and other info that would be helpful:

https://github.com/jgyates/genmon/wiki/3.6---Serial-Troubleshooting

**Comment by jgyates** [comment]
I received your logs. The only thing that looks odd is you have this error:

     Error on open serial port /dev/ttyAMAO: [Errno 2] could not open port /dev/ttyAMAO: [Errno 2] No such file or directory: '/dev/ttyAMAO'

in the file /var/log/myserial.log 

You must make sure that genmon is not loaded when you run the loopback test. Also are you running the same device on the loopback test as genmon is setup for. Genmon is using /dev/ttyAMA0 according to your logs.

**Comment by DJT1423** [comment]
I reversed the rx and tx connections to the Molex connector and it works like a charm.

Thanks very much. Looking forward to learning more about the operation of my generator.

David
________________________________
