### ISSUE TITLE
Unable to Upgrade 

### ISSUE THREAD

**Issue by swvalenti194** [jgyates/genmon#449]
Currently on 1.15.01, hit upgrade button and downloading and restarting completes however still shows 1.15.01. Restarted pi with negative results. 

![Screenshot_20201008-070237](https://user-images.githubusercontent.com/43345060/95450971-1ed31a00-0935-11eb-85d6-9b211b0efd69.png)
![Screenshot_20201008-070318](https://user-images.githubusercontent.com/43345060/95450983-21ce0a80-0935-11eb-9ce2-ee6e9b01d044.png)

**Comment by jgyates** [comment]
I forgot to update the string that contains the version number. I checked in an update to this file. It should work now.
