### ISSUE TITLE
Service Journal

### ISSUE THREAD

**Issue by jjmacneil** [jgyates/genmon#453]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below. This is a template so feel free to remove any of this text. Try to include the info below when applicable.

***NOTE:*** If you are having issues with your serial connection, please read this page before posting:

https://github.com/jgyates/genmon/wiki/3.6---Serial-Troubleshooting

If you are having other issues, please see the following page:

https://github.com/jgyates/genmon/wiki/3.5---General-Troubleshooting

You can search past issues by removing the "is:open" keywords from the search window and adding any keywords that are relevant to your issue.

If you need to send you logs and registers to the developer, if your email is setup and working properly you can click send your logs on the About page in the web interface.

### Expected Behavior

The Service Journal tab should display Journal Entries: at the top of the page

### Actual Behavior

The title at the top of the Service Journal page says Journal Entires:

### Steps to Reproduce (including precondition)

N/A

### Screenshot or Pictures relating to the problem (if possible)

![GenMonServiceJournal](https://user-images.githubusercontent.com/65689224/95703199-8ed6ee00-0c1c-11eb-9dde-ba7f8aa11e4e.JPG)

### Your Environment

- Generator Model: {Please write here}
- Generator Registers: Submit via the About page
- Genmon Version: {Please write here}

**Comment by jgyates** [comment]
Thanks, I corrected this. I did not update the version so just refreshing to V1.15.03 should correct this typo.
