### ISSUE TITLE
Setting monitor time

### ISSUE THREAD

**Issue by nekitti** [jgyates/genmon#478]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below. This is a template so feel free to remove any of this text. Try to include the info below when applicable.

***NOTE:*** If you are having issues with your serial connection, please read this page before posting:

https://github.com/jgyates/genmon/wiki/3.6---Serial-Troubleshooting

If you are having other issues, please see the following page:

https://github.com/jgyates/genmon/wiki/3.5---General-Troubleshooting

You can search past issues by removing the "is:open" keywords from the search window and adding any keywords that are relevant to your issue.

If you need to send you logs and registers to the developer, if your email is setup and working properly you can click send your logs on the About page in the web interface.

### Expected Behavior

Setting Monitor time

### Actual Behavior

Can’t set monitor time

### Steps to Reproduce (including precondition)

Okay. Probably a stupid question. Searched and can’t seem to find the answer. So the time on my Rasberry Pi seems to be set to GMT. 6hrs ahead of me. I see where I can set Gen time to monitor time, but can’t find a way to set the monitor/Pi time in the web interface. Is this possible, or do I need to pull the Pi and hook up to a monitor and keyboard to set the time. It woke me up exercising last night because it thought it was 6 hours later. Thanks for the help.
Rob

### Screenshot or Pictures relating to the problem (if possible)

{Please write here}

### Your Environment

- Generator Model: Evo 1 11kw
- Genmon Logs: Submit via the About page
- Genmon Version: 1.15.11

**Comment by swvalenti194** [comment]
SSH into the RPi and type `sudo raspi-config` and enter the localisation options then change time zone in there.
