### ISSUE TITLE
Maintenance Page Service Due Dates

### ISSUE THREAD

**Issue by quagmirert** [jgyates/genmon#489]
Great project as my parents have a Generac and the Proprietary Controller was dying so we replaced it with this awesome solution.

I am curious if there is a way to update the service due dates on the Maintenance Page. It appears that currently via the controller it just jumps the date and there doesn't appear to be a way to role it back.

I am not that familiar with Modbus but I am a Computer Engineer so I'm happy to test things out and provide feedback.

### Your Environment

- Raspberry Pi 3B+
- Generator Model: G0058851
- Genmon Version: V1.15.14

**Comment by jgyates** [comment]
The service dates are read from the controller. The only way that I now of to modify them is to reset the maintenance timer from the generator controller. Doing this will begin the counter from today (i.e. 1 year / 100 hours or 2 years / 200 hours from the reset date). You can reset the maintenance via the SubMenus - > Dealer  -> Edit menu - > Reset Maintenance 

To access Dealer Menu on the Evolution controller, from the top menu selection (SYSTEM, DATE/TIME,BATTERY, SUB-MENUS) enter UP UP ESC DOWN UP ESC UP, then go to the dealer menu and press enter.

I am closing this issue but if you have other questions on this topic feel free to post them to this thread.
