### ISSUE TITLE
MQTT Publish for Generator Start/Stop Control

### ISSUE THREAD

**Issue by mllockwood** [jgyates/genmon#493]
Is there an MQTT publish topic that can be used to send a start/stop engine run command to the generator?   I see the web based start/stop functions, but do not see anything (unless I have completely overlooked it) related to this using MQTT.  Thanks!

**Comment by jgyates** [comment]
This section has info on publishing commands:

     https://github.com/jgyates/genmon/wiki/1----Software-Overview#genmqttpy-optional

Any command that you can send to genmon you should be able to send via MQTT publish.

**Comment by mllockwood** [comment]
My apologies, I did completely overlook that in the documentation.  Thank you!

**Comment by jgyates** [comment]
No worries.
