### ISSUE TITLE
Login Username appears to be case sensitive

### ISSUE THREAD

**Issue by vonstorch** [jgyates/genmon#496]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below. This is a template so feel free to remove any of this text. Try to include the info below when applicable.

***NOTE:*** If you are having issues with your serial connection, please read this page before posting:

https://github.com/jgyates/genmon/wiki/3.6---Serial-Troubleshooting

If you are having other issues, please see the following page:

https://github.com/jgyates/genmon/wiki/3.5---General-Troubleshooting

You can search past issues by removing the "is:open" keywords from the search window and adding any keywords that are relevant to your issue.

If you need to send you logs and registers to the developer, if your email is setup and working properly you can click send your logs on the About page in the web interface.

### Expected Behavior

Login to the genmon webpage with insensitive case username

### Actual Behavior

Login to the genmon webpage requires you to use the case sensitive input

### Steps to Reproduce (including precondition)

Try logging into webpage with a mix of upper and lower case

### Screenshot or Pictures relating to the problem (if possible)

{Please write here}

### Your Environment

- Generator Model: Generac 22KW
- Genmon Logs: Submit via the About page
- Genmon Version: Version V1.15.16

Not sure if this is by design and that needs identified in the documentation or change code to allow any case for Username.

**Comment by jgyates** [comment]
I checked in an update that remedies this. I did not update the version as this was a small change so just update from the About page and you should be set. Let me know if you have any issues.
