### ISSUE TITLE
Wiki Setup Instructions

### ISSUE THREAD

**Issue by USAFPride** [jgyates/genmon#50]
Raspbian lite was also missing `configparser`.  You may want to add the line below to the wiki for the setup

`sudo pip install configparser`

**Comment by USAFPride** [comment]
Additionally, `clientInterface` is missing the capital i in two spots
` python Clientinterface.py localhost` should be ` python ClientInterface.py localhost`
`python Clientinterface.py <ip address of the raspberry pi> ` => `python ClientInterface.py <ip address of the raspberry pi> `

**Comment by jgyates** [comment]
@USAFPride, 
Thanks for catching this. I have fixed both issues in the wiki.
-Jason
