### ISSUE TITLE
Can't connect after recent software upgrade

### ISSUE THREAD

**Issue by Newtonite** [jgyates/genmon#512]
After upgrading to the latest version, I'm getting a "ERR_CONNECTION_REFUSED" error when I try to connect from my Chrome browser. I think the upgrade went successfully at least, because I received an email saying that the generator was restarting.

Where do I go from here?

**Comment by liltux** [comment]
Reboot your pi.  Can you ssh or vnc to your pi?  If so you can reboot.

**Comment by jgyates** [comment]
This thread has more details on the solution.

**Comment by jgyates** [comment]
https://github.com/jgyates/genmon/issues/504

**Comment by jgyates** [comment]
In the thread mention above I reference a fix I just checked in. Let me know if the next upgrade corrects this issue.

**Comment by Newtonite** [comment]
Yes, that worked. I'll report back what happens with the next upgrade. Thanks!
