### ISSUE TITLE
Discrepency In Software Version Information

### ISSUE THREAD

**Issue by pridesleap** [jgyates/genmon#515]
I recieved a notification the other day that there was a newer version of Genmon available (v16.2). I updated via the "About" page as I previously have. When I go to the about page now I am being told that there is yet another new version available (v16.0). Is this a mistake or is this a rollback? Just asking as I am wondering what I should do.

**Comment by jgyates** [comment]
That was a mistake. The software uses a file with the version number in it to keep track of what the current version and it reads the same file form github to know if an upgrade is available. The old version was 1.15.20, the new is 1.16.0. The reference to the version in the software was updated to 1.16.20 by mistake for one day, then I changed it to 1.16.0.
