### ISSUE TITLE
Saving on Generac Parts

### ISSUE THREAD

**Issue by jeepjungle** [jgyates/genmon#52]
Figured I might share this here even though it's not specific to genmon but figure the DIY'ers might find it useful.

My water cooled QT36 with Nexus controller was getting overspeed and governor faults in the error log.  The maintenance company I was using quoted me almost $1000 to replace the "governor actuator".  So I did some research.

Seems Generac often uses COTS (common off the shelf) component parts and what they call a "governor actuator" and sell for over $400 is known in the automotive world as an "electronic throttle body" and sells for less than $100.  I bought the replacement from Summit Racing and swapped it out myself. It's only held on with 4 bolts.

Generac Governor/Actuator 0E4394 $350-$415 (depending where you buy it)
40mm Bosch Electronic Throttle Body  Part# BCH-0280750149  $83.97 from:  https://www.summitracing.com/

**Comment by jgyates** [comment]
That is great info Thanks!
