### ISSUE TITLE
What determines Fuel Level Low event?

### ISSUE THREAD

**Issue by liltux** [jgyates/genmon#527]
@jgyates what triggers a Fuel Level Low Event?  We had some network issues last week and this week I found our RPi was locked up.  I restarted the RPi and everything was as it should be and functional.  Shortly there after there was an alert/message sent out about low fuel level.  It is at 79%.  Is this hard coded somewhere?  I think this may be a value to be set per installation.  Your thoughts?

**Comment by jgyates** [comment]
The fuel level low event is triggered by a fuel level reading of 20%  or less and another notice at 10% or less. Was the message and email or some other short message? Logs may provide more info on what is happening and why you got an incorrect notice.

The software currently determinants the fuel level by one of three ways depending on the installation.

1) Fuel sensor built in to controller (industrial or Evo Diesel)
2) External fuel sensor add on (tank utility or DIY tanks sensor)
3) Calculated fuel consumption (Evolution or Industrial)

I would look on the Monitor page an see if there are communication errors. In some situation communication errors can cause invalid register readings which could make case number 1 above read bad info.

**Comment by jgyates** [comment]
also, if the notice is recieved from a message other than email then the state can be checked on the Maintenance page:

Maintenance - > Fuel Level State :  (OK or Low)

If this value is Low then a message is sent out via short message (non email)

**Comment by liltux** [comment]
Ok,  I was thinking the same thing.  On the Industrial units, they should annunciate on their own for Fuel level warnings configured in the controller.  You could disable this alert for Industrial units, just a suggestion.  I did send my logs to you, maybe you will see something?  I did not see anything other than the event from the previous week.  Curious, could the mail message been stuck in limbo in SMTP and once rebooted and good network connection the message was able to send?  I have seen if there is a network problem, once corrected, you can get a flood of messages that were not delivered during the networking issue.

**Comment by liltux** [comment]
And I got another message.  Hmmm.  It appears to be triggering 11 min. after a software reboot.  Almost to the T with the time stamp.  But no other issues I can see in the logs, or on the Generator.

**Comment by jgyates** [comment]
What is the exact message state?

**Comment by liltux** [comment]
![FuelLowMess_2](https://user-images.githubusercontent.com/17954856/113882530-fbbde180-9782-11eb-93d4-cbfb8124d3fd.png)
![FuelLowMess_1](https://user-images.githubusercontent.com/17954856/113882540-fd87a500-9782-11eb-940b-f0b47bd13f67.png)

**Comment by liltux** [comment]
See above, approximately 11 min after restart of software I recieve a Fuel Level is Low.  I am only setup for Texts.

**Comment by jgyates** [comment]
This is a bug. I can duplicate. I get a SMS low fuel but no email. I will let you know once I have a fix.

**Comment by liltux** [comment]
Ok, thanks.  I wasn't sure.  Thank you sir!

**Comment by jgyates** [comment]
I checked in V1.16.05. This should fix the problem. Let me know if you have any issues.
