### ISSUE TITLE
Feature request - Configurable shut-down delay

### ISSUE THREAD

**Issue by skipfire** [jgyates/genmon#528]
Is there a configuration somewhere in GenMon to set the shut-down delay when utility power is restored?  I'd like to be able to set the generator to go for 5 minutes after an outage before switching back as every long outage we have tends to see power come back for about 2 minutes, then go out for another 15 to 30 minutes.  The problem is that the generator always throws a crank alarm if it tries to be restarted that soon and I have to go manually deal with it (in the dark at 4:15 AM this morning).

**Comment by jgyates** [comment]
I am not aware of any parameter like this. There is a controller setting for how long to wait *before* starting the generator after an outage is detected, but I am not aware of one for a delay for shutting down the degerator after the utility is restored. To do this in software would require that the software take over the function of the controller, which is not really part of the scope of this project and probably not a safe thing for the generator.
