### ISSUE TITLE
Can't stop generator from GENMON --> Maintenance tab --> Remote Commands --> Stop Generator.

### ISSUE THREAD

**Issue by speters0** [jgyates/genmon#538]
Can't stop generator from GENMON --> Manintenance tab --> Remote Commands --> Stop Generator.

GENMON Version V1.16.08

I have a Guardian 16KW home backup Generac Generator model: G0071760
with an automatic Generac transfer switch.

After starting the generator. the buttons from the 
Maintenance Tab [Stop Generator], [Start Generator] and [Start Generator and Transfer] in GENMON Web App
stayed the same. (same color [green] [grey] [grey]) and (same state [disable] [enable] [enable]).

I looked at the Console Log in Chromium App on my Raspberry Pi and there was a periodic exception
stating: Cannot read property 'length' of undefined in  GetBaseStatus function in genmon.js

After investigating, I found that there was no 'Weather' field in 'result' variable.

the code line that throw the exception was:

if (result['Weather'].length > 5) {

I modified the line with:

if (result['Weather'] != undefined && result['Weather'].length > 5) {

Now every thing works fine.

Can you adapt the code so it can tolerate that there is no 'Weather' field in 'result' variable (from the last ajax request)

Thank you!

**Comment by jgyates** [comment]
@speters0 

Thanks for finding this. I just checked in V1.16.09 which includes this update.
