### ISSUE TITLE
Modification to allow a two propane tank gauges with [gentankdiy]

### ISSUE THREAD

**Issue by speters0** [jgyates/genmon#548]
Hi,

I'm living in the northern Laurentians Quebec, Canada where temperature can get as low as -40°C
I have a 16KW Generac generator and a 5 burner Cooktop. They all run on propane gas.
I have two 420lb propane tanks. And the reason why I have two tanks is:
If It gets too cold the propane gas might freeze if I have only one tank.
If the demand on pressurized gas is high, the pressure drop at the outlet of the tank regulator will lower the temperature substantially at that point.
It is the thermodynamic law.
By having two tanks, the pressure drop at each outlet is less and it minimize the chance of gas freeze.
Lot of peoples on northern locations uses at least a two tank setup.

I'm using DIY thank Method 1 and adding two Propane Fuel Gauge (on on each tank).
The liquid propane level on each tank can lower at a different rate depending on brass fitting diameter and the length of the gas line.

So I decided to modify Genmon Program to accommodate for a two Gauge setup.

The is a new option in the setup file: gentankdiy.conf

# number of tanks (1 or 2)
nb_tanks = 1

If the value is 2

There is a new External Tank Gauge that will display on the [Status] page of Genmon.
In the [Maintenance] page, the fields (Fuel Level Sensor) and (Fuel in tank (sensor)) are calculated with the mean value of both gauges.

The modification has been made on Version V1.16.09

It is only applied on Evolution Controller

Here is the list of the modified files:

/home/pi/genmon/conf/gentankdiy.conf
/home/pi/genmon/genmonlib/gaugediy.py
/home/pi/genmon/gentankdiy.py
/home/pi/genmon/genmonlib/controller.py
/home/pi/genmon/genmonlib/generac_evolution.py
[Genmon.zip](https://github.com/jgyates/genmon/files/6679090/Genmon.zip)

If you wish it could be interesting to have a look at the code, adjust it if needed, and merge it to the latest version.⍺

I will upload these files on github site.

Thank you!

**Comment by jgyates** [comment]
Sounds like a useful addition. Let me review the code and look at integrating this feature.

**Comment by jgyates** [comment]
I integrated most of your changes, however I had to make some tweaks so there is not impact to people not using two tanks. In short you just need to add 

     nb_tanks = 2 

to /etc/genmon/gentankdiy.conf and restart genmon. A refresh of the browser would need to be done if the browser is open while genmon restarted.

Two gauges are shown on the main page if this is enabled. Note: this only applies to type 1 DIY gauges. Type 2 DIY gauge only supports one instance at the moment.

Let me know if you have any issues.

**Comment by jgyates** [comment]
That is do-able. I will try to do that soon. I will update this thread when complete. Let me know once you have a chance to test this as I do not have three tanks to test with :)

**Comment by jgyates** [comment]
@davisgoodman, just to clarify, are you OK with creating your own gauges with the method in this wiki entry:


https://github.com/jgyates/genmon/wiki/Appendix-L-Adding-a-Propane-Fuel-Gauge-to-Genmon#diy-tank-method-1

See DIY tanks gauge method one. This is the only type of gauge that currently supports multiple instances.

**Comment by davisgoodman** [comment]
Yes, does either of these two are supported or only the one with the R3D Rochester sensors. Either or I'm ok to create them

**Comment by jgyates** [comment]
OK. The DIY Tank Method 1 is the only one that supports multiple tanks.

**Comment by davisgoodman** [comment]
Ok. As soon as I can put my hand on those sensors, I’ll update the thread.

**Comment by jgyates** [comment]
@davisgoodman 

I have added support for up to 4 tanks (the max supported by the design of the circuit). These updates are checked in but I have not increased the version number yet. Let me know once you have an opportunity to test.

**Comment by davisgoodman** [comment]
Wow..  Thanks. As soon as I can put my hands on those sensors I sure will.

I'll reach out to speter0 to find out where he got his.
________________________________

**Comment by speters0** [comment]
Hi,

I bought the gauges at:
https://www.petroviron.ca/

**Comment by davisgoodman** [comment]
Thanks, that’s actually one of the distributors they gave me.

 

I’ll phone them up.

**Comment by davisgoodman** [comment]
@speters0Thanks for the lead, I have 4 sensors on their way.On 11 avr. 2022, at 17 h 53, speters0 ***@***.***> wrote:Hi,I bought the gauges at: https://www.petroviron.ca/—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by davisgoodman** [comment]
Still wating to get my sensors but updated genmon on my RaspPI.

 

Maybe just something that was missed but the gentankdiy.conf still shows:

# Optionally support two tanks of gauge type 1, the default is 1.

# Only valid data is 1 or 2

nb_tanks = 1

 

I guess only the comment needs to reflect the update

**Comment by jgyates** [comment]
The file /etc/genmon/gentankdiy.conf does not get updated however the file in /home/pi/genmon/conf/gentankdiy.conf does get updated. If the files in /etc/genmon were updated every update it would wipe out your site specific settings.

**Comment by davisgoodman** [comment]
Indeed, didn't realize it.
________________________________

**Comment by speters0** [comment]
Tank gauges still working great with the last mod!

**Comment by davisgoodman** [comment]
Glad to hear! 

 

Can’t wait to get my 3 tanks hooked up.

**Comment by davisgoodman** [comment]
Well  got my gauges today and all installed.
![image](https://user-images.githubusercontent.com/37666918/163889518-e73d1813-8d94-4165-af53-f5a99e84515b.png)

Few questions, 
when 3 gauges are installed is the "20%" averaged across all 3 gauges?
Do they need to be calibrated?
Is there a config for setting the threshold (20%)?
Is there a way to send out only "Low Fuel" emails as I  may want to send the emails directly to my Propane provider but wouldn't want have any other kind of notifications from Genmon?

**Comment by davisgoodman** [comment]
Also would there be a way to export the tank readings through MQTT, would allow to integrate them with Home Assistant

**Comment by jgyates** [comment]
Genmon will send email notices at 10% and 20% fuel levels.  Short message notices for add ons (SMS, etc) are sent at 20%. When multiple tanks are configured this is the average of the total tanks.

I will leave the calibration question to others as I do not know the answer. For type 1 gauges, i assume no but I do not know for sure.

There is not a configuration setting for fuel level percentage notices.

Low Fuel messages are sent in the "warn" category on the Notifications page. and in "Warning" category for short messages for Add ons. Other types of messages are also in the warning category.

I can look into the MQTT export.

**Comment by davisgoodman** [comment]
Thanks for the response. I suppose there are other kind of warning that would go out in this category which I wouldn't want to send them. For now I'll notify them when I get it.

**Comment by jgyates** [comment]
I checked in a mod to show readings of each tank on the maintenance page and they will also be exported via MQTT.

**Comment by davisgoodman** [comment]
Upgraded to the latest. On the maintenance page I only get the average as well as in MQTT
![image](https://user-images.githubusercontent.com/37666918/163896342-ce268f98-1ea8-4f50-b13b-99bbeb8f650f.png)
![image](https://user-images.githubusercontent.com/37666918/163896422-b4491c98-ca94-4163-b146-29a6a6ee7091.png)

**Comment by jgyates** [comment]
any errors in /var/log/genmon.log?

**Comment by davisgoodman** [comment]
> any errors in /var/log/genmon.log?

Nothing particular:
2022-04-18 18:33:11,945 : GenMon Loaded for site: 105 Des Gardénias, Val-David using python 3.9
2022-04-18 19:46:47,400 : Generator Monitor Shutdown
2022-04-18 19:46:50,903 : Selected Controller: generac_evo_nexus
2022-04-18 19:46:52,093 : GenMon Loaded for site: 105 Des Gardénias, Val-David using python 3.9
2022-04-18 20:10:20,725 : Generator Monitor Shutdown
2022-04-18 20:10:23,570 : Selected Controller: generac_evo_nexus
2022-04-18 20:10:24,767 : GenMon Loaded for site: 105 Des Gardénias, Val-David using python 3.9

**Comment by jgyates** [comment]
send your logs from the about page. This requires outbound email to be working. If you don't have outbound email let me know and we can to this a different way.

**Comment by davisgoodman** [comment]
Done!

**Comment by jgyates** [comment]
try this: 


edit the file /etc/genmon/gentankdiy.conf

add the line

debug = True 

to the end of the file, save the file, restart genmon, wait 20 seconds, then send me the logs again

I don't have the hardware on the i2c but if you enable "debug" in the gentankdiy.conf file it will ignore fatal errors and output more info to the log. The gauges data is displaying for me with debug enabled.

**Comment by jgyates** [comment]
Try updating the repository again. I think I forgot to push the update. Hopefully that corrects the issue. Let me know

**Comment by jgyates** [comment]
also, if this works take out the debug=True from the /etc/genmon/gentankdiy.conf file as that extra log info can put unneeded wear on your SD card.

**Comment by davisgoodman** [comment]
:-( 
![image](https://user-images.githubusercontent.com/37666918/163902025-7c264b8f-ed5c-42bd-8a48-7a1b28376ac6.png)

Still....

**Comment by davisgoodman** [comment]
Just submitted the logs .....

**Comment by jgyates** [comment]
update to the latest, then send logs

**Comment by davisgoodman** [comment]
Upgraded and sent logs. Still only seeing the average

**Comment by jgyates** [comment]
it looks like github is not updating the repository at your location or for some other reason you are not getting the update. I put some additional log output in the latest update but your logs do not show this info.

For example link 92 of ./genmon/gentankdiy.py should be 

     self.LogDebug("Num Tanks: " + str(self.nb_tanks))

and I am showing this in the repository but I would guess that your pi does not have this update. 

https://github.com/jgyates/genmon/blob/f1a01f7af3433bf7cbda5c39d4ac71042a01d4e2/gentankdiy.py#L92

**Comment by davisgoodman** [comment]
Do test I create a separate directory and when trying to clone the repo I'm getting this:
pi@generac:~/gitdownload $ git clone https://github.com/jgyates/genmon.git
Cloning into 'genmon'...
error: git-remote-https died of signal 4

**Comment by davisgoodman** [comment]
Ok so the issue is definitely the update. 

For testing I copy/pasted gaugediy.py from the repo into a new file and diff and the one on my side missed 12 lines of codes

**Comment by jgyates** [comment]
you can also manually update with this command from the genmon folder.

   ./genmonmain.sh -u

This ends up calling these commands:

      git fetch origin
      git reset --hard origin/master

If you have some sort of connectivity issue with github this would cause the problem we are seeing.

**Comment by jgyates** [comment]
when you select update form the web interface it ends up calling genmonmain.sh

**Comment by davisgoodman** [comment]
So you're right, some issues with GitHub.

pi@generac:~/genmon $ ./genmonmaint.sh -u
This script will update genmon to the latest version from the github repository. This script requires internet access. If you have modified any files in the genmon directory, they will be overwritten. Configuration files in the configuration directory will not be overritten.  Continue? (y/n)  y
Updating genmon...
error: git-remote-https died of signal 4
HEAD is now at 02f447e V1.18.10
Done.

**Comment by davisgoodman** [comment]
Just let me know which files been mofidied, I'll pickup only those ones and replace them

**Comment by davisgoodman** [comment]
I believe gaugesdiy.py, controller.py, tooltips.txt, gettankdiy.py

**Comment by jgyates** [comment]
/genmon/gentankdiy.py
/genmon/genmonlib/controller.py
/genmon/genmonlib/gaugediy.py

**Comment by jgyates** [comment]
toottips.txt also, but that one is not critical, just some text for the UI help bubbles related to multiple tanks.

**Comment by davisgoodman** [comment]
Well I now see all three gauges in the Maintenance, though MQTT has lost the Maintenance export
![image](https://user-images.githubusercontent.com/37666918/163908802-7fb68001-a4ec-4b01-af73-ee3db135db0b.png)
![image](https://user-images.githubusercontent.com/37666918/163908876-1c49980f-d07c-47c6-9b24-e510896b41c8.png)

**Comment by jgyates** [comment]
send logs

**Comment by davisgoodman** [comment]
And something doesn't jive in the numbers. Fuel Level Sensors seems to be the average which makes sense but then we should have 3 more readings 1 for each tank. Or have only 3 readings 1 per tank.

Just submitted the logs

**Comment by jgyates** [comment]
Are these logs that have run **after** you requested data from MQTT? That would be more helpful

**Comment by davisgoodman** [comment]
Yes

**Comment by davisgoodman** [comment]
Just as an FYI, I  went elsewhere in github and was able to clone a few other repos without issues. I tried your other top repo githup.io and had the same issue/error

**Comment by jgyates** [comment]
I checked in an update to genserv.py and controller.py try that. If you have the setting "JSON for Numerics" enabled it would caused an issue.

Regarding the repo access issue. I don't have any control on my end about access to the repository. I would not know where to begin troubleshooting that issue. Can you duplicate this on another computer? or is it specific to your pi?

This url is what the web interface uses:

     http://192.168.1.10:8000/cmd/maint_json

the mqtt plug in uses the above or this command, depending on the "JSON for Numerics" setting:
 
     http://192.168.1.10:8000/cmd/maint_num_json

**Comment by davisgoodman** [comment]
Ok so the issue seems to be only on the Pi. I'll look into this later. As for the update, everything is good now. Both the maintenance page and MQTT shows the 3 tanks reading.

Thanks for all the effort

**Comment by davisgoodman** [comment]
If I can make a small comment and that is only a matter of clarity I would probably have the label "Fuel Sensor" changed to Fuel Sensor Tank 1" to be consistent with the other 2 labels.

**Comment by jgyates** [comment]
Thanks for the feedback. I choose the first tank to be labeled "Fuel Sensor" and not "Fuel Sensor Tank 1" because the vast majority of uses only have one tank and I did not want to confuse users. Also, adding the additional logic to make this display differently for multi tank installations vs single tank installations would introduce maintenance complexity and make the first tank display differently via MQTT topics. I did consider this but I opted to implement it this way.

**Comment by davisgoodman** [comment]
Totally understand. But now I guess with multi-tanks we don't have an average reading anymore. I guess that is the consequences of having all 3 readings now.

Again thanks a lot for implementing this in no time.

**Comment by davisgoodman** [comment]
Hi Jason, just found out that the vendor had sent me the datasheet of the Rochester gauges sensors. I was just wondering if the calculation  done for the percentages are based on these.
![image](https://user-images.githubusercontent.com/37666918/164279449-2c3fe16a-62a9-4c36-b3c9-150e19cda96d.png)

**Comment by jgyates** [comment]
Hi @davisgoodman 

I don't know. I did not create the DIY method 1, @zekyl314 created this. Hopefully he can weigh in.

**Comment by zekyl314** [comment]
Hi @davisgoodman, as far as I recall, the sensor does read up to 5V at 100% full.  I pulled some of the code and details from another generic project for reading the hall effect sensors.  The genmon configuration file shows the step of 20% per volt, which would match up to their documentation and my knowledge. 

I have confirmed a matching reading on my physical gauge vs the digital gauge reading in genmon.  The digital is more precise than the physical and both change a little based on temperature.  

I hope this helps.

**Comment by davisgoodman** [comment]
That's perfect, thanks for confirming. I figured it had been done and verified before.
________________________________

**Comment by zekyl314** [comment]
You're welcome @davisgoodman!  Love hearing people using this addon.  :)

**Comment by davisgoodman** [comment]
@zekyl314  Just got my first refuel of my 3 tanks. They put in 901 liters out of a capacityof 1089. We are currently in a major power outage and my generator been running for 5 days straight.

That being said, after the refuel, all 3 gauges read 82% and even after having ran for now couple of hours the reading haven't moved at all. I took an analog reading directly out of the sensors and they were all different. One being at 5.001 volts and the others at 4.804 and can't remember exactly the third one. 
This is what I have now and not moving at all. Any idea what could be the issue. Could it be a calibration issue?

![image](https://user-images.githubusercontent.com/37666918/170576372-27208ff9-cf4d-4433-981b-6e208f342a4f.png)

**Comment by zekyl314** [comment]
> 

Wow, sorry you're in such a major outage.  If you're reading 5.00 volts, that would equal 100%, not 82%.  But as you say too it has been running for hours and should be lower, what does it look like on the physical gauge vs reading in the web GUI?  Have you tried powering off the Pi and reconnecting the inputs for each tank?  I wonder if somehow they got jostled during the refueling?  Also checking the gauge connection end too?

**Comment by davisgoodman** [comment]
Well the gauges are all maxed out physically. Over the 80% range. But as mentioned, reading the voltage directly from the sensors, All three are different and one of them being at 5 makes sense as Tank 1 is always the one that comes down faster than the others then the second and lastly the 3rd one. 
![image](https://user-images.githubusercontent.com/37666918/170581848-384d2233-cc66-4ebf-b1f6-72da78c3cd34.png)
Also if I read each register of the I2C channel they all have different values.
It's a bit mesmerizing...

**Comment by davisgoodman** [comment]
As an update...
Since the time I posted Fuel consumption shows 15.26L but none of the gauges have moved
![image](https://user-images.githubusercontent.com/37666918/170605112-86cd66f3-2fec-432c-a784-9e80838454f1.png)

**Comment by jgyates** [comment]
Fuel consumption is based on the power log, not the fuel gauge.

When you enabled the debug option on the advanced page it sent me your logs, I am attaching your gentankdiy.log as it has some interesting data.

[gentankdiy.log](https://github.com/jgyates/genmon/files/8783042/gentankdiy.log)


Notice in this file how your readings start out different,

2022-05-26 13:58:18,434 : [3, 246]
2022-05-26 13:58:18,435 : Reading Gauge Data: 2.60%
2022-05-26 13:58:19,438 : [17, 14]
2022-05-26 13:58:19,439 : Reading Gauge Data: 11.00%
2022-05-26 13:58:20,441 : [17, 55]
2022-05-26 13:58:20,442 : Reading Gauge Data: 11.00%
2022-05-26 13:58:20,454 : {"Tank Name": "External Tank", "Capacity": 0, "Percentage": 2.6, "Percentage2": 11.0, "Percentage3": 11.0}

Then change to the same value:

2022-05-26 14:21:19,612 : [127, 255]
2022-05-26 14:21:19,613 : Reading Gauge Data: 82.00%
2022-05-26 14:21:20,616 : [127, 255]
2022-05-26 14:21:20,616 : Reading Gauge Data: 82.00%
2022-05-26 14:21:21,619 : [127, 255]
2022-05-26 14:21:21,620 : Reading Gauge Data: 82.00%
2022-05-26 14:21:21,635 : {"Tank Name": "External Tank", "Capacity": 0, "Percentage": 82.0, "Percentage2": 82.0, "Percentage3": 82.0}


You are getting the additional debug info since you have debug=true in /etc/genmon/gentankdiy.log

Did these changes coincide with you filling the tank or do does this change possible represent a change in the circuit, a short??

**Comment by davisgoodman** [comment]
Yes the lower levels were before I refueled and they seemed to work well. We weren't sure if we were going to have enough until this morning so I did shutdown the generator therefore all my network went down. This morning when I turned the generator back on and genmon, I couldn't access it anymore although it was sending me some alerts. 

So I decided to re-install from scratch with the backup I had made on May 24th. I re-installed Raspbian which now seems to be Bullseye and recovered my backups. 

May not be related at all but.. On the first boot of the OS I could connect with my Wifi interface. Did the apt get update and after a reboot no more wifi interfaces. For now I have an ethernet cable.

After I've re-enable I2C and could see the interface at 0x48. From there, the propane truck got here and added 901 liters. I wanted to see where it would bring each tank. At start, I figured 82% right after the refuel kinda made sense but now it doesn't

**Comment by jgyates** [comment]
@davisgoodman 

I would disable the "Enable Debug" option on the advanced page. All this does is read every register (even unknown registers) over modbus and send me emails. This option is for debugging unknown generator functionality so all this is doing is creating extra writes to you SD card.

Regarding your gauge issue, according to the logs it is displaying what is read over the I2C channel. I do not have a DIY gauge. This add on was submitted by others so I am a bit limited in the guidance I can give at the i2c level so I will leave this to others to answer.

**Comment by davisgoodman** [comment]
@jgyates Sorry about that. I<ve disabled it. Should be good now

**Comment by zekyl314** [comment]
@davisgoodman is there a possibility of a short or something wrong with your ADC now?  I've checked and re-checked mine and it is working as it should.  Any commands you ran that you want me to try and get the same output from my genmon to help compare?
-Mike

**Comment by jgyates** [comment]
a photo of your wiring may help

**Comment by davisgoodman** [comment]
Yeah, I thought of it overnight, could be the AD converter that’s blown up. I have another one in the box I made for a friend, I’ll swap it and see if I get a different results and…. check my wiring. 

 

But on that matter, it`s strange because the reading was fine right before the truck got here. I took a snapshot of the readings right before he started the refill and the lower numbers you see in the logs are what the snapshot showed. He filled the tanks and right after I checked the web gui and that’s where I got that 82%. 

 

The box hasn’t been tampered with in between these two periods.

 

I’ll get on this right now and report back.

**Comment by zekyl314** [comment]
Good luck, would love to know what you find.  I hope nothing got damaged by them filling the tanks.  I know I have my wires in conduit all the way to the physical tank gauge.  
-Mike

**Comment by davisgoodman** [comment]
Could this be an issue :
referenced here: http://www.bristolwatch.com/rpi/ads1115.html
An issue to be aware of is the pull up resistors built into the boards as shown in Fig. 2. The Raspberry Pi I2C connections is 3.3-volts and has its own pull up resistors. This may create problems - either remove/cut the pull ups or in my case I used a level translator to operate the ADS1115 at 5-volts and isolate the pull up problem.

**Comment by davisgoodman** [comment]
I think I found a bug...Jason what is the easiest way to get the tank gauge to update faster than 1 min. I have set up a variable power supply at the input of the A2D and right now, seems that when I get at 4.1 volts which gives me an 82% reading, anything higher makes no difference to the readings.I pointed out an article about the pull-up resistors, could this be the issue?On 27 mai 2022, at 14 h 27, Mike Walter ***@***.***> wrote:Good luck, would love to know what you find.  I hope nothing got damaged by them filling the tanks.  I know I have my wires in conduit all the way to the physical tank gauge. -Mike—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by jgyates** [comment]
Just enter a floating point value for poll time (i.e. 0.5)

**Comment by davisgoodman** [comment]
Ok perfect but by now I can confirm... it tops at 82% on anything higher that 4.1V at the input of the A2D

**Comment by davisgoodman** [comment]
Ok maybe I misread something, should the AD be fed 3.3v or 5v? Right now I'm feeding 5v to both the AD and the sensor

**Comment by davisgoodman** [comment]
@zekyl314 and to confirm on my main genmon, for now all 3 readings are higher than 4.1v hence all gauges are at 82%

**Comment by zekyl314** [comment]
> Ok maybe I misread something, should the AD be fed 3.3v or 5v? Right now I'm feeding 5v to both the AD and the sensor

I don't have anything special hooked up to mine.  I am connected just like the diagram in the wiki page.

**Comment by zekyl314** [comment]
> @zekyl314 and to confirm on my main genmon, for now all 3 readings are higher than 4.1v hence all gauges are at 82%

I am not sure I have an easy way to affect my voltage based on where my genset and take are located.  If it doesn't keep raining here, I'll see if I can add 1.5V batter to it to get over 4V.  I can't say that my tank has been over 60% full since I started the project, we just don't lose power much and the other items on propane are just my oven and gas grill.  
-Mike

**Comment by zekyl314** [comment]
> Ok maybe I misread something, should the AD be fed 3.3v or 5v? Right now I'm feeding 5v to both the AD and the sensor

To be clearer, I am running 3.3v to my ADS1115 and 5v to the sensor connected to the tank.

**Comment by davisgoodman** [comment]
Ok so, I moved the AD to 3.3v and now I’m feeding 4.5v and should read 90% but still at 82%.

 

Not sure what next from here but I’m more than willing to be the test bench with my second genmon and power supply

**Comment by zekyl314** [comment]
I’m going to try and see if I can fake some voltage this weekend and see what I come across. I don’t know anything else to try.  It here is a a c program which based this all from that polls the device. I think it’s linked in the wiki. I compiled it on mine and you can run it and see what values you see there too?

-Mike

**Comment by davisgoodman** [comment]
So this morning, all tank gauges are reporting under 82%
![image](https://user-images.githubusercontent.com/37666918/170823897-b9a7657a-cccd-4498-ad97-17cd8575d6e8.png)

**Comment by zekyl314** [comment]
[ads1115b.c.txt](https://github.com/jgyates/genmon/files/8791091/ads1115b.c.txt)
Can you try taking the c program (rename from .txt), edit the value for your setup and then run `gcc ads1115b.c -o fuellevel` and then run it and see what the voltage would be?  This way we can compare the value that genmon is getting and you can see it on the console quickly.

Even run watch -n5 ./fuellevel and it will poll every 5 seconds, then if you can fluctuate the voltage you can see near real live voltage, or change to -n1 for 1 second polling.

**Comment by davisgoodman** [comment]
@zekyl314 
So it's consistent, even with the C program, Voltage stops at 4.1 because the register is at max. Here I have 4.2volts applied 
Every 1.0s: ./fuellevel_ANC0                                                                                                                             

Values: HEX 0x7fff DEC 32767 reading 4.10 volts.
Anything under 4.1 V tracks perfectly

**Comment by zekyl314** [comment]
Well shoot. I never had my tank over 80% when I did this. I’ve not been able to test mine to also confirm mine does the same, but based on what you said it would make sense. 

I wonder if there is a way around it. I’ll have to do some digging, unless you already have an answer or idea. 

-Mike

**Comment by davisgoodman** [comment]
So the more I read the more the VDD needs to be 5V. The Gauge Sensors are optimal at 5V but can work from 3.5 to 6.0V with decrease of accuracy as stated in the datasheet. Also I believe Bits 11:9 for the gain needs to be set at 000 and not 001. The +- 4.096 corresponds exactly at we're seeing the 82% mark 4.1V. 
I'm doing a bit of fool around with the C code to see if I can manage to read 4.2V out of it at some point. I've shut down gentankdiy to make sure I don`t have any interference. 
It also states in the datasheet that inputs should never be higher than + .3v of VDD so having the AD at 3.3 and feeding the sensors at 5v shouldn't have worked but I guess it`s just a warning.
I wonder if the pull-up resistors could be the issue, there was a mention about that in the original post?

**Comment by davisgoodman** [comment]
@zekyl314 

So, changing the gain to 2/3 I now get the right reading. Though by mistake I had misread the diagram and fed it 5v and not 3.3 so it had the right VDD but the wrong gain.
pi@generac:~/src $ ./fuellevel_ANC0_6.1
Values: HEX 0x67f2 DEC 26610 reading 4.99 volts.

Here is the diff:
pi@generac:~/src $ diff ads1115b_ANC0.c ads1115b_ANC0_6.144.c
1c1
< // ads1115b.c read pot on ANC1
---
> // ads1115b.c read pot on ANC0
31c31,37
< const float VPS = 4.096 / 32768.0; //volts per step
---
> //const float VPS = 4.096 / 32768.0; //volts per step
>
> /*
> To allow readings up to 5 Volts
> Resolution is now 187.5uV per steps
> */
> const float VPS = 6.144 / 32768.0; //volts per step
55c61
<   // ANC1 and GND, 4.096v, 128s/s
---
>   // ANC0 and GND, 6.144v, 128s/s
59c65,67
<   writeBuf[1] = 0b11000011; // bit 15-8 0xD3
---
>   //writeBuf[1] = 0b11000011; // bit 15-8 0xD3
>   // Custom for Davis - Port A0 and 5.0V
>   writeBuf[1] = 0b11000001; // bit 15-8 0xC1

**Comment by davisgoodman** [comment]
@jgyates @zekyl314 

![image](https://user-images.githubusercontent.com/37666918/170844115-28f9bc2f-23e2-4953-92d0-e9cf8d2700e7.png)

Jason I manually modified gaugediy.py in genmonlib and seems to work.

On thing I noticed and this is more semantic but the steps are not in mv but rather in uV. So the changes were basically changing the steps from 125 to 187.5 and changing each write buffer for bit 15-8 from 0xC3 to 0xC1 and so on for each input.



diff gaugediy.py.old gaugediy.py

`71c71
<         self.mv_per_step = self.config.ReadValue('mv_per_step', return_type = int, default = 125)
---
>         self.mv_per_step = self.config.ReadValue('mv_per_step', return_type = int, default = 187.5)
122c122
<                 CONFIG_VALUE_1 = 0xC3 # 1 100 001 1 --> Begin a single conversion, AIN(pos) = AIN0 and AIN(neg) = GND, Gain +/-4.096V, Power-down single-shot mode (default)
---
>                 CONFIG_VALUE_1 = 0xC1 # 1 100 000 1 --> Begin a single conversion, AIN(pos) = AIN0 and AIN(neg) = GND, Gain +/-6.144V, Power-down single-shot mode (default)
124c124
<                 CONFIG_VALUE_1 = 0xD3 # 1 101 001 1 --> Begin a single conversion, AIN(pos) = AIN1 and AIN(neg) = GND, Gain +/-4.096V, Power-down single-shot mode (default)
---
>                 CONFIG_VALUE_1 = 0xD1 # 1 101 000 1 --> Begin a single conversion, AIN(pos) = AIN1 and AIN(neg) = GND, Gain +/-6.144V, Power-down single-shot mode (default)
126c126
<                 CONFIG_VALUE_1 = 0xE3 # 1 110 001 1 --> Begin a single conversion, AIN(pos) = AIN2 and AIN(neg) = GND, Gain +/-4.096V, Power-down single-shot mode (default)
---
>                 CONFIG_VALUE_1 = 0xE1 # 1 110 000 1 --> Begin a single conversion, AIN(pos) = AIN2 and AIN(neg) = GND, Gain +/-6.144V, Power-down single-shot mode (default)
128c128
<                 CONFIG_VALUE_1 = 0xF3 # 1 111 001 1 --> Begin a single conversion, AIN(pos) = AIN3 and AIN(neg) = GND, Gain +/-4.096V, Power-down single-shot mode (default)
---
>                 CONFIG_VALUE_1 = 0xF1 # 1 111 000 1 --> Begin a single conversion, AIN(pos) = AIN3 and AIN(neg) = GND, Gain +/-6.144V, Power-down single-shot mode (default)
`

Also modified the value for mv_per_step ( which should read uv_per_step) :-)  in /etc/genmon/gentankdiy.conf

**Comment by jgyates** [comment]
@zekyl314 are you in agreement with the changes above? Since I don't use this add on I want to get everyones input.

**Comment by davisgoodman** [comment]
@jgyates If Mike is ok with it, the Wiki should be updated where it shows the AD connected to 3.3V. Should be moved to 5.0V
![image](https://user-images.githubusercontent.com/37666918/170847438-9ebf6871-ebbd-40e8-b374-dd4e6286e0da.png)

**Comment by jgyates** [comment]
I went ahead and checked in the update and updated the wiki. Let me know if there are any issues.

https://github.com/jgyates/genmon/wiki/Appendix-L-Adding-a-Propane-Fuel-Gauge-to-Genmon

**Comment by zekyl314** [comment]
> @zekyl314 are you in agreement with the changes above? Since I don't use this add on I want to get everyones input.

This seems to make sense.  I goofed on the setup as well since I never had a full tank or even over 80% when I set this all up.  I was using data from other sites to make this work.  I appreciate @davisgoodman for all your help in getting this fixed.  Sorry it didn't work as expected.  I learned a lot from your troubleshooting and diagnosis.

**Comment by davisgoodman** [comment]
@jgyates 

All looks good. I just realized though I hadn't modified the comments in the gaugediy.py.

`
            # set config register  and start conversion
            # ANC1 and GND, 6.146v, 128s/s
            # Customized - Port A0 and 6.146v V input
            # 0b11000011; # bit 15-8  = 0xC1
            # bit 15 flag bit for single shot
            # Bits 14-12 input selection:
            # 100 ANC0; 101 ANC1; 110 ANC2; 111 ANC3
            # Bits 11-9 Amp gain. Default to 010 here 001 P19
            # Bit 8 Operational mode of the ADS1115.
            # 0 : Continuous conversion mode
            # 1 : Power-down single-shot mode (default)
`
and this is again just a semantic thing, is mv_per_step only used in gaugediy.py and /etc/genmon/gentankdiy.conf?

I would suggest making it uv_per_step just to be precise! :-) but that's your call.

**Comment by davisgoodman** [comment]
> > @zekyl314 are you in agreement with the changes above? Since I don't use this add on I want to get everyones input.
> 
> This seems to make sense. I goofed on the setup as well since I never had a full tank or even over 80% when I set this all up. I was using data from other sites to make this work. I appreciate @davisgoodman for all your help in getting this fixed. Sorry it didn't work as expected. I learned a lot from your troubleshooting and diagnosis.

No worries, I learned a lot more than you can imagine and as I'm not a programmer but just like some languages, I'm not too good at writing code but I can read it pretty well.
I love these challenges which forces me to get to understand stuff I'm not familiar at all with.

I should have a refill done in a week or two. Already down to 76% from Thursday refill. Hopefully we'll get our power back tomorrow.

**Comment by jgyates** [comment]
for anyone else reading this who does this update, dont forget to update your /etc/genmon/gentankdiy.conf and change the mv_per_step value from 125 to 187.5. The update from the about page will not make any changes to /etc/genmon/*

**Comment by zekyl314** [comment]
Great to hear!  I need to change mine to 5V and then test.  But my tank won't get filled for a while, as we don't use much.

**Comment by davisgoodman** [comment]
Yeah I did notice and set it up. Now that I have all 3 tanks in Home Assistant I'm actually getting the average from there, so I'm all set.

Thanks again.

On a side note, still working out my git issue on the PI, but that is a different topic.
________________________________

**Comment by davisgoodman** [comment]
Nah.. I was right beside him and he actually mentioned that he wish everyone had a tank setup like I did.😁
________________________________

**Comment by davisgoodman** [comment]
I’ve found this and playing around with it.

 

https://learn.adafruit.com/raspberry-pi-analog-to-digital-converters/ads1015-slash-ads1115

 

I can get some reading out of simpletest.py. Playing around with the different settings. Will try to get 32767 with a 5 volt to the input.
