### ISSUE TITLE
Another "System Initializing. Not receiving data" problem (sorry!)

### ISSUE THREAD

**Issue by eBoon123** [jgyates/genmon#564]
### Expected Behavior

New install of Generac 18KW generator with Evolution 2 controller - expecting to see data from the generator

### Actual Behavior

Monitor page shows: Not receiving data

### Steps to Reproduce (including precondition)

Look at web page

### Screenshot or Pictures relating to the problem (if possible)

{Please write here}

### Your Environment

- Generator Model: Generac Guardian 18kW G007226-0,
- Genmon Logs: Submit via the About page
- Genmon Version: V1.16.13

First off - thank you for a great project - very excited to get past this issue and explore all the data on my new generator!

Just had my generator installed yesterday and have set up Genmon on a Raspberry Pi 3. I have reviewed the troubleshooting guide and I am not having any luck getting data to genmon.

I am powering the Raspberry Pi off of the battery using a MotoPower 12V to USB module.

Here are the results of serialconfig:

![serialconfig](https://user-images.githubusercontent.com/15703884/127714077-cd344f9a-b89e-4590-98af-04e4748e98d5.JPG)

Here are the results of serialtest - the first test without the loopback in place and the second (successful!) with the loopback in place :

![serialtest](https://user-images.githubusercontent.com/15703884/127714166-c4969f90-6b55-44c7-9c9a-d0737724a792.JPG)

Here are pictures of my cable and connections inside the box:
![2](https://user-images.githubusercontent.com/15703884/127714508-0d5a9d69-b3c4-4204-87a7-fb068b5392a7.JPG)
![1](https://user-images.githubusercontent.com/15703884/127714412-087385d1-7f49-4390-81be-b9ea953aeb50.JPG)
The black and red wires are spliced into the yellow wires in the above picture. Black is going to Pin 8 and Red is going to Pin 7 on the Molex connector. I also switched the Red and Black wires around - same results.
![3](https://user-images.githubusercontent.com/15703884/127714603-d7ff6b68-6d98-446b-b3e5-eb967b3933a9.JPG)
![4](https://user-images.githubusercontent.com/15703884/127714816-2fe56790-3491-49fb-83aa-4d39a91a799e.JPG)

I have also just sent logs via the About Page.

Thank you in advance for any help!!

**Comment by skipfire** [comment]
The pic doesn't show how the yellows go to the red/black on the screw terminals , but TX and RX may be backwards, loopback will work but it will fail after.

**Comment by eBoon123** [comment]
> The pic doesn't show how the yellows go to the red/black on the screw terminals , but TX and RX may be backwards, loopback will work but it will fail after.
Black is going to Pin 8 and Red is going to Pin 7 on the Molex connector. I also did switch them around just in case...unfortunately did not help.

Thanks for the reply!

**Comment by skipfire** [comment]
You might also try connecting ground on the molex.

**Comment by jgyates** [comment]
I agree with @skipfire, connect pin 2 on the molex (Ground) to pin 5 on the DB9 modular connector. This will connect ground from the controller to the RS-232 board.

**Comment by eBoon123** [comment]
I had very high hopes that the ground would fix the issue - unfortunately, it made no difference.   :-(

**Comment by jgyates** [comment]
Now that there is a ground have your tried swapping the Tx and Rx again?

**Comment by eBoon123** [comment]
> Now that there is a ground have your tried swapping the Tx and Rx again?

Yes - tried both ways...

**Comment by jgyates** [comment]
I am assuming your loopback was at the molex end of your cable, let me know if this is not the case.

Your logs show that you are getting 100% time out errors (i.e. nothing is returning from the controller). You could have a bad molex pin on your controller or a bad RS-232 driver or receiver on your controller. If you have a multimeter you could measure the voltage levels of the tx pin on the controller (the one that goes to the rx pin on the RS-232 connector). This should be a negative voltage relative to ground pin), generally between -3 and -12 volts depending on the type of transceiver. 

Also, I assume this is a new unit with the wifi module. is the wifi module unplugged? a picture of the connection may help.

**Comment by eBoon123** [comment]
>I am assuming your loopback was at the molex end of your cable, let me know if this is not the case.

 Yes - that is the case

>Your logs show that you are getting 100% time out errors (i.e. nothing is returning from the controller). You could have a bad molex pin on your controller or a bad RS-232 driver or receiver on your controller. If you have a multimeter you could measure the voltage levels of the tx pin on the controller (the one that goes to the rx pin on the RS-232 connector). This should be a negative voltage relative to ground pin), generally between -3 and -12 volts depending on the type of transceiver.

 Will give this a go tomorrow

>Also, I assume this is a new unit with the wifi module. is the wifi module unplugged? a picture of the connection may help.

 I'll attach a picture tomorrow, but yes, this is a NEW unit with the WiFi module. The WiFi module is unplugged for right now - but I do intend to plug it back in once I get genmon working.

Thanks again for your help!

**Comment by eBoon123** [comment]
> > I am assuming your loopback was at the molex end of your cable, let me know if this is not the case.
> 
> Yes - that is the case
> 
> > Your logs show that you are getting 100% time out errors (i.e. nothing is returning from the controller). You could have a bad molex pin on your controller or a bad RS-232 driver or receiver on your controller. If you have a multimeter you could measure the voltage levels of the tx pin on the controller (the one that goes to the rx pin on the RS-232 connector). This should be a negative voltage relative to ground pin), generally between -3 and -12 volts depending on the type of transceiver.
> 
> >Will give this a go tomorrow

> >> NVM - decided to do this tonight.. The WHITE wire is the ground coming from the controller (pin #2 on the molex connector) and the BLACK wire is the Tx coming from the controller (pin #8 on the molex connector).  This is showing POSITIVE 6.57 volts. 
![groundtoTX](https://user-images.githubusercontent.com/15703884/127725270-292da395-05e3-4689-9a61-231d03a98ff6.JPG)
Just for fun - here is molex pin #7 (Rx - red wire) and pin #2 (ground - white wire) showing -.4 volts
![groundtoRX](https://user-images.githubusercontent.com/15703884/127725375-caa8554d-08c1-4874-8a72-fa0d1589085b.JPG)


> > Also, I assume this is a new unit with the wifi module. is the wifi module unplugged? a picture of the connection may help.
> 
> >I'll attach a picture tomorrow, but yes, this is a NEW unit with the WiFi module. The WiFi module is unplugged for right now - but I do intend to plug it back in once I get genmon working.
>>>My connections:
![C1](https://user-images.githubusercontent.com/15703884/127725717-4663091a-bcb9-4a00-b610-b20a0d720c5a.JPG)
![C2](https://user-images.githubusercontent.com/15703884/127725743-4eb4bfba-5c77-4f76-a6f2-c258502863b9.JPG)
Plugging here on the controller:
![port](https://user-images.githubusercontent.com/15703884/127725758-f9d515f9-30aa-454d-b163-f5cff2bd4cf6.JPG)

> 
> Thanks again for your help!

**Comment by jgyates** [comment]
That voltage is correct (ground should go to the common on your meter so if you revers them you should get negative 6V. If you plug this in to your connector can you measure the -6V on the Rx pin? while you are at it you can check the voltage of the tx output on your RS-232. This should be in the same range (negative voltage when idle).

**Comment by eBoon123** [comment]
> That voltage is correct (ground should go to the common on your meter so if you revers them you should get negative 6V.
  
  LOL - that's the problem with using a WHITE wire for the ground - didn't even notice I reversed it! :-)

>If you plug this in to your connector can you measure the -6V on the Rx pin? 
 
Like this? (sorry I'm a bit nooby with the multimeter):
![aa](https://user-images.githubusercontent.com/15703884/127726364-a536fe77-f78d-437e-b6c5-4a54a2b702c1.JPG)

>while you are at it you can check the voltage of the tx output on your RS-232. This should be in the same range (negative voltage when idle).

 Like this?
![bb](https://user-images.githubusercontent.com/15703884/127726532-9df76590-adae-4163-9a48-90aa81b3dce5.JPG)

Thanks!

**Comment by jgyates** [comment]
All the measurements should be on the green connector if you are measuring the RS-232 levels. If you measure on the pi side it will be 3.3v or zero volts only depending if it is a logic 0 or 1 respectively).

**Comment by eBoon123** [comment]
> That voltage is correct (ground should go to the common on your meter so if you revers them you should get negative 6V. If you plug this in to your connector can you measure the -6V on the Rx pin? 

![red2gnd](https://user-images.githubusercontent.com/15703884/127738420-83d07e21-36d6-41e4-b0ce-c37f6e9b0489.JPG)

>while you are at it you can check the voltage of the tx output on your RS-232. This should be in the same range (negative voltage when idle).

![Blk2gnd](https://user-images.githubusercontent.com/15703884/127738395-95eace2c-42aa-4195-96bd-2c6ddb88757b.JPG)

Hope I got the measurements correct. Thank you again for your help and patience!

**Comment by jgyates** [comment]
This looks good. If genmon is running do you see these values change (I am not sure that the fidelity of your multimeter will show this but it might). I would guess that you should see the values not be stable while genmon is running, possibly moving very briefly every 3 seconds (the length of the time out)or so. If you see the pi transmit fluctuate but not the receive then this puts the problem on the RS-232 side.

**Comment by eBoon123** [comment]
OK - A couple of updates. When I plugged everything in this morning to take the above pictures - I left everything running while I went on an errand. Came back and realized that Genmon was actually working! (Yay!). So, of course, I had to shut it down and remove (only!) the molex connector from the generator so I could bring the box inside to measure for the hole I am going to cut to run wires. I then went out and put everything back and (of course!) I am now right back where I started - Not Receiving Data.

Weird - but I'm too surprised because I didn't change anything from yesterday when it was not working. So the mystery is why did it work 1 time and not the other 20 times I tried - sounds like something is flakey.

I did repeat the voltage measurements from above on the Rx and Tx pins - but this time my voltages are both about 3.99 - not sure if that is significant or not.

>If genmon is running do you see these values change (I am not sure that the fidelity of your multimeter will show this but it might).

Yes - but only very small changes on the third decimal point value.

**Comment by skipfire** [comment]
I would think that it is some kind of cable issue.  It looks like you have a change in gauge from the molex wire to your extensions, that is the first spot I would check.  If you removed and reseated any molex pins you may want to recheck the seating on those.

I set mine up with the molex wires going directly into the serial screw terminals making a 4 inch cable, then used a serial extension cable for the distance, it avoided manual splices and had a better cable for the distance portion.

**Comment by skipfire** [comment]
You might also check for any stray conductors at the screw terminals, maybe you have one that flared out instead of going into the screw terminal and is making contact with the other wire direction.

**Comment by eBoon123** [comment]
> I would think that it is some kind of cable issue. 

Ding Ding Ding!
![Capture](https://user-images.githubusercontent.com/15703884/127751847-f10b8c00-516a-4ffa-a312-fceb27a10705.JPG)

It's either these jumpers or the pins. Kept fiddling with these connections and finally, it's working! Of course the board could also be flakey, but I'll keep an eye on it and see if it keeps running.

Thank you @jgyates and @skipfire for your help and advice! Very excited to start playing with the app!!

**Comment by skipfire** [comment]
I would suggest putting heatsinks on the 2 top chips since this will be outside in the heat and with the case pictures you have I'm guessing there is not much airflow.

**Comment by eBoon123** [comment]
> I would suggest putting heatsinks on the 2 top chips since this will be outside in the heat and with the case pictures you have I'm guessing there is not much airflow.

Already ordered and should be here tomorrow. Hoping that with that box all buttoned up it doesn't get too hot in there!

**Comment by skipfire** [comment]
It has been in the 90s here lately and I have my Pi in the generator and see CPU peaking around 65C, so it gets hot but not too hot.

**Comment by jgyates** [comment]
I am glad it is working now. I am going to close this thread but feel free to comment here if you have related issues or questions.

**Comment by jgyates** [comment]
@eBoon123 

I checked in a minor update that includes identification and fuel consumption of the Evolution 2.0 18kW model (V1.17.01).

**Comment by eBoon123** [comment]
> @eBoon123
> 
> I checked in a minor update that includes identification and fuel consumption of the Evolution 2.0 18kW model (V1.17.01).

Awesome - just upgraded. I can now see values (0.00) instead of unknown.

Thanks again for this project - looking forward to playing with it more!

**Comment by eBoon123** [comment]
I am thinking more and more that my TTL to RS232 board is bad - stopped receiving data again last night. I am currently using [this board](https://www.amazon.com/dp/B072KJSS5C/ref=sspa_dk_detail_3?psc=1&pd_rd_i=B072KJSS5C&pd_rd_wg=Nd6FS&pd_rd_r=VZ5RZZSGJ0JP5JMS1AYK&pd_rd_w=UqGO1). This is the board that was recommended as a second choice in the Hardware Wiki. Amazon currently does not have any stock for [the first board that was recommended](https://smile.amazon.com/gp/product/B00EJ9NAKA/ref=oh_aui_detailpage_o03_s00?ie=UTF8&psc=1).

Any suggestions on an alternate board? Would [this ](https://www.amazon.com/HiLetgo-MAX3232-Converter-Module-Serial/dp/B00LPK0Z9A/ref=asc_df_B00LPK0Z9A/?tag=hyprod-20&linkCode=df0&hvadid=390329205806&hvpos=&hvnetw=g&hvrand=12057979747322657643&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9010585&hvtargid=pla-906418052077&psc=1&tag=&ref=&adgrpid=79862087277&hvpone=&hvptwo=&hvadid=390329205806&hvpos=&hvnetw=g&hvrand=12057979747322657643&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9010585&hvtargid=pla-906418052077) work?

Thanks again for all the help!

**Comment by jgyates** [comment]
Yes, that should work.

**Comment by jgyates** [comment]
@eBoon123 

Since you have "Automated Feedback" enabled, your genmon installation sent a notice to me of an alarm log entry that the software has not seen before. If you can look at your log on your generator and let me know the exact text of the log with this date and time (08/01/21 21:24:39) I can add it to the software. I am guessing this is a new alarm code that is specific to Evolution 2, but that is a guess.

**Comment by eBoon123** [comment]
I’m guessing this is it:

This is a snapshot from Mobile Link - is there somewhere else I should look
to get you the info?

Thanks

**Comment by jgyates** [comment]
Images are stripped if you replay to the thread in email. You can post an image directly in the thread on github via this link in a browser:

      https://github.com/jgyates/genmon/issues/564

You can also go to your generator and select Sub Menus -> History -> Alarm Log then scroll thru until you see the entry with this date:

   08/01/21 21:24:39

Then just type in the text for that log entry into this thread.

**Comment by eBoon123** [comment]
Looks like a 2 liner:
"WIRING ERROR"
"ERROR CODE 2098"

A little background - had a large storm here with a lot of lightning last
night. I saw a huge strike very near our house and noticed the status LED
on the generator was Red. Went out and reset and put the generator back
online - no further issues (so far).

I did a bit of research and found that one of the potential (non-wiring
error) ways to get this error, is a large nearby lightning strike - so
hoping that's was was the case.

Thanks again for all of your help and such an awesome project. Please let
me know if you have any questions or need me to look at anything further.

**Comment by jgyates** [comment]
I checked in an update that should report this log entry correctly now. I did not update the version number so just go to the About page and update the software and your should be good.

**Comment by eBoon123** [comment]
Looks good - thanks!
