### ISSUE TITLE
[Feature Request] - Option to remember 2FA for 30 days

### ISSUE THREAD

**Issue by danodemano** [jgyates/genmon#565]
This seems like a regular thing when 2fa is used. Would it be possible to have a remember for 30 days where you don't have to enter the code during that time? Super-low priority but wanted to at least throw it out there. As always thanks for the amazing project!

**Comment by jgyates** [comment]
To do that I would need to store some type of authentication cookie in the browser. I will keep this in mind when changes are made to the web app. https://github.com/jgyates/genmon/blob/master/feature_requests.md
