### ISSUE TITLE
Syslogging

### ISSUE THREAD

**Issue by lanhampr** [jgyates/genmon#587]
Looking for direction on getting Genmon syslog messages delivered.  How do I setup the IP:port of the destination server? Is this a linux config or Genmon config? Do Genmon syslog messages get stored in gensyslog.log? Thank you for any advice.

**Comment by jgyates** [comment]
Hi @lanhampr 

Sending syslog messages from one computer to another is a linux thing. This article covers that:

https://www.techrepublic.com/article/tech-tip-enable-remote-logging-with-syslog/

/var/log/gensyslog.log is where error for the gensyslog.py add on are stored. The sys log for linux is stored in /var/log/syslog
The genmon software will log generator events to the local syslog if the "Linux System Logging" add on is enabled on the Add On page in the web interface.

There is a separate add on to log genmon events to CSV file.
