### ISSUE TITLE
ATS fail detection?

### ISSUE THREAD

**Issue by skipfire** [jgyates/genmon#593]
Does the generator know if the transfer fails?  My ATS isn't transferring and the generator did not error and GenMon didn't show anything.  Any idea how difficult it would be to have GenMon notice that the transfer switch should be engaged but no significant power output has occurred after 5 minutes and then fire its own alert?

Because I know the helpful people here will also want to see if they can help me fix the ATS, I am pretty sure it is the electromagnet as I hear the relay click when it should, but no buzz or clank.  It successfully transferred last week for an outage, but didn't during my scheduled transfer test today.  Tomorrow I'm going to take the panels off to take a look and do a manual transfer test.

**Comment by jgyates** [comment]
For the "dumb" type ATS (the ones typically used with Evolution and Nexus), my understanding is, no, there is nothing that tells the controller that the switch has a problem. I think the sequence of events is this:

1) Controller detects outage and starts engine if in auto mode, it waits for the warmup time (default is 5 seconds)
2) controller signals ATS via a relay 
3) ATS switch engages 

The controller knows that it has signaled the relay but does not know if the actual ATS is engaged.

@liltux may have more details as he know a lot more about this than I do.

**Comment by griffths** [comment]
There are a set of dry contacts that can be used to confirm transfer switch position but of course that would require a physical connection to the Pi or some other way to get that information to Genmon

**Comment by skipfire** [comment]
@jgyates what about GenMon detecting the possible failure through data?  If it is a transfer test, but output power doesn't measure above 500w for 5 minutes, some kind of notification or warning of a possible problem?

**Comment by grsthegreat** [comment]
make sure both wires are plugged into the coils. the upper coil is the utility coil, the lower coil is the generator coil. i get service calls all the time about switches not transferring, and more times than not a wire fell off. may have to physically tighten the spade connector if its loose.

**Comment by skipfire** [comment]
@grsthegreat is the purple wire the one you were thinking of?  Once I opened the switch it sure stood out.

**Comment by liltux** [comment]
On the right side of the new switches it is standard to have an additional auxiliary contact that will change states.  That could be taken to the Rpi as in input.  This would be the best way to monitor switch state change.  Also all newer Gens all have CTs.  The switches that do not have an Aux contact it is easy to add.

**Comment by grsthegreat** [comment]
yes. the wire slipped off of the coil. slightly recrimp connector and reinstall

**Comment by skipfire** [comment]
Thanks @grsthegreat, tested again and it is working again.

**Comment by grsthegreat** [comment]
good to hear. make sure none of the others are loose

**Comment by skipfire** [comment]
> good to hear. make sure none of the others are loose

None of the others moved with a gentle tug, but I have my semi-annual service this month so I'll ask them to double check as well.  Thanks for the help.

**Comment by jgyates** [comment]
I added this to the feature request list. I will update this thread when it has been added.

**Comment by jgyates** [comment]
https://github.com/jgyates/genmon/blob/master/feature_requests.md
