### ISSUE TITLE
Not able to Login to Web Interface - Post Python 3 upgrade

### ISSUE THREAD

**Issue by sambeetm** [jgyates/genmon#601]
Issue#1
--------
Getting following error in the /var/log/genserv.log.
I do have a "%" character in the password. Looks like its causing issue now after the python 3 upgrade. 

Error in MyConfig:ReadValue: GenMon: http_pass: '%' must be followed by '%' or '(', found: '%' : myconfig.py:85
2021-11-10 13:02:37,306 : Starting /home/pi/genmon/genserv.py, Port:443, Secure HTTP: True, SelfSignedCert: True

After I edited, the genmon.conf to remove the % character from the password, its working.

Issue#2
--------
gengpio.py is not running anymore.

 ./startgenmon.sh restart
Restarting genmon python scripts
Stopping....
Stopping genemail2sms.py
Stopping gengpio.py
kill: (6964): No such process
Stopping gengpioin.py
Stopping genlog.py
Stopping genpushover.py
Stopping genserv.py
Stopping genmon.py
Starting....
Starting /home/pi/genmon/genmon.py
Starting /home/pi/genmon/genserv.py
Starting /home/pi/genmon/genpushover.py
Starting /home/pi/genmon/genlog.py -f /home/pi/genmon/LogFile.csv
Starting /home/pi/genmon/gengpioin.py
Starting /home/pi/genmon/gengpio.py
Starting /home/pi/genmon/genemail2sms.py

**Comment by jgyates** [comment]
I found a problem I introduced in V1.17.5 in gengpio.py. I checked in an update so click update from the About page or type

      ./genmonmaint.sh -u
      ./startgenmon.sh restart

Let me know how it goes.

**Comment by sambeetm** [comment]
Thanks for the quick fix. Working as before !
