### ISSUE TITLE
[ LOW-PRIORITY REQUEST ] - Dark mode

### ISSUE THREAD

**Issue by danodemano** [jgyates/genmon#602]
So this would be like the lowest of low-priority, lol. I'm going to ask anyway though - I would love for the UI to have a dark mode option.

**Comment by jgyates** [comment]
It is on the list. Thanks.

**Comment by jgyates** [comment]
https://github.com/jgyates/genmon/blob/master/feature_requests.md

**Comment by jgyates** [comment]
This is now in version 2.0
