### ISSUE TITLE
Firmware Release 1.20 NO COMMS to Genmon 

### ISSUE THREAD

**Issue by fdcaptjd** [jgyates/genmon#613]
Hello,

My 2016  22KW unit has just had a stator replaced under the extended warranty by a dealer. 

I have been told this also required a new controller.

This new controller is running 1.20 firmware.

Genmon is not communicating at this point. I have attached a screen shot of the stats.

Thanks,

Jeff
![genmon](https://user-images.githubusercontent.com/95499621/144658703-75646b52-827d-44d4-a1a4-a89df763c7c2.PNG)

**Comment by jgyates** [comment]
I have many reports of firmware 1.20 working. I am guessing that this is either a connection problem or a defective controller.   The timeout errors indicate that either the packets sent by the pi are not being received or the response packets sent by the controller are not being received by the pi.

Make sure that your cable is attached to the new controller properly. If you can do that then try the loopback test to validate you pi is still functioning as expected. 

https://github.com/jgyates/genmon/wiki/3.6---Serial-Troubleshooting


I once had a controller replaced and the company doing the service initially tried to replace it with a controller with defective comms (the box was marked "no comms" with a sharpie). After I pointed this out they replaced it with another one. Of course your mileage may vary with another service tech.

**Comment by fdcaptjd** [comment]
Thank you for the quick response, and all the work you do on this project. 


Jeff

**Comment by grsthegreat** [comment]
that unit uses the evolution 1.0 or sync 2.0 controller (if labeled honeywell). the v1.20 software will not effect genmon operation.

take a look and see which of the 2 ports its plugged into, there are 2 accessory ports. labeled port 1 and port 2

**Comment by fdcaptjd** [comment]
Thanks for the info.

I did the loopback test yesterday and believe the problem is a failed TTL/235 convertor. Got good tests on the Pi, nothing after the convertor. 

JD

**Comment by jgyates** [comment]
I am going to close this issue for now but feel free to post here with any status updates or questions.
