### ISSUE TITLE
Any way to add second SMTP Configuration?

### ISSUE THREAD

**Issue by TopBanana123** [jgyates/genmon#627]
I currently have SMTP setup to go through my Office365 account, and the emails work great.

My goal is to setup some kind of local notifications, and one of the ways I found is to use local SMTP into this HomeBridge plugin, which would give me notifications through Apple HomeKit

https://github.com/SphtKr/homebridge-smtpsensor

But, that would wipe out my existing SMTP setup. Is there any way to add a second SMTP configuration?

**Comment by jgyates** [comment]
There is already a request for HomeBridge integration here

https://github.com/jgyates/genmon/issues/552

I will think on this feature vs the original homekit plugin method

**Comment by TopBanana123** [comment]
HomeBridge support would be AWESOME. Oh man, the cool things you could do

Plus, the all local notifications that would then be available

**Comment by jgyates** [comment]
I am going to close this issue as the hombridge support is already on the proposed feature list.
