### ISSUE TITLE
MQTT retain message

### ISSUE THREAD

**Issue by SethL** [jgyates/genmon#637]
I'm setting up mqtt with Home Assistant and it is working great.  The only issue I am having is that when the generator is not running all of my dashboards error out.  This is because the sensors are not reporting a value to HA via mqtt.  Is it possible to add the retain option to the mqtt module?  I think this would solve things as the broker would retain the last message which wold be zero.  

![image](https://user-images.githubusercontent.com/2295127/148101204-87206b70-6af8-42b3-a68c-b2780e4b729b.png)

**Comment by jgyates** [comment]
Have you tried using the flush interval option in the genmon MQTT add on? This will set a timeout that will send all values that are unchanged. If your HA setup has a default value that sets and error after a period of inactivity, set the flush internal to half of that value to guarantee that this error will not occur.

**Comment by SethL** [comment]
Ah ha!  
That did it.  I had to uncomment some of the disabled items but I am good to go. thanks!

![image](https://user-images.githubusercontent.com/2295127/148113978-a81357c9-4556-42fa-8cfb-9fedec3bd187.png)
