### ISSUE TITLE
Outage log and total consumption 461.55cf for 0:00 length outage

### ISSUE THREAD

**Issue by Starz26** [jgyates/genmon#638]
Not really looking to figure out why, just what I need to modify to remove the outage and update the Maintenance total consumption calculation.

I removed the line from the outage log but that did not cause a recalculation. Here is the current state:

outage.log

<img width="669" alt="image" src="https://user-images.githubusercontent.com/1149656/148631036-2d427be1-b43a-49a0-b79c-58ad457e2ee5.png">

Maintenance screen

<img width="486" alt="image" src="https://user-images.githubusercontent.com/1149656/148631044-dde64cb5-c830-47e0-bfd4-e8dd7d9e4e31.png">

How can I remove the 461.55 outage and the 461.55 from the total consumption?

**Comment by jgyates** [comment]
if you have removed that entry from the outage log in /etc/genmon/outage.txt, then the only other step should be to restart genmon. You can do this from the advanced page or via ssh. For ssh type:

      cd genmon
      ./startgenmon.sh restart

Genmon only reads the outage file on startup and keeps a copy in memory, but writes it when there is an outage.

**Comment by jgyates** [comment]
I am going to close this issue. Let me know if you still have questions.

**Comment by Starz26** [comment]
@jgyates I deleted the line from /etc/genmon/outage.txt and then did the /.startgenmon.sh restart

The maintenance screen still shows the 461.55

outage:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/1149656/148830358-aafe6cec-5d26-4077-ac2c-b973b2ac85bd.png">

Maintenance screen

<img width="555" alt="image" src="https://user-images.githubusercontent.com/1149656/148830443-4eba8839-10d9-4c43-940d-2593ebe67f9b.png">

**Comment by jgyates** [comment]
To delete the fuel consumption from the total you will need to delete the corresponding entries in /etc/genmon/kwlog.txt

To do this delete all of the entries with the date of the outage you deleted earlier (10-23-2020). Save the file, then restart genmon. There are several of these entries for that date, one every 10 seconds that the generator was running.

**Comment by Starz26** [comment]
> To delete the fuel consumption from the total you will need to delete the corresponding entries in /etc/genmon/kwlog.txt
> 
> To do this delete all of the entries with the date of the outage you deleted earlier (10-23-2020). Save the file, then restart genmon. There are several of these entries for that date, one every 10 seconds that the generator was running.

:( there are no entries for 10/23/20 - may just have to reset power log and fuel consumption.
