### ISSUE TITLE
Question - Enabling External Current Transformer (CT) Sensors

### ISSUE THREAD

**Issue by TopBanana123** [jgyates/genmon#644]
I noticed in the latest update it added support for the PintSize.me external sensor board. I ordered one and it got delivered today

To enable support, is checking the box in the UI enough, or do I need to follow the CLI instructions as well?

![image](https://user-images.githubusercontent.com/43852644/149396699-468d0c27-7cfd-46b0-8baa-b0fc1b9ebc99.png)

I have a Liquid Cooled RG027 which can't measure current on its own, so this is an awesome feature

**Comment by TopBanana123** [comment]
Thanks! That worked

Any way to get the chart back, or is that dependent on the internal power output?

**Comment by TopBanana123** [comment]
Also, is there any way for a future feature to show amps per line, instead of added together. Pretty handy for seeing an unbalanced load if they were separate

**Comment by griffths** [comment]
@jgyates 

Not an expert on Linux by any stretch of the imagination....

I am running OS version 10 (Buster) according to the monitor page of Genmon.

Following this bit of your recipe, not sure I added the required text in the proper location.

"In earlier raspbian versions you can add this to the bottom of the file. Starting with Bullseye there are sections (i.e. [all], [pi4], [cm4], etc) in the config.txt file. Add the above line to the first (unnamed section)."

![Genmon CT config](https://user-images.githubusercontent.com/19066716/149427293-cc62cf85-fd76-4e41-9885-3f13be550a29.png)

**Comment by TopBanana123** [comment]
@griffths I added mine there and it works fine

**Comment by jgyates** [comment]
@griffths yes that is correct

@TopBanana123 , I am working on your issue now

**Comment by TopBanana123** [comment]
Thanks @jgyates 

You have no idea how much better this software makes a generator (Well, you probably do)

**Comment by griffths** [comment]
Thank you both for the speedy confirmation of my modifications.

Don't have the HAT yet so no CT's for Genmon to display:  Is this why no gauges are showing on Status page for me?

**Comment by jgyates** [comment]
yes

**Comment by griffths** [comment]
Thanks again for your guidance.

**Comment by jgyates** [comment]
I am going to close this issue but feel free to post here if you have related questions.
