### ISSUE TITLE
Determining monitor version of my Generac

### ISSUE THREAD

**Issue by xybertech** [jgyates/genmon#647]
![image](https://user-images.githubusercontent.com/59705732/149460764-9084d844-82d9-473c-9791-7c42bea4181f.png)

My Generac Model: Model 04390-1
15 KW (has electrical upgrade kit) running on Propane
I installed mine in 2006 but I am not sure of the name of the monitor type. I attached an image from my repair and diagnostic manual. It is pretty basic, but has a terminal block with some monitor data. Here it is:
![image](https://user-images.githubusercontent.com/59705732/149464313-556f4076-49ae-4e1f-911d-76158a5484ff.png)

I could not find a name mentioned, is it one that you have supported?
If not I will probably have to start from scratch, or use your design as a starting point. It should be straight forward to read the status of the lights or defined values.

Your project is quite good and I have thought about doing this for a while, but I am glad to see you have went down that path already.

**Comment by jgyates** [comment]
@xybertech, Unfortunately this generator is not supported. This project acquires data from the generator via the serial port and this unit does not appear to have a serial port.

**Comment by xybertech** [comment]
I will probably just tap into the wires, terminal or use a light sensor to read the status of each of the led lights and any appropriate parameter from the terminals and a current/charge sensor for the battery so I have some data. I wont be as nice as yours, but I will have the basics.

**Thank you for taking a look and responding so fast. You did a great job on this project and the documentation is quite good as well.**
