### ISSUE TITLE
Switching to USB Wifi- Cheatsheet request

### ISSUE THREAD

**Issue by Don331** [jgyates/genmon#653]
I have a new raspberry Pi 3 with the hat, I need to change to a USB wifi adapter so I can use an external antenna. I have the Wireless-N USB adapter as it seems popular with the group.
My question is does anyone have a doc with the steps to install and configure it for GenMon?

**Comment by jgyates** [comment]
There are a few articles on this topic, here are a couple:

https://www.lifewire.com/usb-wifi-adapter-raspberry-pi-4058093
https://www.seeedstudio.com/blog/2021/01/25/three-methods-to-configure-raspberry-pi-wifi/
