### ISSUE TITLE
Configuring USB WiFi - EASY WAY

### ISSUE THREAD

**Issue by Don331** [jgyates/genmon#654]
This give detail on how to change to an external USB Wifi device so you can use an external antenna.

- The test platform is a preloaded Raspberry PI 3A+ with Hat from Pintsize.me
- The Pi was **already configured** using the internal wifi and working fine. (This is typically the point where you realize you need an external antenna)
- A  Mideatek RT5370N Wireless-N USB Adapter from Amazon was used as other posts referred to it as already working on this model.

The internal wifi by default comes up as WLAN0. Plug in the external and it comes up as WLAN1. 

There are multiple articles on the WWW, but none seems to exactly fit the use case here - too complex.

**Here's the simple solution:** Disable the built-in WiFi. By doing this, the USB Wifi will come up as WLAN0, and no other WLAN interfaces will be active. You will not have to change any other settings, as they are already set up for WLAN0.

**STEPS:**
You can open a terminal, connect via SSH, or edit the file directly on the SD card from your computer
Open the config.txt file with nano:
   **sudo nano /boot/config.txt**

Find the following line:
    # Additional overlays and parameters are documented /boot/overlays/README

And add these two lines **under** it:
   **dtoverlay=disable-wifi
   dtoverlay=disable-bt**

(The second line is to disable the Bluetooth module)
    **Save and exit (CTRL+O, CTRL+X)**
**Power off the Pi, insert the USB Wifi and power up.** 

Note: If you've reserved an IP address already for your PI, the will not be working as the MAC address has changed. It should get a new address from DHCP. You'll need to make a new IP address reservation for the new MAC.

**Comment by jgyates** [comment]
This is great info. Thanks! I added it to the wiki here:

https://github.com/jgyates/genmon/wiki/Appendix-M-Tips-and-Tricks-useful-for-Genmon#configuring-usb-wifi-on-a-raspberry-pi
