### ISSUE TITLE
Genmon triggering deprecated kernel logging

### ISSUE THREAD

**Issue by lps-rocks** [jgyates/genmon#666]
### Expected Behavior

No Logging Errors

### Actual Behavior

<pre>Feb  4 16:53:16 genmon kernel: [  127.364728] ------------[ cut here ]------------
Feb  4 16:53:16 genmon kernel: [  127.364757] WARNING: CPU: 3 PID: 474 at drivers/firmware/raspberrypi.c:233 get_throttled_show+0x6c/0x70
Feb  4 16:53:16 genmon kernel: [  127.364768] deprecated, use hwmon sysfs instead
Feb  4 16:53:16 genmon kernel: [  127.364778] Modules linked in: sha256_generic cfg80211 rfkill 8021q garp stp llc bcm2835_codec(C) v4l2_mem2mem bcm2835_v4l2(C) bcm2835_isp(C) bcm2835_mmal_vchiq(C) videobuf2_dma_contig videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 snd_bcm2835(C) videobuf2_common raspberrypi_hwmon snd_pcm videodev snd_timer mc snd vc_sm_cma(C) rpivid_mem uio_pdrv_genirq uio nvmem_rmem drm drm_panel_orientation_quirks backlight fuse ip_tables x_tables ipv6
Feb  4 16:53:16 genmon kernel: [  127.365237] CPU: 3 PID: 474 Comm: python3 Tainted: G         C        5.10.63-v7l+ #1488
Feb  4 16:53:16 genmon kernel: [  127.365243] Hardware name: BCM2711
Feb  4 16:53:16 genmon kernel: [  127.365251] Backtrace:
Feb  4 16:53:16 genmon kernel: [  127.365274] [<c0b83534>] (dump_backtrace) from [<c0b838c8>] (show_stack+0x20/0x24)
Feb  4 16:53:16 genmon kernel: [  127.365284]  r7:ffffffff r6:00000000 r5:60000013 r4:c12e6b3c
Feb  4 16:53:16 genmon kernel: [  127.365297] [<c0b838a8>] (show_stack) from [<c0b87cb4>] (dump_stack+0xcc/0xf8)
Feb  4 16:53:16 genmon kernel: [  127.365311] [<c0b87be8>] (dump_stack) from [<c0220b10>] (__warn+0xfc/0x114)
Feb  4 16:53:16 genmon kernel: [  127.365321]  r10:c33efef8 r9:00000009 r8:c09bce68 r7:000000e9 r6:00000009 r5:c09bce68
Feb  4 16:53:16 genmon kernel: [  127.365328]  r4:c0ea16d8 r3:c1205094
Feb  4 16:53:16 genmon kernel: [  127.365339] [<c0220a14>] (__warn) from [<c0b8406c>] (warn_slowpath_fmt+0xa4/0xd8)
Feb  4 16:53:16 genmon kernel: [  127.365347]  r7:000000e9 r6:c0ea16d8 r5:c1205048 r4:c0ea16b0
Feb  4 16:53:16 genmon kernel: [  127.365358] [<c0b83fcc>] (warn_slowpath_fmt) from [<c09bce68>] (get_throttled_show+0x6c/0x70)
Feb  4 16:53:16 genmon kernel: [  127.365367]  r9:c33b7e00 r8:c19b2210 r7:c28a7000 r6:c0c4d71c r5:c19b8c40 r4:c28a7000
Feb  4 16:53:16 genmon kernel: [  127.365381] [<c09bcdfc>] (get_throttled_show) from [<c0848848>] (dev_attr_show+0x28/0x54)
Feb  4 16:53:16 genmon kernel: [  127.365388]  r5:c131f4e8 r4:c283ef00
Feb  4 16:53:16 genmon kernel: [  127.365402] [<c0848820>] (dev_attr_show) from [<c04f6854>] (sysfs_kf_seq_show+0x98/0x100)
Feb  4 16:53:16 genmon kernel: [  127.365410]  r5:00001000 r4:c283ef00
Feb  4 16:53:16 genmon kernel: [  127.365421] [<c04f67bc>] (sysfs_kf_seq_show) from [<c04f48cc>] (kernfs_seq_show+0x34/0x38)
Feb  4 16:53:16 genmon kernel: [  127.365431]  r9:00000001 r8:00000000 r7:00400cc0 r6:7ffff000 r5:00001001 r4:c283ef00
Feb  4 16:53:16 genmon kernel: [  127.365443] [<c04f4898>] (kernfs_seq_show) from [<c046b11c>] (seq_read_iter+0x1a0/0x4ec)
Feb  4 16:53:16 genmon kernel: [  127.365455] [<c046af7c>] (seq_read_iter) from [<c04f4f48>] (kernfs_fop_read_iter+0x140/0x188)
Feb  4 16:53:16 genmon kernel: [  127.365464]  r10:c33efee0 r9:00000000 r8:00000000 r7:c33efef8 r6:00001001 r5:c38adcc0
Feb  4 16:53:16 genmon kernel: [  127.365470]  r4:c33b7e00
Feb  4 16:53:16 genmon kernel: [  127.365482] [<c04f4e08>] (kernfs_fop_read_iter) from [<c043e25c>] (vfs_read+0x218/0x344)
Feb  4 16:53:16 genmon kernel: [  127.365491]  r10:c33eff58 r9:00000000 r8:00000000 r7:c1205048 r6:00001001 r5:c38adcc0
Feb  4 16:53:16 genmon kernel: [  127.365497]  r4:00000000
Feb  4 16:53:16 genmon kernel: [  127.365506] [<c043e044>] (vfs_read) from [<c043e854>] (ksys_read+0x68/0xe0)
Feb  4 16:53:16 genmon kernel: [  127.365515]  r10:00001001 r9:b2105e30 r8:c38adcc0 r7:00000000 r6:00000000 r5:c38adcc3
Feb  4 16:53:16 genmon kernel: [  127.365522]  r4:c1205048
Feb  4 16:53:16 genmon kernel: [  127.365531] [<c043e7ec>] (ksys_read) from [<c043e8e4>] (sys_read+0x18/0x1c)
Feb  4 16:53:16 genmon kernel: [  127.365540]  r10:00000003 r9:c33ee000 r8:c0200204 r7:00000003 r6:00001001 r5:b06fd900
Feb  4 16:53:16 genmon kernel: [  127.365547]  r4:0000000e
Feb  4 16:53:16 genmon kernel: [  127.365558] [<c043e8cc>] (sys_read) from [<c0200040>] (ret_fast_syscall+0x0/0x28)
Feb  4 16:53:16 genmon kernel: [  127.365565] Exception stack(0xc33effa8 to 0xc33efff0)
Feb  4 16:53:16 genmon kernel: [  127.365574] ffa0:                   0000000e b06fd900 0000000e b2105e30 00001001 00000000
Feb  4 16:53:16 genmon kernel: [  127.365583] ffc0: 0000000e b06fd900 00001001 00000003 0000000e 0049be68 0049be30 0049be38
Feb  4 16:53:16 genmon kernel: [  127.365591] ffe0: 00000000 b06fbde8 00000000 b6ee8f6c
Feb  4 16:53:16 genmon kernel: [  127.365600] ---[ end trace 691c3be39817ee34 ]---
</pre>

### Steps to Reproduce (including precondition)

Run genmon on any raspberry Pi with Linux kernel 4.19 or newer and without vcgencmd installed. Newr versions of raspbian no longer come with vcgencmd since the native kernel hwmon driver exists now.

**Comment by jgyates** [comment]
This PR has been incorporated with some changes to maximize compatibility with older distros. Thanks for this,
