### ISSUE TITLE
Notification 

### ISSUE THREAD

**Issue by andrewvanlagen** [jgyates/genmon#671]
Hi
How can I get notifications
I like to get sms or email 

Thanks

**Comment by jgyates** [comment]
There are two steps to get email notifications.

1) Setup the ability for genmon to send emails. This is done on the Settings page. Under "Optional - Outbound Email Settings". If you enter your email server information in this section you will enable the genmon software to send emails.
2) Specify an email recipient. To do this you enter the email address to send notifications in the "Notifications" page.

To send SMS messages there are a few options. Any one of these will work to send SMS notices:
1) Create a twilio account and use the "Notifications via SMS - Twilio" add on from the Add on page.
2) Enable the "Mobile Carrier Email to SMS" add on from the Add On page. This requires step 1 in the email setup above to be completed first.
3) Purchase a cellular HAT for the pi and enable the "Notifications via SMS - LTE Hat" add on from the Add On page. This requires purchasing hardware and cell service.

Other notifications methods:
1) Pushover (enabled via the Add On page
3) Slack (enabled via the Add On page

**Comment by andrewvanlagen** [comment]
Thanks

**Comment by andrewvanlagen** [comment]
i got pushover to work. 
it there free option to use

**Comment by jgyates** [comment]
Other than the one time purchase of the mobile app, pushover is free for personal use.
 
The options listed above that use email (including the email to SMS via your existing carrier) are free.
