### ISSUE TITLE
GPIO Output Add-on not working

### ISSUE THREAD

**Issue by sambeetm** [jgyates/genmon#681]
Hi..Is the GPIO Output add-on broken ? Its not working anymore. Not sure since when though. It only lights-up READY Led and does not change with other statuses (like exercising, running, off etc). It used to work perfectly. I looked into the processes and /home/pi/genmon/gengpio.py is up and running. In the /var/log/gengpio.log is 0 byte. Any other way to debug ?

I tested all the GPIO pins triggering low-high from PI(using a simple .py program) and all are responding. So, no wiring issues.

Thanks

**Comment by jgyates** [comment]
Hi @sambeetm 

Apparently yes. Thanks for pointing this out. I checked in a fix (version number did not change) so just update your software from the about page. Let me know if you have any issues.

Thanks

**Comment by sambeetm** [comment]
Thanks for the fix. Working as expected now.....!!

**Comment by jgyates** [comment]
Nice setup with your pi and LEDs

**Comment by sambeetm** [comment]
@jgyates what is the condition for "Internet Connection GPIO 3" to stay high ? After a day of working fine, this light is turning on. I checked  1) genserv is up and accessible from outside 2) PI can access internet.

**Comment by jgyates** [comment]
The software attempts to make a HTTP connection to google.

https://github.com/jgyates/genmon/blob/768d5e4c01a01bffeb88bfe080b0463dfc55cbc1/genmonlib/myplatform.py#L424

**Comment by jgyates** [comment]
I found one more bug that probably effects this. I checked in the change so just update from the about page. Sorry about that.

**Comment by sambeetm** [comment]
Thanks !! its gone for now. I will monitor for few days and let you know if there are any more findings...
