### ISSUE TITLE
No graph UI when you go to the home screen...  Help

### ISSUE THREAD

**Issue by kd5bwp** [jgyates/genmon#684]
GenMon will not show graph...  New to this system...  Power cycled the device tried checking Disable power/ current display setting was working then stopped...

Console shows this.
![image](https://user-images.githubusercontent.com/101480992/158036357-8d742ae3-720a-4bc3-a83b-450446870da0.png)

![image](https://user-images.githubusercontent.com/101480992/158036293-d21500d1-ae15-4b50-8b3d-3be96df0838f.png)

![image](https://user-images.githubusercontent.com/101480992/158036305-89ec229d-ceb0-4949-8495-f966c83cf527.png)

![image](https://user-images.githubusercontent.com/101480992/158036311-55a3456a-f0e7-40ea-8188-ae8b82857e03.png)

![image](https://user-images.githubusercontent.com/101480992/158036322-5419e4be-84eb-4f79-853a-1b27b6d04d16.png)

**Comment by jgyates** [comment]
There is a lot of information missing so I can not really provide much but some guesses. 

What model generator?
Is genmon communicating with the controller? Add ons will not function if communications are not active.
Log files were not submitted.

The errors on the console you pictured above appear to be from a chrome extension, not from genmon.

If your serial comms are not working then it would be expected that the graph would not show up. The gauges will not show not show up if genmon has not finished initializing, which will take a lot longer if serial comms are not working. 

check the Monitor page, you should see something like this 
<img width="451" alt="CommStats" src="https://user-images.githubusercontent.com/4513286/158041678-4876864c-2c7c-42cb-815e-e18009433f7f.png">

Also, when you say "New to this system" I do not know what you mean. Are you saying that you are new to the raspberry pi or are you saying that genmon is newly installed on this system.

**Comment by kd5bwp** [comment]
Thank you for the fast response I'm new to this Genmon setup.  The graphs came back when I plugged in the phat to the evo controller.  I was just setting up the device and see that I had graphs and then they disappeared and when I first plugged it into the gen the graphs on the home page didn't show up for a bit.  But now they do.  
The model of the generator is a RD02023 with Firmware 1.  It's a 20kw Diesel.

The only other question is how does the fuel gauge work?  Is this just a estimate?  It does have a fuel gauge and over limit alarm with low cut off built into the unit but currently only have a little under a half and not full.

![image](https://user-images.githubusercontent.com/101480992/158044658-b5cee68f-99d9-43d2-9a5f-68a1cad770ee.png)

On the email I tired a few setting and wasn't able to get my email to work...  Tried a few combinations with ssl on and off.

![image](https://user-images.githubusercontent.com/101480992/158044723-44f57876-8408-40eb-886b-2573f8c54cf3.png)

**Comment by jgyates** [comment]
There is a fuel estimate gauge however for Evolution Diesel units there is a fuel gauge sensor built in. To enable it turn on the "Use Sensor for Fuel Gauge" on the settings page (this option only shows up on Evolution Liquid cooled models with diesel fuel).

Regarding you email question, did you install via the genmonmaint.sh script? The "WRONG_VERSION_NUMBER" indicates you may have an issue with your installation.

For email username and passwords, it depends on the type of email account you are using (gmail, Microsoft, etc). This section in the wiki has info related to email setup: https://github.com/jgyates/genmon/wiki/1----Software-Overview#configuring-mymailpy

All of the settings can be controlled by the web interface, however you either need to have either a "app specific" password or use "less secure app" settings with your email provider. The link above has more details on this.

Let me know if you have additional questions.

**Comment by jgyates** [comment]
Also, you show the CT Hat add on in your above pictures. Do you have the CT Hat installed?

**Comment by kd5bwp** [comment]
Yes I have the CT hat installed.

**Comment by jgyates** [comment]
Did you install via the genmonmaint.sh script?

**Comment by kd5bwp** [comment]
Not sure. Can I run it?

**Comment by jgyates** [comment]
I am a little concerned about your last answer. How did you come to have genmon installed on this raspberry pi? The answer to this is dependent on what we do next. If you are not sure then I would suggest that you start over with the instructions on this page:

https://github.com/jgyates/genmon/wiki/3.3--Setup-genmon-software

**Comment by jgyates** [comment]
in addition, there is an additional step described on this link:

https://github.com/jgyates/genmon/wiki/1----Software-Overview#gencthatpy-optional

that is needed for setting up the CT Hat. If you have not modified the file /boot/config.txt as described then the CT Hat will not work. This would need to be done after the install process.
