### ISSUE TITLE
secure login needs python-openssl installed

### ISSUE THREAD

**Issue by MolallaComm** [jgyates/genmon#69]
The wiki docs are generally excellent but should probably mention "sudo apt-get install python-openssl" in both the documentation and the genmon.conf if using HTTPS for the web interface.  It might also be worth mentioning that HTTPS is required to enable the login/password functionality (I figured it out from looking at the code).

**Comment by jgyates** [comment]
Thanks! I added this to the wiki and the comment in genmon.conf.
