### ISSUE TITLE
rpirtscts error in genmonmaint.sh script

### ISSUE THREAD

**Issue by jlhaggerty** [jgyates/genmon#694]
I'm just getting started with genmon.  I cloned the genmon git repo and ran `./genmonmaint.sh -i`  It throws the following error when cloning the rpirtscts

```
Installing rpirtscts...
~/genmon ~/genmon
Cloning into 'rpirtscts'...
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
./genmonmaint.sh: line 118: cd: rpirtscts: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
cp: cannot stat './rpirtscts': No such file or directory
Finished installing rpirtscts.
```

I was able go fix this by updating the genmonmaint.sh script on line 117

before
`git clone git://github.com/mholling/rpirtscts.git`
after
`git clone https://github.com/mholling/rpirtscts.git`

I reran the script and had no problems.  I hope that helps!

**Comment by jgyates** [comment]
Thanks!

I checked in a change that corrects this issue.
