### ISSUE TITLE
Web based control

### ISSUE THREAD

**Issue by griffths** [jgyates/genmon#7]
I see that your solution allows remote control of the genset through email and command line only.  Would it be possible for you to add this functionality to the web interface?

Regards,

Jay

**Comment by jgyates** [comment]
Wow, I must be physic. I just checked that in earlier today. The 1.2.0 (and master) tagged release supports the remote commands via the web interface.

**Comment by griffths** [comment]
Thanks and I apologize for not looking at the most recent codebase before submitting a request

Jay

**Comment by jgyates** [comment]
No problem. I am sorry I can't spell psychic. I mispelled it in the first response. :). Let me know if you have any other questions.
