### ISSUE TITLE
Feature request: SNMP V2c support with bulkwalk

### ISSUE THREAD

**Issue by w-u-2-o** [jgyates/genmon#705]
Shameless feature request: please expand SNMP support for V2c and bulkwalk requests.

Reason: Checkmk ([https://checkmk.com/](https://checkmk.com/)) network monitoring system does not support MIB files, preferring to simply do a bulkwalk of V2c and V3 SNMP services. This is the future, so they say.

Checkmk does support pseudo bulkwalk over V1, but even that does not work with genmon (see: [https://docs.checkmk.com/latest/en/snmp.html#_when_devices_create_problems](https://docs.checkmk.com/latest/en/snmp.html#_when_devices_create_problems)

Thanks for all you do!

**Comment by jgyates** [comment]
I will add this to the list.

https://github.com/jgyates/genmon/blob/master/feature_requests.md

I will update this thread when this feature is added.
