### ISSUE TITLE
Email Notification Error - please run connect() first

### ISSUE THREAD

**Issue by bmg01907** [jgyates/genmon#708]
I recently upgraded to v1.18.11 with your help.  Everything seems to be running fine except that email notifications aren't working.  When I select the "Test Email Settings" button I receive an error that says, "please run connect() first" as shown in the screenshot below.

What's the fix for this?
![Email Error](https://user-images.githubusercontent.com/66648374/167312228-d07d0d62-89ae-4345-8603-2e59369364cb.JPG)

**Comment by jgyates** [comment]
I would need more info to give you anything other than a guess. 

1) Make sure you are either using "less secure apps" (which is going away with gmail at the end of the month) or for a longer term solution, use two factor authentication and "app specific passwords" (https://github.com/jgyates/genmon/issues/682)
2) look at /var/log/mymail.log and see if there are are errors and post them here. 
3) also, without knowing your settings like  SMTP Server Port, Use SSL Encryption, Disable TLS Encryption, Disable SMTP Auth it is difficult to say. Also know if this is gmail account or some other type would be helpful.
4) Are there any unusual non ASCII characters in your server address, email address or password (e.g. unicode characters)

**Comment by bmg01907** [comment]
Thanks for your reply.  My answers:

1. I'm not using Gmail.  I'm sending email through my own domain name that's managed by Network Solutions.
2. I've attached the mymail.log file.
3. The attached screenshot shows the email settings in Genmon.  They're identical to what worked in the prior version of Genmon that I was running without any issues.  They're consistent to the settings that work in my email client (Outlook).
4. There are no unusual non ASCII characters in use.

![Email Settings](https://user-images.githubusercontent.com/66648374/167313321-ddae297f-724d-4129-9715-b8dd47367f94.JPG)
[mymail.log](https://github.com/jgyates/genmon/files/8647677/mymail.log)

**Comment by bmg01907** [comment]
Thanks for your reply.  My answers:

1. I'm not using Gmail.  I'm sending email through my domain name that Network Solutions manages.
2. I've attached the log file.
3. The attached screenshot shows the email settings.  They're identical to what I used in the prior version of Genmon that worked without any issues.  They're similar to the settings in my email client (Outlook).
4. There are no unusual non ASCII characters in use.

[mymail.log](https://github.com/jgyates/genmon/files/8647683/mymail.log)
![Email Settings](https://user-images.githubusercontent.com/66648374/167313500-800318aa-cc15-4506-ab02-64e55ae4a797.JPG)

**Comment by jgyates** [comment]
The first error in your log file is this:

Error SMTP Init : SSL:<False>: [Errno -3] Temporary failure in name resolution : mymail.py:501

this occurs when the software is trying to connect to your SMTP server. Can you ping the server you specify in the SMTP Server setting form the pi console?

**Comment by jgyates** [comment]
FYI the second error in your log file is:

Error SMTP sendmail: (451, b'See http://pobox.com/~djb/docs/smtplf.html.') : mymail.py:527

The "451" above denotes " Temporary local problem - please try later"

You can google "error 451 email" for details. Can you send email with another client using this account?

**Comment by bmg01907** [comment]
I pinged the SMTP server from the console.  There doesn't appear to be any issue; see the attached screenshot.

I sent an email using Outlook from the "notifications" account without any problem.  It was received intact.

![Ping from Console](https://user-images.githubusercontent.com/66648374/167314871-0bb6deea-9ce0-410f-b357-b48d957c9aa4.JPG)

**Comment by jgyates** [comment]
what is the output of this command:

     cat /etc/os-release

If you still have the operating system from your previous install then try this to give us an additional data point:

      cd genmon
       ./startgenmon.sh -p 2 restart

This should restart genmon forcing python 2 instead of python 3. Then see if your email is working. If this works then it will give more info as to the source of your issue. Your email settings are not really that common (no SSL, no TLS) so it is possible that this has not been tested with python3.

**Comment by bmg01907** [comment]
Success.  Email is now working with Python 2.  See the attached screenshot.

Is there a fix for this so I can use Python 3?

![Cat os-release Python 2](https://user-images.githubusercontent.com/66648374/167315559-b06cdd16-87ce-4e0c-bf26-cf69a3b954fa.JPG)

**Comment by jgyates** [comment]
No, this is an issue I have not seen before. I have an idea of how to fix it but implementing is tricky as I am concerned that this would break email for others. I will need to think about this and possibly get you to run some tests. 

Is this an email server that you maintain? If so can you provide a test email account that I can test with until I get a fix? If not then I would need you to test any possible fix.

**Comment by jgyates** [comment]
I checked in a version that may fix this issue. First, restart using python 3

    cd genmon
    ./startgenmon restart

Then go to the About page in the web interface and update the software. When the software restarts after the update then let me know if this corrects the issue.

**Comment by jgyates** [comment]
Also, the version number has not been updated.

**Comment by bmg01907** [comment]
Done.  I restarted using Python 3 (see attached screenshot) and updated Genmon from the About page.  I then selected "Test Email Settings" and received the test email as well as the Genmon startup email.  It appears that you fixed it.  Much appreciated.

FYI - I can enable SSL and TLS if necessary.

Thanks for your help.  Let me know if you need me to do any testing for you.
![Restart Python 3](https://user-images.githubusercontent.com/66648374/167316444-3216eca7-f963-48bf-93d2-df573f4974db.JPG)

**Comment by jgyates** [comment]
If you could test with SSL and TLS, that would be helpful. Also send your logs on the about page to make sure everything is running as expected. Thanks

**Comment by bmg01907** [comment]
Email stopped after turning on SSL and TLS.  Test Email Settings generates an error.  See the attached screenshots.

Logs sent from the About page.

![SSL-TLS On](https://user-images.githubusercontent.com/66648374/167317810-9a6358c1-7477-4b1a-89e3-0a41c0aff52a.JPG)
![SSL-TLS Error](https://user-images.githubusercontent.com/66648374/167317820-1d906c1f-40a5-4a24-bf5e-37272a44a602.JPG)

**Comment by jgyates** [comment]
Based on this I would say that your issue is that either your mail server is misconfigured (less likely) or your ssl libaries on your pi are messed up. What is the output of this command:

       pip3 freeze

and this command


       pip freeze

**Comment by bmg01907** [comment]
pip3 and pip screenshots attached.

I don't manage the email server.  Network Solutions handles that.  Accordingly, I assume that it's configured correctly.

FYI - I turned off the SSL and TLS settings in Genmon.  The emails are working again.

![Pip3 Freeze](https://user-images.githubusercontent.com/66648374/167320353-43ed2de9-9fa1-4467-bbed-6939b4acc451.JPG)
![Pip Freeze](https://user-images.githubusercontent.com/66648374/167320359-f43133fd-a783-44ed-be96-376d3fa68c81.JPG)

**Comment by jgyates** [comment]
Let's try updating your pip libraries that genmon uses. Type this:

    cd genmon
    ./genmonmain.sh -r


Have you installed any other software on the pi?

**Comment by bmg01907** [comment]
I haven't installed any other software on the RPi.

Your command above generates an error; see the attached screenshot.

![Genmonmain error](https://user-images.githubusercontent.com/66648374/167321386-afa52a4e-9cc2-4ba1-b01c-329562bd15bc.JPG)

**Comment by jgyates** [comment]
sorry for the typo:

       cd genmon
       ./genmonmaint.sh -r

**Comment by bmg01907** [comment]
Done.  Three screenshots attached.

![Genmonmaint 1](https://user-images.githubusercontent.com/66648374/167321678-ca76fe7d-6665-44fe-bd86-3d59a569685b.JPG)
![Genmonmaint 2](https://user-images.githubusercontent.com/66648374/167321684-ad0b33c6-80fa-4856-85d1-3b2a37d806ce.JPG)
![Genmonmaint 3](https://user-images.githubusercontent.com/66648374/167321691-5e44609b-59f4-4869-b143-aecea27f98a9.JPG)

**Comment by jgyates** [comment]
it is strange that you are getting the name resolution error like the one in your mymail.log file.

Did this allow you to send email with SSL or TLS?

If it did not then I would suggest a few other things:

1) Try upgrading your pi to Bullseye from Buster. You are currently running buster but bullseye is the latest. Instructions are here:

https://www.tomshardware.com/how-to/upgrade-raspberry-pi-os-to-bullseye-from-buster


2) reinstall a fresh copy of the operating system and reinstall genmon. Use this guide to install genmon:

    https://github.com/jgyates/genmon/wiki/3.3--Setup-genmon-software

you can restore your settings from your backup files.

I have seen this happen on rare occasions in the past (encryption libraries have a strange dependency problem that makes an SSL version error). Unfortunately there are quiet a few python modules that use these (smtplib, flask, basically anything that uses HTTPS or sends mail in python) and tracking this down can be time consuming so the easiest path is to just reinstall the OS.

Once you get everything backup an running test your email with your original settings. I am going to backout the last update as I am not convinced yet that this is the right change to make. If you still have an issue with non SSL and non TLS email I can put it back in.

Let me know how it goes of if you have questions.

**Comment by bmg01907** [comment]
Thanks.  Emailing with SSL and TLS on won't work after the pip update; see the attached screenshot.  Emailing works with SSL and TLS off.  I'll leave them off for now.
![After pip update](https://user-images.githubusercontent.com/66648374/167322973-87569e10-3360-4f35-8e16-45cd4677b821.JPG)


I'll try the steps that you described above and report back in the next couple of days.

I appreciate your help.

**Comment by bmg01907** [comment]
Thanks.  I haven't had a chance to upgrade the RPi OS and reinstall Genmon.  I'll post a report here about that as soon as I've done so.
