### ISSUE TITLE
Question. Upgrade

### ISSUE THREAD

**Issue by usmc124** [jgyates/genmon#71]
How do I upgrade from the current version to V1.4.1.  I have been replacing the updated files individually up till this point but assuming their is a way to upgrade the whole package.  Barely know enough about python to be dangerous.

**Comment by jgyates** [comment]
I have received this question a few times so it prompted me to write a wiki page about this:

https://github.com/jgyates/genmon/wiki/Updating-to-the-Latest-Version

Let me know if you have any questions.

**Comment by usmc124** [comment]
Perfect- exactly what I was looking for.  I found numerous methods to update the package but each followed with 25 entries of people disagreeing or offering alternative methods.  I figured I should go to the experts.  Thank you!
