### ISSUE TITLE
Multi-Instance SNMP Support

### ISSUE THREAD

**Issue by jf5264835** [jgyates/genmon#712]
I was looking to see if it would be possible to add a setting for binding the SNMP port on a per instance basis, as either part of the genmon.conf file, or the gensnmp.conf file? Today I have to make not only a second folder of config files per instance, but also a second folder with the git library in it, and between 2 instances I am having to change line 483 in gensnmp.py from

`udp.domainName, udp.UdpSocketTransport().openServerMode(('0.0.0.0', 161))`

to

`udp.domainName, udp.UdpSocketTransport().openServerMode(('0.0.0.0', 163))`

and while this works, if there was a way to just set a port number within a config file so only one gen.py library needs to be executed from, it would help cleanup my setup.

Thanks for making this library!

**Comment by jgyates** [comment]
I checked in an update that will allow you to add a parameter named 'snmpport' to /etc/genmon/gensnmp.conf like this:

     snmpport=163

Let me know if you have any issues. The version number has not been updated.
