### ISSUE TITLE
SiteName Change

### ISSUE THREAD

**Issue by usmc124** [jgyates/genmon#72]
I have changed the option sitename=SiteName to the sitename I want in genmon.conf.  However email notifications and web page still shows sitename=SiteName.  Does this need to be changed somewhere else as well?

**Comment by jgyates** [comment]
Hi @usmc124 
You need to make sure that you are editing the version of genmon.conf in the /etc/ directory and you also need to make sure you restart genmon.py after making the change. Let me know if you have any other questions.

Jason

**Comment by usmc124** [comment]
got it.  I was not modifying the right one.  thx.
