### ISSUE TITLE
(non-issue) non-minimized libraries.js

### ISSUE THREAD

**Issue by StuartRothrock** [jgyates/genmon#720]
Is there a chance of getting the non-minimized versions of the libraries.min.js and libraries.min.css files? Thanks!

**Comment by StuartRothrock** [comment]
Thank you @jgyates - I should have assumed all was included and just look a little further before posting. I am impressed with your coding style and python knowledge. Is your bio posted anywhere? I am curious about your background. I have been in enterprise IT for 30 years and have seen the good and the bad.

**Comment by jgyates** [comment]
Hi @StuartRothrock, Thanks for the kind words. No bio, but I started coding around 1990 with x86 assembly, then moved on to C around 1992. I started using python for projects around the house around 2011. Most of my experience is centered around low level interfacing (device drivers, firmware and embedded systems).

**Comment by StuartRothrock** [comment]
Hey me too on the x86 assembler - had the ibm pc hardware reference and of
course Peter Norton's book. Back in the ugly TSR days. What was it 0 I may
have forgotten the handiest of all - Bios Int 21h  - Thanks for sharing.

**Comment by jgyates** [comment]
Ah, memories...Ray Duncan's Advanced MS-DOS Programming was the book always in arms length back then, i think.

https://www.amazon.com/Advanced-MS-DOS-Programming-Microsoft-Programmers/dp/1556151578
