### ISSUE TITLE
Possible Bug when disabling platform stats

### ISSUE THREAD

**Issue by liltux** [jgyates/genmon#723]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below. This is a template so feel free to remove any of this text. Try to include the info below when applicable.

***NOTE:*** If you are having issues with your serial connection, please read this page before posting:

https://github.com/jgyates/genmon/wiki/3.6---Serial-Troubleshooting

If you are having other issues, please see the following page:

https://github.com/jgyates/genmon/wiki/3.5---General-Troubleshooting

You can search past issues by removing the "is:open" keywords from the search window and adding any keywords that are relevant to your issue.

If you need to send you logs and registers to the developer, if your email is setup and working properly you can click send your logs on the About page in the web interface.

**Not connected to Internet**

**Selected Disable Platform Stats under the Advanced page
When this was done on restart the webui would never load just spin its wheel.  In the genmon.log I had this entry:**

> 2022-06-21 13:36:39,432 : Error in GetStartInfo: 'NoneType' object has no attribute 'IsOSLinux' : generac_evolution.py:4004

**When I Enabled Platform Stats or made it False in the genmon.conf file, when I restarted Genmon the error did not occur. 
I am not sure where the problem lies, as I did not look that deep into it, just wanted to share what I found.**

### Steps to Reproduce (including precondition)

**Can toggle Disable Platform Stats On and Off (or True and False in the configuration file)
and the error would follow the change accordingly.**

### Screenshot or Pictures relating to the problem (if possible)

**Did not get a screenshot**

### Your Environment

- Generator Model: **N/A**
- Genmon Logs: **No Internet Connection**
- Genmon Version: **1.18.11**
- **Raspberry PI running latest Raspbian lite image**

**Comment by jgyates** [comment]
Good catch. I checked in V1.18.12 that should fix this issue.
