### ISSUE TITLE
Looking for the Modbus tables that you used.....

### ISSUE THREAD

**Issue by Bentnail** [jgyates/genmon#730]
Great software that you have written.  I have also been reading more about Genmon and I am scheduled for a Generac 24kW air cooled install in a week.  I work for Johnson Controls and do alot of Modbus integrations into our Metasys system.  With that being said I ave scoured the internet for modbus registeries for the Gaurdain systems and have found nothing.  In fact I have emailed and called Generac and was told that they were "Private" and they will not release them to the public.  I have modbus registery tables for their commercial products but none for the residential line.  SO i was wondering if they had given you a modbus registers of what they use??  

Now in my reading there was something I read about they are going to encrypt.  As far as I have seen in the industry there is no encryption out there for modbus.  Unless something has cropped up in the last 2 months, all my modbus integrations are working on sites around North America.  So encryption is interesting.  Now they could put a switch on the port and only allow that by turning it on by the installer.  

I read the fleet link that was given about encryption and i could see that for external or Cellular since those are a risk.  But you can not encrypt modbus as I know.  So wondering....

I also find that Generac is be crap heads about this.  I spend lots of money to have their system and in turn just give me an app that does, it is on or off and alarm.  Nothing else.  

Thank you again for your software and I am hoping that my genset does not have Generac being sissies over other writing integration of their system.

Thank you....

**Comment by jgyates** [comment]
I am going to close this issue for now but feel free to post to this thread if you have any related questions.
