### ISSUE TITLE
config files -  Question

### ISSUE THREAD

**Issue by rwskinner** [jgyates/genmon#731]
I noticed when I save settings in the web interface, I don't see those values in the config files located in the conf folder.
Are these being saved somewhere else so they aren't overwritten during an update?

I ask, because I want to turn off the https web login that I enabled by mistake, and It's off on the genmon.conf so I'm sure it's another config somewhere.

**Comment by jgyates** [comment]
The active config files are stored in /etc/genmon/. 

main conf file for genmon - /etc/genmon/genmon.conf
email related - /etc/genmon/mymail.conf
web server - /etc/genmon/genserv.conf

Each add on has it's own conf file in the same folder.

Let me know if you have any other questions.
