### ISSUE TITLE
Restoring From Backup

### ISSUE THREAD

**Issue by stellagits** [jgyates/genmon#732]
I am in the process of building a new debian genmon server. I have backed up my installation and log files from my previous server.

How do I use the back up .tar.gz files to restore the installation on the new server? Getting them there isnt the problem. It's what do I do with them once transfered.

**Comment by jgyates** [comment]
The wiki page for Tips and Tricks has this info:

https://github.com/jgyates/genmon/wiki/Appendix-M-Tips-and-Tricks-useful-for-Genmon#restoring-settings-from-a-backup

**Comment by stellagits** [comment]
Thanks @jgyates, I thought that it might be documented somewhere. My searches never turn up what I'm looking for.
