### ISSUE TITLE
A watchdog would be really a nice addition

### ISSUE THREAD

**Issue by acato** [jgyates/genmon#735]
This service is just amazing. The integration with pretty much anything is idiot-proof and the support superlative.
There is only one thing that I think is sorely missing: occasionally, the server goes on the fritz and stops serving some of the counters (I noticed the web server and the SNMP service being particularly flaky), and this is fixed easily with a good'ole reboot or restart.
It would be nice to have a service that monitors the availability of the monitoring site and restarts the service and/or the host when it becomes unavailable. This is particularly important for remote monitoring, when you can't just go and recycle the power by walking outside.

**Comment by jgyates** [comment]
I have added this to the feature request list.

https://github.com/jgyates/genmon/blob/master/feature_requests.md

I will update this thread once this is completed.

On a related note, I use Nagios to monitor both the web socket and SNMP. If I ever see an issue I use VPN to remotely restart. I can see how your request would be useful.
