### ISSUE TITLE
Power PI from Generator Controller

### ISSUE THREAD

**Issue by jonathanpisarczyk** [jgyates/genmon#74]
Hello Everyone,

I was curious if anyone has had success powering the PI using the generator controller connector as stated in the instructions? 

"alternate way to power your Pi is to take 5V and ground from the generator controller connector and power your Pi via the power and ground connections on the GPIO connector. The wiki page on making a cable has additional detials on the controller pinout."

If so can you please provide a wiring diagram? I'm not 100% sure how to connect molex power and ground to which GPIO pins on PI?  I'm using the RS232 9pin female with GPIO pins 04, 06, 08, 10. 

I'm guessing I could connect molex PIN1 (5V) to GPIO 02 (5V) 
and
molex PIN2 (ground) to GPIO 39 (Ground) 

If not I plan on using the usb style connector. 

Any comments apperciated.  What a great project and idea.  I love it.  Makes so much more sense than the 3g option.  I've got no cell signal where our generator is located.

**Comment by krisasmith** [comment]
I am powering my Pi though the GPIO. I am using PIN 2 & 14.

![image](https://user-images.githubusercontent.com/27901356/36500011-01fbc756-1711-11e8-923f-3d3a9798697b.png)

Black wire is ground and green wire is 5v both coming from the genset controller.
![image](https://user-images.githubusercontent.com/27901356/36500020-08a2b4b6-1711-11e8-8f56-eafa4d8bc2b9.png)

**Comment by jgyates** [comment]
Hi @jonathanpisarczyk 

This thread:

https://github.com/jgyates/genmon/issues/3

has some discussion on using 5V and GND from the controller connector. I personally have not done this but others who have used this forum have.

**Comment by jonathanpisarczyk** [comment]
Thanks @jgyates I missed thread #3... 
Also thanks @krisasmith 
I suspect you meant to say **Black wire is 5v and green wire is ground** both coming from the genset controller.  

I will try it out!

**Comment by krisasmith** [comment]
Yes - I had them backwards. I have updated the post.

**Comment by jonathanpisarczyk** [comment]
Picture of my new setup for anyone else starting out. 
![img_1346](https://user-images.githubusercontent.com/36710072/36503477-3ef691a4-171b-11e8-9870-94bc21f858c0.jpg)
![img_1347](https://user-images.githubusercontent.com/36710072/36503481-43d26680-171b-11e8-8a54-63fc4bc9891a.jpg)

**Comment by krisasmith** [comment]
That should do it, looks just like mine.

**Comment by UPS99** [comment]
I had tried this with an Evolution controller and found that everything worked, however the load of the Pi pulled the 5 volt line down to about 4.7 volts, which may put the Pi close to the edge of its operating range, and also could overheat a regulator or other component in the controller.

**Comment by jgyates** [comment]
That is a good data point. Thanks!
