### ISSUE TITLE
not receiving vtext email to text messages anymore

### ISSUE THREAD

**Issue by grsthegreat** [jgyates/genmon#750]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below. This is a template so feel free to remove any of this text. Try to include the info below when applicable.

***NOTE:*** If you are having issues with your serial connection, please read this page before posting:

https://github.com/jgyates/genmon/wiki/3.6---Serial-Troubleshooting

If you are having other issues, please see the following page:

https://github.com/jgyates/genmon/wiki/3.5---General-Troubleshooting

You can search past issues by removing the "is:open" keywords from the search window and adding any keywords that are relevant to your issue.

If you need to send you logs and registers to the developer, if your email is setup and working properly you can click send your logs on the About page in the web interface.

### Expected Behavior

text push from email notification
### Actual Behavior

VTEXT not working

### Steps to Reproduce (including precondition)

called Verizon. no longer supported

### Screenshot or Pictures relating to the problem (if possible)

{Please write here}

### Your Environment

- Generator Model: 2016 era 22 kw
- Genmon Logs: Submit via the About page
- Genmon Version: V1.18.13
- up until a week ago, i would receive an immediate text upon system change on the genmon. the emails always took 5-10 minutes to sync thru even though my phone is set to auto sync.
i have had VTEXT set up thru Genmon for several years, but when i called Verizon they told me they no longer support VTEXT and were surprised i was receiving pushes up to a week ago.

is there another system i can use to get push notifications on my verizon Samsung S8 phone?

**Comment by jgyates** [comment]
@grsthegreat 

There are a few options.

1) Use email notices. You get more info in email than short messages like txt from genmon.

2) Use Pushover.net. You can use pushover.net to push messages from genmon to your phone. You should first go to pushover.net and create an account. Once you create an account you will need to create an application ID from the web interface. You will also need an pushover user ID. With these two IDs you can setup the pushover genmon add on. Once this is done you can install the pushover mobile app on your android or apple phone. Pushover is free for individual use.

3) Use Twilio. This is a SMS service that has a free trial, but does have a cost associated with it. There is a genmon add on fir this as well.

I am going to close this issue for now as your question is answered however if you have additional questions feel free to post them to this thread.
