### ISSUE TITLE
Are historical service counters available anywhere?

### ISSUE THREAD

**Issue by skipfire** [jgyates/genmon#753]
Due to a lightning strike my Evo2 controller had to be replaced, so I lost my Service A & B counters.  Are historical values of those stored anywhere?  I didn't see them in any of the emails and I'm not sure where else they could be.

**Comment by jgyates** [comment]
Genmon does not record these value, it reads them over modbus. You could look at your service log to see the last service A event. The next service a should be 125 hours or one year after that. Service B is 250 hours or 2 years.

You could also look at your outgoing email that you use on the generator and see if your registers we ever submitted. Register 001a is hours until service A and register 001e is hours until service B.
