### ISSUE TITLE
A different install that worked

### ISSUE THREAD

**Issue by ralkire** [jgyates/genmon#765]
Generator: G0070423 20KW Evolution 2.0, Air Cooled

My installation uses genmon but the hardware is a bit different than what usually is recommended.

I used the 8 pin power supply cable StarTech EPS 8 Pin Power Extension Cable EPS8EXT from Amazon and spliced into the wires. This saved me from not having to crimp the connector.  This goes between the Evolution 2 controller and the WiFi unit. 

I used a small RS-232 to RS-422 converter (BASSO-101DS) inside the generator and is zip tied to the cable.  RS422 can reliably send and receive data over a long distance and fairly immune to noise. These can be powered from the 5V and don't draw much as they are often powered by an unused signal line like RTS. I used standard CAT6 cabling (about 70ft) and outdoor direct burial CAT6 (10ft) to the generator. I had to bring the wire through the propane line gasket - the generator is fairly tight, I guess to keep the rats out. 

On the other side of the RS422, having run out of Raspberry Pi, I used an Orange Pi Lite 3 running Armbian with a RS-422 to USB converter. (BASSO-1010UC). I first tried to use it on one of my servers but there were package conflicts that I didn't want to break. On Armbian, the software just came up and worked and only real issue was how the MQTT was done. It is legitimate MQTT but it sends raw data rather than JSON. Most of my infrastructure was set up for receiving JSON. It also uses a lot of topics rather than utilize the JSON structure. Still I got it to work and my house now tells me if the generator is running or not. Can't hear it otherwise and when the cloud stuff tells me, it is far too late. 

Thanks!

One more note. I set up my first service and the onsite firmware update was listed in the contract. Hopefully it doesn't break things.

Bob

**Comment by jgyates** [comment]
@ralkire 

Thanks for the feedback. It is useful to hear of folks using non pi hardware. To date I don't have any reports of people having issues with the latest Evo 2.0 firmware. I have seen register submissions of firmware up to version 1.15 for Evolution 2.0. Sounds like a nice setup.
