### ISSUE TITLE
Issue with Error Codes

### ISSUE THREAD

**Issue by buschauer** [jgyates/genmon#77]
Since version 1.40 (if I recall correct), I get unknown error codes on my Evolution controller. Before it was working fine. I think the problem is line 2549 in genmon.py. This only takes AlarmLogDecoder & NexusAlarmLogDecoder, but not AlarmLogDecoder_EvoAC. Can you take a look?
Also line 2480 seems duplicate.

**Comment by jgyates** [comment]
Good catch. Both issues are fixed and checked in

**Comment by buschauer** [comment]
work perfectly now. thanks!
