### ISSUE TITLE
Question: Would RS232 to Ethernet work?

### ISSUE THREAD

**Issue by jpettitt** [jgyates/genmon#771]
I was wondering if rather than putting a Pi4 (which is hard to get right now) inside my generator I could use something like this [RS232 over Ethernet](https://www.amazon.com/USR-TCP232-302-Serial-Ethernet-Converter-Support/dp/B01GPGPEBM/ref=sr_1_1_sspa) adaptor and then run the software in a docker image on one of my servers.   

Thoughts?

**Comment by jgyates** [comment]
@jpettitt 

Yes. See this wiki article on how to do this. 

https://github.com/jgyates/genmon/wiki/Appendix-F----Serial-over-IP

The docker part is not addressed but as long as you have a python environment, a TCP/IP stack and a file system you should be good. I am going to close this issue but feel free to post here with any follow up questions.
