### ISSUE TITLE
Genmon Version V1.18.15 sends constant Raspberry Pi health messages

### ISSUE THREAD

**Issue by mxplea10** [jgyates/genmon#774]
I just updated from Genmon Version V1.18.14 to V1.18.15 and immediately starting receiving text messages about the Raspberry Pi health from Genmon.  How can I stop Genmon from monitoring the Raspberry Pi and/or sending texts about the Raspberry Pi health?  Or, how can I revert back to Genmon Version V1.18.14?  I'm receiving so many text messages that I had to shut down the Genmon Raspberry Pi.

- Generator Model: Generac 22kW
- Genmon Logs: Submit via the About page
- Genmon Version: V1.18.15

**Comment by mxplea10** [comment]
![GENmon Raspberry Pi Health Messages](https://user-images.githubusercontent.com/35709872/191130727-ebf372ec-45ac-47a0-b1d9-9155f8676e53.png)

I thought that I had attached this but don't see it.

**Comment by jgyates** [comment]
@mxplea10 

You can disable the Pi hardware sensor notifications on the add on page. Each add on has it's own disable for each notification catagory.

<img width="317" alt="Screen Shot 2022-09-19 at 6 30 21 PM" src="https://user-images.githubusercontent.com/4513286/191130886-bcea175a-ed3e-4d79-834b-96296b431183.png">

Also, note that these sensors indicate a problem with your pi's temperature or power source. Your attachment looks like the CPU freq throttling so this could be a heat issue. If the pi's internal temp is over 80 degrees C then CPU throttling is enabled. Maybe add a fan or better air flow may also correct the issue.

**Comment by mxplea10** [comment]
Ok, it seems strange that this occur immediately after the update.  I'll troubleshoot the issue and updated accordingly.  Thanks for the fast response.

**Comment by mxplea10** [comment]
@jgyates

Is there another setting to change?  I'm still receiving messages.
![Twilio Setting Change 20220919_18-08-44](https://user-images.githubusercontent.com/35709872/191134912-5a772af4-efa6-4963-96b5-ce12952a21ac.jpg)

**Comment by jgyates** [comment]
This is a new feature in 1.18.15. 

https://github.com/jgyates/genmon/blob/master/changelog.md

It is very likely you had this issue all along but you were not monitoring this info. The new update allows genmon to monitor this information and notify you. This feature was added by request form this thread:

https://github.com/jgyates/genmon/issues/772

I am going to close this issue now but feel free to post here with follow up questions or comments.

**Comment by mxplea10** [comment]
Ok, but how is this helping me with temporarily disabling this until I have time to troubleshoot it.

**Comment by mxplea10** [comment]
Again, I have disable "Notify for Pi Hardware Issues" in the Twilio Add-on but I'm still receiving the text messages.

**Comment by jgyates** [comment]
have you saved you settings once you disable this? I will try to duplicate this later tonight.

**Comment by mxplea10** [comment]
Yes, I saved it.  I disabled Twilio and the text messages stopped.  I'll enable it again and leave "Notify for Pi Hardware Issues" disabled to verify if I receive the message again.

![Twilio Disabled 20220919_18-24-59](https://user-images.githubusercontent.com/35709872/191136299-3903864a-ae19-46f9-82fa-7db18b562449.jpg)

**Comment by mxplea10** [comment]
Ok, the Pi Hardware issue messages started again when I enabled Twilio.

**Comment by jgyates** [comment]
@mxplea10 

sorry about the confusion in the earlier reply. I glossed over the fact that you were unable to disable the pi hardware sensor monitoring. I was able to duplicate and found the issue. I checked in an update so just update from the About page and then you can enable the SMS add on and also disable the pi sensor monitor. Let me know if you have any issues or questions.

**Comment by mxplea10** [comment]
It works with the update.  Thanks...
