### ISSUE TITLE
Feature request : Manually start / Stop / Transfer generator from Dashboard

### ISSUE THREAD

**Issue by fencing49** [jgyates/genmon#775]
Maybe it's not on my dashboard but i don't see a way to manually start / stop / transfer the generator on my own.

It would be a nice addition for also running along side with the exercise as sometimes i just want to turn my generator on to monitor outputs.

If it's already in Genmon let me know where and feel free to close this.

Either way, love this software so damn much you have no idea.
Down with Generac corporate greed, all hail genmon!

**Comment by skipfire** [comment]
@fencing49 it is near the bottom of the maintenance page.

**Comment by fencing49** [comment]
That's odd, appears to be missing on mine
![image](https://user-images.githubusercontent.com/12490327/191369473-0bbc7740-9b67-4700-b622-94fac2f30509.png)



> @fencing49 it is near the bottom of the maintenance page.

**Comment by jgyates** [comment]
Do you have "Smart Transfer Switch" enabled on the Settings page? If you have a smart switch then the controller can not support these commands as your controller would be in Two Wire mode. If you do not have a smart switch then you should disable this settings and you will see the controls to start, stop and start/transfer on the Maintenance page.

If that does not answer your question I would need to see you logs, which you can submit on the about page.

**Comment by fencing49** [comment]
> Do you have "Smart Transfer Switch" enabled on the Settings page? If you have a smart switch then the controller can not support these commands as your controller would be in Two Wire mode. If you do not have a smart switch then you should disable this settings and you will see the controls to start, stop and start/transfer on the Maintenance page.
> 
> If that does not answer your question I would need to see you logs, which you can submit on the about page.

That was it, i have a smart transfer switch so i had it enabled."

Thankyou!
