### ISSUE TITLE
Docker installation possible?

### ISSUE THREAD

**Issue by FlaMike** [jgyates/genmon#776]
I would like to install your genmon software on a docker server instead of directly on a Pi's OS.  I plan to use gregmac's approach with either a D1 Mini Pro at the generator or and ESP32.  Both have external antennas and can hopefully transmit generator data to the server over WiFi.

If you have any suggestions or can tell me how to install the genmon software using a Docker container I would appreciate it greatly.

I look forward to using your fascinating software.

Thank you!

**Comment by jgyates** [comment]
Here are a couple of threads that are doing that:

https://github.com/jgyates/genmon/issues/491

https://github.com/jgyates/genmon/issues/771


the first one has a yml file that may be useful. I am going to close this issue but free free to post to this thread or the other two with followup questions or info that may help others.
