### ISSUE TITLE
Do I have a compatible controller?

### ISSUE THREAD

**Issue by ripvega** [jgyates/genmon#784]
My controller is an Evolution 2.0.

Below is a photo of the underside. It looks to me like the Molex connector, which was covered with a green sticker, isn't fitted.
![IMG_2844](https://user-images.githubusercontent.com/42817627/194830289-9a262573-482c-4457-afe7-073122d22a47.JPG)
Any suggestions?

**Comment by skipfire** [comment]
Right next to the empty 10-pin is the occupied 8-pin. 
 Unplug the 8-pin that is in there, that current cable will be Mobilelink.

**Comment by ripvega** [comment]
Great! Thank you.
