### ISSUE TITLE
latest version

### ISSUE THREAD

**Issue by Barrygordon** [jgyates/genmon#790]
I have recently installed Genmon and it is working perfectly.  The virsion I have installed is 1.18.15
but at the GIT site it says the latest version is 1.18.14 (latest).  I don't understand. could you please clarify.

**Comment by jgyates** [comment]
If you look at the release history here:

https://github.com/jgyates/genmon/releases

you will see numerous, non consecutive version numbers of "releases". A "release" is just a point that I take a snap shot. The last "release" is 1.18.14. I typically create a "release" after a period of no reported issues to signify stability.

The version is consecutive and changes when every something significant changes in the code.

For example you can have versions 1,2,3,4,5 but only create a release for version 2 and 4. You can look at releases as just a marker or tag for a given version that is created at a milestone point in time.

The change log documents what changes between versions:

https://github.com/jgyates/genmon/blob/master/changelog.md
