### ISSUE TITLE
Pushover - need help for install on older build

### ISSUE THREAD

**Issue by DC072012** [jgyates/genmon#791]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below. This is a template so feel free to remove any of this text. Try to include the info below when applicable.

***NOTE:*** If you are having issues with your serial connection, please read this page before posting:

https://github.com/jgyates/genmon/wiki/3.6---Serial-Troubleshooting

If you are having other issues, please see the following page:

https://github.com/jgyates/genmon/wiki/3.5---General-Troubleshooting

You can search past issues by removing the "is:open" keywords from the search window and adding any keywords that are relevant to your issue.

If you need to send you logs and registers to the developer, if your email is setup and working properly you can click send your logs on the About page in the web interface.

### Expected Behavior

Pushover configured with app id and pushover user key.  Push alerts not working 

### Actual Behavior

Push alerts not coming to device.

### Steps to Reproduce (including precondition)

This is a really old build of genmon prior to the inclusion of the Pushover add on screen.  I followed these instructions from sjbader but am stuck.  My notes in parentheses:

"As promised, here is the code and config file. Install is super simple.

sudo pip3 install chump **(ran this, chump already installed)**

Copy genpushover.py to the root directory where all your other genmon files are. 
**(Not sure how to do this.  Here is file list for genmon and a search for files named genpushover.***

pi@genpi [~/genmon] ls -l
total 416
drwxr-xr-x 2 pi pi   4096 Oct 17 13:14 addon
-rw-r--r-- 1 pi pi  41099 Oct 17 13:14 changelog.md
-rw-r--r-- 1 pi pi   2807 Oct 17 13:14 ClientInterface.py
drwxr-xr-x 2 pi pi   4096 Oct 17 13:14 conf
drwxr-xr-x 4 pi pi   4096 Oct 17 13:14 data
drwxr-xr-x 3 pi pi   4096 Oct 17 13:14 Diagrams
-rw-r--r-- 1 pi pi   1817 Oct 17 13:14 feature_requests.md
-rw-r--r-- 1 pi pi  48875 Oct 17 13:14 genloader.py
-rw-r--r-- 1 pi pi  10316 Mar 16  2021 genmon_backup.tar.gz
drwxr-xr-x 3 pi pi   4096 Oct 17 13:14 genmonlib
-rwxrwxr-x 1 pi pi  14925 Oct 17 13:14 genmonmaint.sh
-rw-r--r-- 1 pi pi  65686 Oct 17 13:14 genmon.py
-rw-r--r-- 1 pi pi 149154 Oct 17 13:14 genserv.py
-rw-r--r-- 1 pi pi  18026 Oct 17 13:14 LICENSE
drwxr-xr-x 2 pi pi   4096 Oct 17 13:14 OtherApps
-rw-r--r-- 1 pi pi  10423 Oct 17 13:14 README.md
-rw-r--r-- 1 pi pi    163 Oct 17 13:14 requirements.txt
-rwxrwxr-x 1 pi pi   2810 Oct 17 13:14 startgenmon.sh
drwxr-xr-x 5 pi pi   4096 Oct 17 13:14 static
drwxr-xr-x 2 pi pi   4096 Oct 17 13:14 templates
------------------
pi@genpi [~] sudo find / -type f -name "genpushover.*"
/var/hdd.log/genpushover.log
/var/log/genpushover.log
/etc/genmon/genpushover.conf
/home/pi/genmon/addon/genpushover.py
/home/pi/genmon/conf/genpushover.conf
find: ‘/proc/26149/task/26149/net’: Invalid argument
find: ‘/proc/26149/net’: Invalid argument

**Do I need to copy /home/pi/genmon/addon/genpushover.py somewhere else?**)

Copy genpushover.conf to /etc and configure as following: **( I verified this has the proper keys)**
appid is generated when you log into pushover.net and at the bottom next to "Your applications" click on "Create Application/API Token". I don't recall exactly, but I'm pretty sure I chose the 'application' type from the dropdown that is provided. I don't think it much matters. Once you create your app, you're provided with a long and unique application/API token. That's what you provide from the appid value.
userid is your user key and is provided when you log into pushover.net.
pushsound is the custom sound field. I want my genmon to sound different than other alerts, so I don't choose the default. There is a link to the list of options in the .conf file.

Add the following in the 'start' case in startgenmon.sh: **(I added this)**
sudo python /home/pi/genmon/genpushover.py &

Add the following in the 'stop' case in startgenmon.sh: **(I added this)**
sudo pkill -f genpushover.py"

### Screenshot or Pictures relating to the problem (if possible)

{Please write here}

### Your Environment

- Generator Model: G0058820
- Genmon Logs: Sent
- Genmon Version: V1.18.15

**Comment by jgyates** [comment]
If your genmon version is 1.18.15, then you do not have an older build. This is the latest version and adding any lines to startgenmon.sh do not help, it only corrupts your install. The wiki states:

https://github.com/jgyates/genmon/wiki/1----Software-Overview#genpushoverpy-optional

"This program, like other add on programs, is enabled and configured via the web interface on the Add On page. If using the Add On interface the setup, configuration and execution is handled by genlaoder via the web interface."

To enable the pushover add on just enable it on the Add On page in the web interface.

Your logs (/var/log/genpushover.log) indicate that these errors are occurring:

2022-10-17 13:11:44,188 : Unable to authenticate app ID
2022-10-17 13:11:44,189 : Error sending message in QueueWorker, callback failed, retrying
2022-10-17 13:13:28,943 : Send Notice Error: genpushover.py:214: Bad sound: must be in ('alien', 'bike', 'bugle', 'cashregister', 'classical', 'climb', 'cosmic', 'echo', 'falling', 'gamelan', 'incoming', 'intermission', 'magic', 'mechanical', 'none', 'persistent', 'pianobar', 'pushover', 'siren', 'spacealarm', 'tugboat', 'updown', 'vibrate'), was 'Bugle'

You have your sound set to Bugle but it should be lower case: https://pushover.net/api#sounds

Once you correct that issue, if it still does not work then your issues is your app ID is invalid.

**Comment by DC072012** [comment]
OK, feel pretty sheepish now - I forget that capitalization matters on these things.  As you predicted, I fixed that and it is working now.

I appreciate your help over the past few days and will be sending along a donation in appreciation.

**Comment by jgyates** [comment]
No worries. I am glad it is working now.

**Comment by jgyates** [comment]
FYI, I updated the wiki to include info about lower case and I also added a line to the add on to force lower case.

Make sure you remove the lines you added to startgenmon.sh or you can just update the software from the About page and it should overwrite the any modifications in the /home/pi/genmon folder.
