### ISSUE TITLE
Tank Utility Monitor

### ISSUE THREAD

**Issue by Barrygordon** [jgyates/genmon#797]
I understand that Generac has bought out the Tank Utility Monitor.  Knowing their propensity to have things work in house onl, I am wondering if Genmon will work with the Generac Tank Utility Monitor or will it only work with the Generac Cloud?  Generac charges a $50 annual subscription fee.  I am totally against what they are doing.

**Comment by jgyates** [comment]
as long as you buy your monitor from https://tankutility.com/ you should be good, however I do not have a data point on a Generac branded monitor.

**Comment by jgyates** [comment]
I have a monitor from tank utility and it still works with the gnemon add on and the tankutility mobile app however I purchased my before generac got involved. 

My generator is diesel but use tank monitor on a propane tank with my HVAC system.
