### ISSUE TITLE
Closed issue #797

### ISSUE THREAD

**Issue by Barrygordon** [jgyates/genmon#798]
Whenever I try and buy the tank utility monitor from tankutility.com it sends me to the Generac site to buy it there. Has anybody had experience with the tankutility monitor sold by Generac? I am concerned that they might have changed the firmware to only communicate with their cloud.

**Comment by jgyates** [comment]
You can still comment on closed threads. You just have to remove "is:open" from the filters 

Here is your original issue: 

https://github.com/jgyates/genmon/issues

**Comment by jgyates** [comment]
sorry, this is your original issue:

https://github.com/jgyates/genmon/issues/797
