### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by Barrygordon** [jgyates/genmon#800]
Is there any way to clear the logs?

**Comment by jgyates** [comment]
Not via genmon. If there is a way to do that via the controller menus I am not aware. Others may have more insight on this question.

**Comment by jgyates** [comment]
looks like the answer is no:

https://www.zillerstore.com/post/can-logs-be-cleared-to-hide-previous-under-voltage-alarms-11866802?highlight=clear%20log&pid=1327503517
