### ISSUE TITLE
Raspberry Pi memory size

### ISSUE THREAD

**Issue by Barrygordon** [jgyates/genmon#802]
A friend asked me to build him a system as he has the same generator as I. This time it will go quickly as I know what I am doing.  I had a nice RPi 4 which I used when I built my system.  What ram memory size do you recommend for the RpP?  All it will be running is Genmom. 

TIA, Barry

**Comment by jgyates** [comment]
Any memory sizes offered of the raspberry pi will work fine with genmon. If you plan to run other apps or services on your pi you may want the higher memory options.
