### ISSUE TITLE
Questions not issue

### ISSUE THREAD

**Issue by Barrygordon** [jgyates/genmon#808]
I believe the indicator of battery volltage does not read the batteries voltage it reads the chargers voltage output as long as the charger is running. 
This should be a Generac problem, but perhaps a re-labeling of the meter in the monitor would be appropriate as "Battery Charger"

I live in Florida where it gets pretty hot.  I am wondering if a warning (Message and email) will be issued by Genmon when the temperature is too high (Meter showing in the yellow region). I am thinking of venting the case and installing some 12v 40x40 fans to exhaust air. However my motto is "If it ain't broke, don't fix it".  Right now the air temp is around 82 F and the CPU temp is 137 F.

Genmon is an excellent piece of work!!

**Comment by jgyates** [comment]
Hi @Barrygordon 

Genmon does not send a notice for the CPU temp. This value is read from the operating system and is available on most linux systems so if I implemented a warning notice then this would need to user configurable regarding the notice threshold or only applicable to a raspberry pi. Let me think on a good way to implement.

If you are using a short message add on like SMS you do have the option of getting notices when the pi is frequency throttled (as a result of overheating),  the Pi ARM Frequency Cap has been hit or an under-voltage on the PI has occurred.

Regarding the battery gauge label, you are correct that when charging it reads the charger output, however when not charging it reads the battery voltage. The battery chargers in 18 hour cycles. The comments in the code here give more details on the charger cycles. When cranking the charger is disabled and it shows the battery voltage.  From the software's perspective, there is only one reading and to avoid confusion I will likely keep it labeled Battery Voltage.

https://github.com/jgyates/genmon/blob/9cf8952173ec007aae08f2ed12d5640c1d10fb67/genmonlib/generac_evolution.py#L4238

Thanks for the kind words and the great feedback. If you have any thing else on these topics feel free to post it to this thread.
Jason
