### ISSUE TITLE
Not so much an issue, but a question

### ISSUE THREAD

**Issue by grsthegreat** [jgyates/genmon#811]
it sure would be nice if there was a way to have a do not disturb option available. In other words, tell the generator if power fails outside the set limits, the generator is not to turn on. 

I could care less if the power went out at 3am while im asleep. The noisy gen just wakes me up.

**Comment by jgyates** [comment]
@grsthegreat 

The only way to do this would be to use the remote buttons, which only work on the Evolution Liquid cooled models. Unless you have that model I don't know of a way to do this. If you do have the model, then you ***must*** have a UPS connected or you would not recover if a power failure occurred.
