### ISSUE TITLE
Question - Propane Tank Level Alarm

### ISSUE THREAD

**Issue by rwskinner** [jgyates/genmon#818]
Happy Thanksgiving!

Question - Is there a notification with adjustable setpoint for low tank level that can be used on the Mopeka or other external sensor?
A deer hit my gas line and cracked it and I lost 200 gallons of propane in 1 day.  I'd like to set an alert in case a freak accident like his happens again that I might be able to save some of it.  That was an expensive lose!

**Comment by jgyates** [comment]
No. Currently the notification is fixed at 10 and 20 percent (two separate notices). I can add this to the feature list.

**Comment by jgyates** [comment]
https://github.com/jgyates/genmon/blob/master/feature_requests.md

**Comment by rwskinner** [comment]
I sure don't remember seeing an email notification on either and I had 
notifications turned on.

**Comment by jgyates** [comment]
The fuel level is checked once every 10 min so if you lost a lot of fuel rapidly then you may not of gotten a message.
