### ISSUE TITLE
Genmon CT Hat

### ISSUE THREAD

**Issue by andrewvanlagen** [jgyates/genmon#819]
What gpio's does your Ct Hat use the mpc3008

**Comment by skipfire** [comment]
@andrewvanlagen if you are asking about the PintSize HAT it uses SPI1 with CS0 which ties up IOs 18, 19, 20, 21.

**Comment by andrewvanlagen** [comment]
@skipfire @jgyates 
can you please confirm this pinout
MOSI - Gpio 20
MISO - Gpio 19
CE0 - Gpio 18
CLK - Gpio 21

**Comment by skipfire** [comment]
That is correct @andrewvanlagen

**Comment by andrewvanlagen** [comment]
thanks

**Comment by skipfire** [comment]
@andrewvanlagen I forgot about the 1-Wire on 4 for temp.

**Comment by andrewvanlagen** [comment]
Does the software support 4 or 8 CT

**Comment by skipfire** [comment]
GenMon is only utilizing channels 0 & 1 for the CTs.  The HAT has the 8 channel chip, the pHAT has the 4 channel chip.

**Comment by jgyates** [comment]
@skipfire  is correct, the software currently only reads two channels. If there was a person who wanted to test I could add a third for a generator that supports three phase.

**Comment by jgyates** [comment]
I am going to close this issue but feel free to post here with any follow up questions on this topic.
