### ISSUE TITLE
otodata bluetooth propane level receiver

### ISSUE THREAD

**Issue by bdwilson** [jgyates/genmon#824]
I got my hands on an otodata TM6030 propane sensor.  This sensor speaks bluetooth and supposedly has a 10yr battery.  Since my genmon device is close to my tank, I can easily capture this bluetooth data via genmon.  My question is, does genmon provide a facility to run a plugin as a daemon?  Currently this is what I'm doing to capture the data and send it into Genmon (it's in Perl or I'd attempt to do a PR).

Run: `sudo hcitool lescan --duplicates` continuously with output not buffered. 
The Bluetooth name of the device swaps between the device name (TM6030) and serial#, sleeping... and the current level! The name looks like this: `Complete Local Name: 'level: 56.1 % horiz'`

When I get a match on level, I capture the percentage and make a call to `/home/pi/genmon/ClientInterface.py` with a payload of: `'generator: set_tank_data={"Tank Name": "External Tank", "Capacity": 320, "Percentage": 56.1}'`

I wasn't sure how hard this would be to add into Genmon. I don't mind running my own perl daemon, but figured I'd share this in case others have access to devices and want to create a plugin.  I'm running this on a Pi Zero 2, and the Pi is inside my Generator unit. The propane tank is about 15' line of sight from the generator.   

EDIT: Here is the code I wrote.  https://github.com/bdwilson/otodata-genmon. It will also send the data to Hubitat.

**Comment by jgyates** [comment]
@bdwilson 

This is great info. Thanks for sharing this!

Unfortunately no, genmon does not have any functionality to load or unload daemon add ons. No one has ever asked before. If I get more requests I will consider adding this.
