### ISSUE TITLE
include "Site Name" is Twilio/SMS messages

### ISSUE THREAD

**Issue by MolallaComm** [jgyates/genmon#825]
With the Twilio/SMS add on - would be it possible to include "Site Name" in the message.  Without it, for people who have many different generators they monitor, there is no way to tell which is which.

**Comment by jgyates** [comment]
I have checked in an update that adds the site name to short messages for gensms, genslack and genpushover. Let me know if you have any issues. I am going to close this thread but feel free to post questions or comments on this topic here.
