### ISSUE TITLE
Minor issue - Wifi signal strength appears inconsistent between generator status page and monitor page

### ISSUE THREAD

**Issue by DC072012** [jgyates/genmon#837]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below. This is a template so feel free to remove any of this text. Try to include the info below when applicable.

***NOTE:*** If you are having issues with your serial connection, please read this page before posting:

https://github.com/jgyates/genmon/wiki/3.6---Serial-Troubleshooting

If you are having other issues, please see the following page:

https://github.com/jgyates/genmon/wiki/3.5---General-Troubleshooting

You can search past issues by removing the "is:open" keywords from the search window and adding any keywords that are relevant to your issue.

If you need to send you logs and registers to the developer, if your email is setup and working properly you can click send your logs on the About page in the web interface.

### Expected Behavior

WIFI Signal strength on status page and the monitor page should be similar if not equal

### Actual Behavior

Signal strength on status page and monitor page are not similar.  Coincidentally the absolute value of the two numbers appear to add up to roughly 100.

I tried this on both Safari and Chrome so it does not appear to be a browser issue.

Maybe this in unavoidable for some reason - I could not find a similar issue when searching the wiki.

### Steps to Reproduce (including precondition)

Click on status screen, then the monitor screen

### Screenshot or Pictures relating to the problem (if possible)

3 screenshots:
<img width="1068" alt="Screenshot 2023-01-02 at 9 17 41 AM" src="https://user-images.githubusercontent.com/51464940/210243615-34b4b048-6652-4d13-bc3b-919f1bf37631.png">
<img width="1068" alt="Screenshot 2023-01-02 at 9 18 00 AM" src="https://user-images.githubusercontent.com/51464940/210243630-91753fb0-f308-4a33-a14a-df1b2a5fde59.png">
<img width="1068" alt="Screenshot 2023-01-02 at 9 18 50 AM" src="https://user-images.githubusercontent.com/51464940/210243636-26ea2c4f-b67c-4527-8563-b5b029bd4120.png">

### Your Environment

- Generator Model: G0058820
- Genmon Logs: Sent
- Genmon Version: V1.18.16

**Comment by jgyates** [comment]
This is an anomaly / bug. I will try to correct this behavior soon. The software is pulling the info form 2 different places but they are related as you noted.

**Comment by jgyates** [comment]
I have updated the code that **should** correct this. There are still some rare conditions that this can occur, but that is dependent on the underlying wifi network adapter device driver. Not all drivers support the same format in /proc/net/wireless and if the program "iw" is not present then the software falls back to using /proc/net/wireless to get the signal strength. I am going to close this issue but let me know if you have any issues in this thread.

**Comment by DC072012** [comment]
Looks like the update is working!  Thanks for the quick update.
