### ISSUE TITLE
Help with wiring

### ISSUE THREAD

**Issue by kalex1114** [jgyates/genmon#84]
Hello
I finally got all parts and starting to assemble the cable. 
I need a little help with wiring :)
I bought female rs232 to ttl and male break out connector.
I also bought ATX cable with connector on it and will be using Raspberry PI3

The way I understand it is that I need to cut the ATX cable and leave the molex connector with cables attached.  
Is this correct?
Pin 1 of the molex calbe will plug into pin 2 on the PI3
Pin 2 of the molex cable will plug into pin 9 on the PI3
Pin 7 of the molex cable will plug into pin 2 RXD on the breakout connector
Pin 8 of the molex will plug in into pin 3 TXD on the breakout connector
VCC dupont connector on rs232/ttl adapter will go into pin 4 on PI3
RDX dupont connector on rs232/ttl adapter will go into pin 10 on PI3
TXD dupont connector on rs232/ttl adapter will go into Pin 8 on the PI3
GND dupont connector on rs232/ttl adapter will go into pin 6 of the PI3

Did i get these correctly?

Here are pictures just to make sure i got right parts.
Molex from ATX cable:
![screenshot 2018-04-05 16 31 57](https://user-images.githubusercontent.com/17240236/38390294-e2189446-38ee-11e8-8fc2-fe0536e8cdd2.png)

Male breakout cable:
![screenshot 2018-04-05 16 32 37](https://user-images.githubusercontent.com/17240236/38390333-f9b8b504-38ee-11e8-99cb-f87856d6f4e4.png)

female rs232/ttl adapter:
![screenshot 2018-04-05 16 32 57](https://user-images.githubusercontent.com/17240236/38390350-0992c406-38ef-11e8-81b2-3141534440a1.png)

![screenshot 2018-04-05 16 33 23](https://user-images.githubusercontent.com/17240236/38390362-15ac80ec-38ef-11e8-8453-3bee86a080c2.png)

![screenshot 2018-04-05 16 34 29](https://user-images.githubusercontent.com/17240236/38390409-3d7d6ae6-38ef-11e8-9c1c-12b064aec7aa.png)

**Comment by JustApu** [comment]
`` Pin 7 of the molex cable will plug into pin 2 RXD on the breakout connector``
``Pin 8 of the molex will plug in into pin 3 TXD on the breakout connector``

I believe you need to swap these two but everything else looks correct to me. Caveat: My parts are still en route so I haven't built mine yet.

**Comment by jgyates** [comment]
Not sure if you have seen this, but there is a diagram on this page that should help:

https://github.com/jgyates/genmon/wiki/Making-a-Cable

**Comment by kalex1114** [comment]
Yep I saw the making a cable diagram.  I followed it just wanted to double check i got it right.

**Comment by kalex1114** [comment]
JustApu - are you sure? I followed the cabling diagram posted here:

https://raw.githubusercontent.com/jgyates/genmon/master/Diagrams/Cable_Connections.jpg

I was following DCE setup female rs232/ttl adapter and make 9 pin breakout connector
Pin 8 molex into pin 3 on the PI
Pin 7 molex into pin 2 on the PI

Is that not correct?

**Comment by JustApu** [comment]
Not sure.

In looking at your link, I think you are correct. I was going with the TX/RX on the MAX3232 board and didn't notice the connectors on your parts for DCE vs. DTE.

**Comment by jgyates** [comment]
@kalex1114, I will close this thread unless you still have questions. Feel free to comment in this thread if you do.

**Comment by jgyates** [comment]
Nothing stands out to me as incorrect.
