### ISSUE TITLE
[Feature Request] - Hardware keys (FIDO2) for 2fa

### ISSUE THREAD

**Issue by danodemano** [jgyates/genmon#841]
This is another bottom of the barrel request but I'm trying to get away from 2fa codes and having to scroll though like 60 of them on my phone, lol. It would be great if Genmon would support hardware keys like Yubikey and FIDO2 auth. So much easier to just touch a USB key than pull out my phone. :) As always, thanks for the amazing project!!!

**Comment by jgyates** [comment]
@danodemano 

Thanks for the suggestion.

https://github.com/jgyates/genmon/blob/master/feature_requests.md

It's on the list. I will update this thread when it gets added to the code.
