### ISSUE TITLE
Feature Request - Enhanced Cool Down

### ISSUE THREAD

**Issue by alphaa211** [jgyates/genmon#844]
Is there any way to have an enhanced cool down period either user selectable or for a set 5 minutes after the generator has run under load OR has run at any time if that is all that is possible?

I really notice this in the summer when I test under load; the standard 1 minute really isn't enough and I'll manually run it to help it get a better cool down before it shuts off and heat soaks.  The big industrial generacs have selectable cool down timers and I wondered if Genmon could do something similar.  Even if it automatically added 5 mins to the end of every run time that would cool down better in the summer but also give a minimum run time for short duration outages that just get the thing started for a minute or two.

Thanks!

**Comment by jgyates** [comment]
No. There is no way to alter, stop or override the built in cool down period for Evolution or Nexus that I am aware of. You could monitor when the generator shuts off and then run again, but that would not achieve what your are wanting.

I am going to close this issue but feel free to post any follow up questions here.
