### ISSUE TITLE
Help - Cable Connection Inside Generator

### ISSUE THREAD

**Issue by jonathanpisarczyk** [jgyates/genmon#85]
Hey Guys,

I went to connect my Pi and cable to Generac.  However I can't find the appropriate place to connect my cable.  I've got a Evolution 20KW model.  See pictures below.  Any help would be appreciated. 

![img_1741](https://user-images.githubusercontent.com/36710072/38457546-b299c538-3a5f-11e8-85ec-1350dd06af48.jpg)
![img_1742](https://user-images.githubusercontent.com/36710072/38457547-b2a8b336-3a5f-11e8-91c3-24c6104870cf.jpg)
![img_1743](https://user-images.githubusercontent.com/36710072/38457548-b2b567d4-3a5f-11e8-857a-637494187418.jpg)
![img_1744](https://user-images.githubusercontent.com/36710072/38457549-b2c2d41e-3a5f-11e8-8b1d-6816d51164e9.jpg)

**Comment by proppilot** [comment]
Peel off the Accessory Port 1 sticker and plug is there

**Comment by jonathanpisarczyk** [comment]
Thank you !!! Never would have guessed that.

**Comment by jonathanpisarczyk** [comment]
I know the issue has been closed.  However the picture may help someone in the future.  Here's my genmon cable going into accessory port 1.  Thanks again...
![img_1746](https://user-images.githubusercontent.com/36710072/38509344-a6787326-3bef-11e8-9256-d5458ae3d67b.jpg)
