### ISSUE TITLE
Temperature gauge display problem

### ISSUE THREAD

**Issue by T-C123** [jgyates/genmon#856]
**Expected Behavior:**
Temperature gauge displaying analog and digital temperature

**Actual Behavior:**
Displays temperature but the digital display for the second temperature gauge is displayed low, almost off the bottom of the gauge.

**Steps to Reproduce** (including precondition):
Whenever Status page is displayed

**Screenshot** or Pictures relating to the problem:

![image](https://user-images.githubusercontent.com/93269367/218124629-3e132161-e75a-4bfb-aad4-18bfb1d5a978.png)

**Your Environment:**
Display is the same on Chrome, Firefox or via Real VNC.

**NOTE:** The gauge displaying incorrectly is the second of two added under Add-Ons and data is retrieved from a thermocouple.

![image](https://user-images.githubusercontent.com/93269367/218125929-f0b12a42-0b49-4d08-acff-6869c00cdb78.png)

- **Generator Model:** Generac 18 kw, Evo2
- **Genmon Version:** V1.18.16

This is a minor problem but I thought you should know.

Thanks for your help!

**Comment by jgyates** [comment]
Try shortening the label form "Engine Oil Temp" to something like "Oil Temp" or "Oil Temperature". The issues is that all of the gauge placements expect a single line for the label. The gauges use a 3rd party library so I don't have full control over the spacing. Let me know if that does not fix your issues.

**Comment by T-C123** [comment]
Fixed, Thank you!


    On Friday, February 10, 2023 at 10:20:37 AM EST, jgyates ***@***.***> wrote:  
 
 


Try shortening the label form "Engine Oil Temp" to something like "Oil Temp" or "Oil Temperature". The issues is that all of the gauge placements expect a single line for the label. The gauges use a 3rd party library so I don't have full control over the spacing. Let me know if that does not fix your issues.
