### ISSUE TITLE
Serial to TCPIP w/ USR-W630

### ISSUE THREAD

**Issue by LPCALC** [jgyates/genmon#863]
Has anyone had any success using the USR-W630 as serial to tcpip device?  

The device passes the loopback test.  

Serialtcp.log  contains only errors & timeouts:

_2023-02-26 12:32:54,750 : Error in SerialTCPDevice:Write : timed out : myserialtcp.py:212
2023-02-26 12:33:05,697 : Error: Connect : timed out_

### Your Environment

- Generator Model: Generac 17kW Air Cooled with Nexus 
- Genmon Version: current

**Comment by jgyates** [comment]
I have not personally used that one (I use the WR610) however it passes the [socket loopback test](https://github.com/jgyates/genmon/wiki/1----Software-Overview#otherappssockettestpy-optional) it should work. This is assuming you have the same IP and port number on the loopback command line as you do on the settings page. Also, note that you should *NOT* use Modbus TCP with a Nexus or Evolution controller. Only use the transparent serial over IP mode. Genmon supports both however Modbus over TCP is a different protocol compared to serial Modbus over a transparent TCP link. If you enabled Modbus over TCP then the loopback would pass but the operation of genmon would result in a timeout as the controller would not respond as it does not support modbus TCP.

**Comment by LPCALC** [comment]
I did have Modbus turned on. Turned it off and restarted genmon.  Looks like genmon is receiving data from the WR630, 
Communication errors & Timeouts persist:
![com stats](https://user-images.githubusercontent.com/123986303/221678454-9f7d2279-5e6a-44cc-b28f-ea03114dddd5.JPG)

I am running the WR630 via wifi.  Although it is only ~15' from the AP, maybe a contributing factor to my issue.

**Comment by jgyates** [comment]
I am going to close this issue but feel free to post any follow up status or questions here. Let me know if you got the WR630 working.

**Comment by LPCALC** [comment]
I believe my settings are correct. 
Genmon config:
use_serial_tcp =True
serial_tcp_address =192.168.1.183
serial_tcp_port = 8899
modbus_tcp = False


W630 config
![image](https://user-images.githubusercontent.com/123986303/222211604-35f344b7-9503-499e-8bd7-2dc59ef740fd.png)
![image](https://user-images.githubusercontent.com/123986303/222211593-d2a5c963-cf9f-4e69-87a6-bf981f4b3013.png)
![image](https://user-images.githubusercontent.com/123986303/222215148-31ed01eb-93ec-44b7-aab2-2220b315b3e8.png)


The W630 has a lot of setting I do not understand & manual is of little help to noobie like myself. 
 If the UART performs anything like web GUI then I could it be an issue. Web GUI does not always load on first go. Not sure if it is because I am utilizing Wifi. Unifi system says it has 100% signal strength so it probably is not an issue in my case.  I would hardwire it, but when I enable the LAN port and disable Wifi the device drops off of network. 
W630 is similar to the W610 but has additional LAN port. Are you running your 610 via wifi or hardwired?  

What is the url command to create and download logs?   <serviceip:8000/cmd/logs> ??

**Comment by jgyates** [comment]
I run with wifi. My W610 is powered by the controller and my pi is in my house.

To get the logs use this command:

http://ipaddress:8000/cmd/get_logs

One thing that looks odd is that your "Server Address" is 10.10.100.100" in the W630 settings yet your /etc/genmon/genmon.conf file shows "serial_tcp_address =192.168.1.183". these IP address should be the same.

Here are my settings for the W610:

<img width="941" alt="Screen Shot 2018-11-18 at 6 55 22 PM" src="https://user-images.githubusercontent.com/4513286/222220391-40d156f1-b55f-437f-9a1c-34666c869e29.png">

<img width="982" alt="Screen Shot 2018-11-18 at 6 55 36 PM" src="https://user-images.githubusercontent.com/4513286/222220427-e26e86ab-ae22-4672-9336-3db1d2a15ae2.png">

<img width="1017" alt="Screen Shot 2018-11-18 at 6 55 52 PM" src="https://user-images.githubusercontent.com/4513286/222220454-34a21005-42da-4c1c-b45b-ec237a6c978b.png">

<img width="1022" alt="Screen Shot 2018-11-18 at 6 56 47 PM" src="https://user-images.githubusercontent.com/4513286/222220504-7c236b74-dc70-4b26-bba9-80021bada1ff.png">

<img width="610" alt="Screen Shot 2018-11-18 at 6 57 41 PM" src="https://user-images.githubusercontent.com/4513286/222220554-fc96305e-57ea-4869-8892-0107192df8d0.png">

<img width="634" alt="Screen Shot 2018-11-18 at 6 57 54 PM" src="https://user-images.githubusercontent.com/4513286/222220606-7a314063-9a5e-4ea5-a4ae-71634054a634.png">

<img width="991" alt="Screen Shot 2018-11-18 at 6 58 13 PM" src="https://user-images.githubusercontent.com/4513286/222220646-1cdd89f7-6437-497f-9e07-21193d2223d0.png">

**Comment by LPCALC** [comment]
Thanks for the screen shots. 
On my w630 network setting has Server address greyed out.  Only way to edit is change mode type to Client. After updated IP and switch back mode back to server is switches back to 10.10.10.100 which is factory default for W630.

**Comment by jgyates** [comment]
what are your settings under the AP Interface menu? There is a section to set the IP address there and disable DHCP.

also, show your Ethernet Settings and Application Settings (not quick settings)

**Comment by LPCALC** [comment]
Application settings:
![image](https://user-images.githubusercontent.com/123986303/222261746-48ea9ae7-8c09-42f3-ade3-09b49898b93c.png)
![image](https://user-images.githubusercontent.com/123986303/222261769-f1a96bff-3f65-42f5-8dc5-69dc23211101.png)

Ethernet is not connected at this time. I am currently l running the w630 solely over wifi ei STA mode. 
![image](https://user-images.githubusercontent.com/123986303/222264564-f040f9ba-0b85-42af-9af1-8f9734377399.png)

The w630 already has an IP address 192.168.1.183 via DHCP. When I hardwired to network would I overwrite the default IP?

**Comment by jgyates** [comment]
You should set the LAN IP address to a fixed IP address. The DHCP address assigned by your router may change and when it does the IP will be different and genmon will no longer work until you change it to the different IP address.

Under LAN IP settings set set it to a fixed IP address on your network (not one assigned by DHCP) and the DHCP type should be "Disable". You have it setup to assign DHCP address from the WR630 which will conflict with your router.  Because the LAN settings on your WR630 and your listening IP address are no different subnets you have a misconfigured device so that is my best guess as to the problem.
