### ISSUE TITLE
Modbus Exceptions EVO 2.0 Version 1.15.176

### ISSUE THREAD

**Issue by ORCL-DBA** [jgyates/genmon#865]
Just started installing GenMon on a Generac EVO 2.0. Modbus log shows below messages. Will GenMon work with firmware 1.15.176?
Loopback tests look good. PI is connected to the Generac Battery for power.

Error Receiving slave packet for register xxxx

**Comment by jgyates** [comment]
See known issues number 11 and 15 regarding modbus exceptions on Evo2.0 controllers:

https://github.com/jgyates/genmon/wiki/Appendix-D-Known-Issues

Yes version 1.15 is known to work however modbus exceptions around every 8 minutes are expected. If you think it is not working for you then submit your logs via the about page.
