### ISSUE TITLE
Feature request: Option to delay "not receiving data" alerts?

### ISSUE THREAD

**Issue by skipfire** [jgyates/genmon#867]
I've recently switched to using a serial bridge, since the switch a few times I day I've gotten false not receiving data and utility outage notifications.  I was able to eliminate the false utility outage notifications by setting the outage notification delay to 10 seconds, a similar option for not receiving data would be fantastic.  Or is there one already that I just haven't seen?

Also, I found help comments about the outage notification delay, but could not find a default value in any of the config files.  I ended up reading the code and saw it was being read in near the smart transfer switch setting, so I placed it next to that config value.

Genmon version V1.18.16

**Comment by jgyates** [comment]
Look under the Advanced Settings for the setting named "Additional Watchdog Timeout (sec)". If using serial the default watchdog timeout is 2 seconds, if using TCP the default is 8. This setting will add x number of seconds to this timeout.

**Comment by skipfire** [comment]
Thanks!
