### ISSUE TITLE
Serial Server Address by name?

### ISSUE THREAD

**Issue by skipfire** [jgyates/genmon#868]
Is there any technical reason that the `Serial Server TCP/IP Address` must be an IP address rather than a name, or is it limited to IP because local name lookup can be questionable on some home networks?

Thanks.

**Comment by jgyates** [comment]
It can be an IP address or a fully qualified domain name.  The comment bubble for this parameter in the settings page needs to be updated to reflect this. I will do that. Let me know if you are having any issues.

**Comment by skipfire** [comment]
Needing the fully qualified name is what I missed, thanks!
