### ISSUE TITLE
Wi-Fi changed and cant get in... remedies?

### ISSUE THREAD

**Issue by ravedoglv** [jgyates/genmon#871]
Unfortunately the Wi-Fi changed and now cant get back in. I tried throwing a was_supplicant file on the boot drive and reload the card but nothing came up.

Any ideas how I change the Wi-Fi without Wi-Fi?

Thanks in advance

**Comment by skipfire** [comment]
First I would verify the file name, it should be wpa_supplicant.conf, double check the content of the file and the location you are placing it on the micro-SD card.  After that, I only can think of 3 options...
1. Connect a keyboard and monitor (optionally a mouse as well) and do it through the OS GUI or command line.
2. Setup a temporary wifi with the old configuration (perhaps your phone as a hotspot or the guest config on your WAP) and hope that the Pi connects to that.
3. Rebuild which sucks.

**Comment by ravedoglv** [comment]
I will try number 1 and I’m gonna try 2 today. I brought another router with me. I shutter and number 3 as honestly I don’t remember how I got here. But I’ll try the wiki. I did manage to save the settings. I should have kept notes. I do remember there was a lot of fiddling with serial. 

That you jg…

**Comment by ravedoglv** [comment]
So cute story. I had to connect it to Ethernet, and it turns it DID copy my wpa file from the boot drive but when I looked at it, it had the wrong password, Wah Wah.  Changed it, rebooted and all is good. Whew. Thank you for your help
