### ISSUE TITLE
Generator Comms out - after storm

### ISSUE THREAD

**Issue by interested1204** [jgyates/genmon#872]
Had an unfortunate situation.  Suspected lightning strike near the house, main network switch died.  Genmon RaspPi was being powered over the network.  Original RaspPi 3 B+ won't boot at all.   2 of 3 fuses in ATS blown with some black around them.   Those have been replaced.

Rebuilt a fresh install of Genom on a RaspPi 3 V1.2 and reinstalled with new network switch.  Loopback test works all the way to the molex on the Generac.   Still no communication.

Largely selected Generac because of Genmon, its the best software out there without question.  I suspect the communications in the evolution board are burned out.  I tried a generator test tonight, flipping the main breaker on the ATS.  Generator fired up, but never switched, so I have to suspect the transfer switch controller board was irreparably damaged as well.  

Is there anyway to test the evolution board? 

Where to start with all this?

If I have to replace the Evolution controller will I still be able to use Genmon?

Its not an old install, less than 3 years,  does anyone think Generac would help?

**Comment by jgyates** [comment]
If you have to replace your controller, yes, genmon should work with the replacement. Replacement controllers do not have a serial number burned into the controller like the controllers that come pre-installed with the generator.

Regarding any trouble shooting, if you have validated the loopback works, the just double check your ground connection is good between the pi and the controller. If that connection is bad your serial comms will not work.

If your ground is good and your loopback works, then the last think you can try it to reverse your TX and RX (assuming your built a new RS-232 converter and cable). If the TX and RX is swapped, the loopback will work but it will not communicate with the controller. 

If your ground is good, loopback works, and your pin connections are accurate then the controller's RS-232 interface may be bad. I have seen this happen on occasion and with a lightening strike all bets are off. 

Unfortunately the evolution does not transmit anything unless your first send it data so there is not a way to test it independently. You could measure the voltage on the TX and RX pins of the controller:

Pin 8  - Transmit from Controller, connect to Receive on the Pi
Pin 7  - Received to the Controller, connect to Transmit on the Pi

voltages from diagnostic manual:

<img width="451" alt="Screenshot 2023-03-20 at 8 46 00 PM" src="https://user-images.githubusercontent.com/4513286/226495087-b96ddadd-bde9-447d-aa4f-98be8dea45ba.png">

**Comment by skipfire** [comment]
I had a ground strike last year and my controller got fried.  It locally reported as ok (after rebooting the controller as it was frozen), but the serial was shot and it would not trigger the transfer switch with an outage but the problem was the controller not the ATS (the controller triggers the ATS switch not the ATS itself).

Is the black around the ATS fuses on circuit boards, or just the fuses themselves?  If there is black beyond the fuses I'd be concerned about damage on the circuit board in the ATS, but hopefully it's just a bit of blown smoke that settled.

My Pi was fried so I swapped out all the hardware and imaged the micro-SD card to a new one, but as @jgyates said when I plugged my Pi back into the controller it loaded right up and genmon worked fine.

**Comment by interested1204** [comment]
It was just at the fuses as far as I could tell, I have not pulled the cover on the ATS board itself yet.   I'm going to test those voltages in the morning, and report back.  Thanks everyone, I appreciate it.

**Comment by interested1204** [comment]
Ok, I have confirmed the continuity on the ground wire into pin2.    Pin 8 gets 6.53 and Pin 7 gets 7.7v.  Also, I threw the breaker again, and grounded wire #23 to manually transfer and it doesn't transfer.  In good news though, if we manually (with the bar) transfer to generator while power is out, it will transfer back to utility on its own.   I'm thinking I may end up needing both the controller AND transfer switch module.

![IMG_20230322_085727652](https://user-images.githubusercontent.com/125165631/226938941-ce2be632-dac9-402a-8a40-038b09bbac59.jpg)

**Comment by jgyates** [comment]
I also lost a controller several years ago to lightening.
