### ISSUE TITLE
Finding run hours from Evo2 past registers?

### ISSUE THREAD

**Issue by skipfire** [jgyates/genmon#874]
I had my controller fried last year and I was hoping to recover an approximate of run hours based on logs I sent in last year.  I found the sent mail, but what registers do I need to look at and how do I decode them?  The emails themselves don't directly contain the 3 different run hours listed on the maintenance screen.

**Comment by skipfire** [comment]
Thanks, found c2 so 194 hours and I can guess usage between the date of that log and the replacement.

**Comment by jgyates** [comment]
and you can use the "Additional Run Hours" parameter on the advanced page to fill in the hours from your old controller so genmon will display the total hours on your generator accurately. You probably knew this but wanted to add it for the historical record.

**Comment by skipfire** [comment]
Thanks, I had not seen that but thought it might be hidden on the advanced page.
