### ISSUE TITLE
Getting messages even with delays added

### ISSUE THREAD

**Issue by skipfire** [jgyates/genmon#875]
### Expected Behavior
Notifications do not get sent if they are under the specified delay.

### Actual Behavior
I get notifications about false outages or and communication failures that are well under the delays I've configured.  I have Outage Notification Delay of 10 and Minimum Outage Duration of 10; however I get notifications about outages that are really short (0 seconds, 6 seconds, etc).  This started when I switched to using an ESP32 relay bridge so it may be related to delayed packets or something.

Time: 08:27:13 AM
Date: Sat 08-Apr-2023
Utility Power Restored. Duration of outage 0:00:06

Not sure if it is related, but I have also seen several instances where I get Pushover notifications but not email, especially for short communication failures.

### Steps to Reproduce (including precondition)

Cannot reproduce on demand.

### Your Environment

- Generator Model: 22kW air cooled Evo2
- Genmon Logs: Submitted
- Genmon Version: V1.18.16
- OpenGenSet serial bridge relay to GenMon running on an Ubuntu 22.04.2 LTS VM.

**Comment by jgyates** [comment]
With the current implementation the delay in notification also delays the timed start of the outage, so in your example above with an outage duration of 6 seconds, your actual outage duration is 16 seconds. I have a log wifi distance to cover with my generator (i also use serial over TCP) and there at times that the delay is not sufficient. I use 15 second notification. Wifi retry intervals vs modbus timeouts can be very irritating.

**Comment by skipfire** [comment]
Thanks.
