### ISSUE TITLE
Cable for R3D gauge

### ISSUE THREAD

**Issue by Barrygordon** [jgyates/genmon#878]
I am trying to find a source for the 3 wire cable for my R3D gauge on my buried propane tank to connect it to the Rpi running Genmon. The gauge manufacturer will not sell it to an end user and my propane supplier who leases my the tank won’t supply it. 
any help greatly appreciated. TIA,
Barry Gordon

**Comment by jgyates** [comment]
I will leave this question for other uses as I don't know the answer.

**Comment by jgyates** [comment]
I am going to close this issue but feel free to post any follow up to this thread.
