### ISSUE TITLE
Serial number not appearing in Genmon

### ISSUE THREAD

**Issue by lqallison** [jgyates/genmon#88]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below.

### Expected Behavior

{Please write here}

### Actual Behavior

{Please write here}

### Steps to Reproduce (including precondition)

{Please write here}

### Screenshot on This Problem (if possible)

{Please write here}

### Your Environment

- Genereator Model: {Please write here}
- Generator Registers: {Please write here}
- Genmon Version: {Please write here}

**Comment by lqallison** [comment]
> Expected Behavior
Generator serial number appears on maintenance page.
Actual Behavior
Generator serial number appears on maintenance page. Sorry but number appears now. 
![genmon screenshot](https:
![withoutserialnum](https://user-images.githubusercontent.com/34928443/38647181-02edf6e2-3db9-11e8-8871-6e12099a3e69.jpg)
//user-images.githubusercontent.com/34928443/38647044-528bbf5a-3db8-11e8-92f1-4cd82d9477ee.png)

**Comment by jgyates** [comment]
FYI, I just checked in a change that will mask the email account password on the settings page.
