### ISSUE TITLE
Minor issue:  email error message inaccurate

### ISSUE THREAD

**Issue by DC072012** [jgyates/genmon#886]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below. This is a template so feel free to remove any of this text. Try to include the info below when applicable.

***NOTE:*** If you are having issues with your serial connection, please read this page before posting:

https://github.com/jgyates/genmon/wiki/3.6---Serial-Troubleshooting

If you are having other issues, please see the following page:

https://github.com/jgyates/genmon/wiki/3.5---General-Troubleshooting

You can search past issues by removing the "is:open" keywords from the search window and adding any keywords that are relevant to your issue.

If you need to send you logs and registers to the developer, if your email is setup and working properly you can click send your logs on the About page in the web interface.

### Expected Behavior

Email that is sent for “Inspect Battery” error should say “Inspect Battery”

This was addressed here but the code may have somehow regressed:

https://github.com/jgyates/genmon/issues/347#issue-551532062

### Actual Behavior

Email says “Check Battery:
Time: 05:45:29 PM
Date: Sat 22-Apr-2023

Current Alarm: Check Battery
System In Alarm: 0001:[00000014](tel:00000014)

Status : 

    Engine : 
        Switch State : System in Alarm
        Engine State : Off - Ready
        System In Alarm : Check Battery
        Battery Voltage : 13.00 V
        RPM : 0 
        Frequency : 0.00 Hz
        Output Voltage : 0 V
        Active Rotor Poles (Calculated) : 0 

    Line : 
        Utility Voltage : 233 V
        Utility Max Voltage : 245 V
        Utility Min Voltage : 226 V
        Utility Threshold Voltage : 156 V

    Last Log Entries : 

        Logs : 
            Alarm Log : 05/28/22 11:30:12 Over Voltage 
            Run Log : 04/22/23 11:42:11 Stopped - Auto 

    Time : 
        Monitor Time : Saturday April 22, 2023 17:45:28
        Generator Time : Saturday April 22, 2023 17:46

To clear the Alarm/Warning message, press OFF on the control panel keypad followed by the ENTER key

### Steps to Reproduce (including precondition)

{Please write here}

### Screenshot or Pictures relating to the problem (if possible)

![image](https://user-images.githubusercontent.com/51464940/233851037-078f032a-48d3-4770-b0c9-073a7d7a0747.jpeg)

### Your Environment

- Generator Model: 5882-0
- Genmon Logs: Logs submitted
- Genmon Version: V1.18.17

**Comment by jgyates** [comment]
the code supports one set of displayed values for Alarm codes but separate set of displayed values for the displayed values for the codes embedded in the log data. To be consistent with the newer models (Evolution 1.0 and 2.0) "Check Battery" is displayed for the alarm code 0x14, instead of "Inspect Battery" for Nexus models.
