### ISSUE TITLE
PowerPact Generator and 0J0064 Controller

### ISSUE THREAD

**Issue by hccunion** [jgyates/genmon#888]
Has anyone successfully connected to the PowerPact Generator and 0J0064 controller? The connector is not the same serial or Molex as the new controllers (we have the pintsize.me pi and hat). Attached are pictures of the bottom of the controller, and the generator info. We have several of these little guys. Thanks! Spencer
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/121971097/234428810-a912e148-8960-42f1-90f8-150934ab0c89.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/121971097/234428823-7545ca10-02c7-4c98-af51-d717e0042820.png)

**Comment by hccunion** [comment]
After some reading of closed comments, maybe our controller is NOT the PowerPact, even though the generator is labeled PowerPact?

**Comment by jgyates** [comment]
Is it one like this: https://norwall.com/content/norwall-pim-app/assets/document/733_5837_specs2.pdf

Looking at the spec sheet and the data online for the 0J0064 controller, I don't think this will work with genmon as that controller is not an Evolution or Nexus type of controller.

**Comment by hccunion** [comment]
Thanks @jgyates - do you think the controller doesnt have a serial output for genmon to read, or just not developed yet?

**Comment by jgyates** [comment]
I don't think it has a serial output.

**Comment by hccunion** [comment]
ok, thanks! is there a way to be sure, or test to be sure? Im willing to try a custom cable, if you think it CAN do it.

**Comment by jgyates** [comment]
You can send a picture of the front and back to help be sure. At the moment I don't think it is possible, but I will do a some more digging to validate.

**Comment by hccunion** [comment]
Sounds good - I will get some better pictures today, thanks!

**Comment by jgyates** [comment]
I am going to close this issue but feel free to post any follow up info to this thread.
