### ISSUE TITLE
H-100 Setup & Parts List

### ISSUE THREAD

**Issue by star-glider** [jgyates/genmon#889]
There don't seem to be too many examples of H-100 installations here, so I figured I'd share mine in case it helps anyone. The nice thing about the industrial controller is that it has a native DB9 port; the irritating thing is that it's mounted such that you can't close the cover. I saw one guy here physically moved the port, which seemed like a little too much work. :) I just got a simple right-angle adapter to solve the problem, and fortunately I found one that has the right "directionality" to it. The cover now serves the semi-helpful purpose of holding it in the port. Here's what it looks like all done:

![IMG_4210](https://user-images.githubusercontent.com/121585629/235329848-a2d634b2-8176-47e1-bde3-5ac0055992af.jpg)
![IMG_4211](https://user-images.githubusercontent.com/121585629/235329854-c0ca31fb-c40e-4fc8-9731-dc2e111490d3.jpg)
![IMG_4213](https://user-images.githubusercontent.com/121585629/235329855-19f5fb88-1ff5-4142-867e-f14c30acbafd.jpg)
![IMG_4214](https://user-images.githubusercontent.com/121585629/235329857-d24f0802-b2ba-4f8b-b572-ac389abf734b.jpg)

I hope this helps any fellow industrial folks!

Parts list:
Right-angle serial adapter: https://www.amazon.com/dp/B001S2PYV4
Serial cable: https://www.amazon.com/dp/B00008VF6L
RS232 <> TTL board (I liked this one because it had through-hole as well as pads): https://www.amazon.com/dp/B07BJJ3TZR
Simple buck converter (I'm powering from battery): https://www.amazon.com/dp/B07Y2V1F8V
Cheap fuse holders: https://www.amazon.com/dp/B0813Q4S6P
Switch so I can restart the pi after powering it off: https://www.amazon.com/dp/B074V5WHSX
Enclosure: https://www.amazon.com/dp/B08PP1W8Q3

Thank you to jgyates for such great software and for helping me through a weird dependency issue while I was setting this up. This has been a fun project.

**Comment by jgyates** [comment]
Nice! Thanks for the details

**Comment by jgyates** [comment]
I added a link to this thread in the wiki: https://github.com/jgyates/genmon/wiki/Appendix-G-Generac-H-100,-G-Panel-and-PowerZone-Controllers
