### ISSUE TITLE
Feature Request: Add ability to upload photos to service journal

### ISSUE THREAD

**Issue by northportio** [jgyates/genmon#896]
Hi there,

I was noting service done on generator and I would like to be able to add photos to the service journal.

Just wondering if something like this can be added/is possible since AFIK, the service journal is JSON based.

Thank you.

**Comment by jgyates** [comment]
I have added this to the list.

https://github.com/jgyates/genmon/blob/master/feature_requests.md

I will need to think about the implementation and weigh it against maintainability and priority of other features but it sounds like a good idea. I will update this thread once this is implemented.

**Comment by jgyates** [comment]
https://github.com/jgyates/genmon/blob/master/feature_requests.md
