### ISSUE TITLE
LogRotation for log files?

### ISSUE THREAD

**Issue by steven-pozarycki** [jgyates/genmon#90]
Is there a way to do automatic log rotation of the LogFile.csv at the end of the day? (If I have this running for a long time, I'd like to have a log file per day that I could send off somewhere and archive. Some cool things could be done with archived historical data over a long period of time outside of this project.)

**Comment by jgyates** [comment]
This is built in via the logrotate program in Linux. You can configure what logs are rotated by the settings in /etc/logrotate.conf and the files in /etc/logrotate.d/*

https://www.tecmint.com/install-logrotate-to-manage-log-rotation-in-linux/

logrotate will also rotate files that do not end in .log:
https://serverfault.com/questions/196843/logrotate-rotating-non-log-files
