### ISSUE TITLE
Failure to update GenMon

### ISSUE THREAD

**Issue by rwskinner** [jgyates/genmon#906]
GenMon doesn't update.  
About page shows - You are not running the latest version.
    Current Version: V1.18.16
    New Version: V1.18.17

Click Update, it says downloading for about 10 seconds, then reboots and the same version is listed.
Looking at the logs really didn't show me anything but I submitted them to you anyways.

Any ideas where to look next?

**Comment by skipfire** [comment]
I had to log in with ssh and manually do a git pull, then restart genmon.

**Comment by rwskinner** [comment]
#876 worked fine with no issues and no errors.

cd genmon
./startgenmon.sh stop
./genmonmaint.sh -u
./startgenmon.sh restart

**Comment by jgyates** [comment]
FYI:   An update has been posted that may resolve this upgrade issue in the future. [See this thread for more info](https://github.com/jgyates/genmon/issues/920).
