### ISSUE TITLE
Enhanced Exercise Time - What are the supported firmware versions?

### ISSUE THREAD

**Issue by jarocht** [jgyates/genmon#907]
The 'Enhanced Exercise Time' option on the settings page says "firmware version dependent."
What are the supported firmware versions?

Can I enable this to test if it works without risk? The wording currently implies I should not enable unless I know for sure its supported.

I am looking to extend the exercise duration from the standard runtime.

**Comment by jgyates** [comment]
I don't know the exact firmware versions however it should not hurt to try it out. This feature has been in the software for at least 4 years so the firmware would have to be quite old version of the Evolution to not have this feature. If you firmware is not supported the non-weekly exercise time (if enabled an set) will not be displayed in the web interface. The older firmware only used weekly exercise times.
