### ISSUE TITLE
Text messages to iPhone

### ISSUE THREAD

**Issue by Barrygordon** [jgyates/genmon#916]
I am looking for a way to have genmon send notifications as text messages to my iPhone.  Is there an add-on that does that.  If so what do I need and how do I proceed?  If possible restrict which notifications are sent e.g. generater start and stop times and outage notifications.

TIA,
Barry Gordon

**Comment by madisdev** [comment]
There is pushover notification available.

**Comment by jgyates** [comment]
The Pushover service is free, there is the voice over IP add on, the twillio add (gensms) has some issues as twillio is changeing their cost structure. This thread has some details on twillio and which genmon add on programs are good alternatives.

https://github.com/jgyates/genmon/issues/912
