### ISSUE TITLE
MQTT Integration JSON for Numerics doesnt include temperature sensors

### ISSUE THREAD

**Issue by chrkov** [jgyates/genmon#917]
### Expected Behavior

Enabling 'JSON for Numerics works as expected, but doesn't convert the temperature sensors.

![image](https://github.com/jgyates/genmon/assets/57808614/6ac8763f-a053-46b1-8ca0-cacae7f8c4c8)

### Actual Behavior

Works as if 'JSON for Numerics is off'

### Steps to Reproduce (including precondition)

Turn on 'JSON for Numerics' and look at temperature sensors

### Screenshot or Pictures relating to the problem (if possible)

![image](https://github.com/jgyates/genmon/assets/57808614/1e5d425a-e476-4c8c-b5e3-573c7eb946c0)

### Your Environment

- Generator Model: 16kw
- Genmon Logs: Submit via the About page
- Genmon Version: {Please write here}

**Comment by jgyates** [comment]
Good catch. That was an oversight on my part. I checked in an update that corrects this issue. The version number has not changed. Let me know if you have any issues.

**Comment by chrkov** [comment]
Thanks.   I am currently on 1.18.17 software.   How to I get the fix installed if the version doesn't change?

**Comment by jgyates** [comment]
Just go to the about page and click the update button. the software will update and restart, but the version number will not change.

**Comment by chrkov** [comment]
Did that, but seeing the same outcome as before.
![image](https://github.com/jgyates/genmon/assets/57808614/205ad4db-aa5a-4a5a-b672-4f4615ec836b)

**Comment by jgyates** [comment]
Sometimes github takes a while to update. To validate you have the latest you can check the file date of ./genmon/genmonlib/controller.py. Log into the pi via ssh and type:

    cd genmon
    ls -la ./genmonlib/controller.py 

You should some an output with todays date. If the date if from before today then you should wait and try it again later. The output I have on my system is this:

    -rw-r--r-- 1 pi pi 122934 Jun 29 15:49 ./genmonlib/controller.py

The time and date is from when I performed the update on my pi. If the update is not posted in the github mirror you are using then it would be from an earlier date.

**Comment by chrkov** [comment]
My file shows a date of May 3rd right now.   I will try again later and check the date again.  

Thanks!

**Comment by chrkov** [comment]
FYI.   Still not updating.   I just tried again today to do the upgrade and my file still shows May 3rd.

**Comment by jgyates** [comment]
Can you describe how you are updating the software? The changes that I checked in are showing up from the web interface:

https://github.com/jgyates/genmon/blob/c2b611f1bfd71c84cb2e3b0aba76b6ee9b0bbb31/genmonlib/controller.py#L2088

If you are updating the software and changes are not occurring this is either an issue with github (it works when I update) or a local issue with you pi.

**Comment by chrkov** [comment]
I am going to the PI via chrome at http://192.168.151.163:8000
Clicking on 'About'
Clicking on 'Upgrade to latest version'

It does have access to the internet.  I can ping 4.2.2.2.  DNS also works as I can ping google.com.  Resolves to 142.251.40.206

**Comment by jgyates** [comment]
try logging in to the pi via ssh and then type:

      cd genmon
      ./genmonmaint.sh -u

Then when prompted type "y" for Yes to update to the latest. Post your output here.

If you type this command:

       grep "popitem" ./genmonlib/controller.py 

It will output nothing if the update is not there. If the update is there it will output this:

      TempKey, TempData = TempDict.popitem()

**Comment by chrkov** [comment]
That worked.   I tried one more time from the gui and still that date on that file remained as May 3rd.

Did it from the CLI and it updated and is showing the json on the temp sensor now.

Here is the output if you still wanted it.

'''
genmonpi@genmon:~/genmon $ ls -la ./genmonlib/controller.py
-rw-r--r-- 1 genmonpi genmonpi 121690 May  3 19:22 ./genmonlib/controller.py
genmonpi@genmon:~/genmon $  ./genmonmaint.sh -u
This script will update genmon to the latest version from the github repository. This script requires internet access. If you have modified any files in the genmon directory, they will be overwritten. Configuration files in the configuration directory will not be overritten.  Continue? (y/n)  y
Updating genmon...
remote: Enumerating objects: 109, done.
remote: Counting objects: 100% (109/109), done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 109 (delta 63), reused 94 (delta 48), pack-reused 0
Receiving objects: 100% (109/109), 1009.07 KiB | 4.50 MiB/s, done.
Resolving deltas: 100% (63/63), completed with 23 local objects.
From https://github.com/jgyates/genmon
   4261395..c2b611f  master     -> origin/master
Updating files: 100% (264/264), done.
HEAD is now at c2b611f V1.18.17
Done.
genmonpi@genmon:~/genmon $ ls -la ./genmonlib/controller.py
-rw-r--r-- 1 genmonpi genmonpi 122967 Jul  2 22:10 ./genmonlib/controller.py
genmonpi@genmon:~/genmon $
'''
![image](https://github.com/jgyates/genmon/assets/57808614/97cb477c-b315-4d67-84af-3b2f6c3030aa)

**Comment by chrkov** [comment]
Ok.  I just sent the logs over to you.

**Comment by jgyates** [comment]
I looked at your logs and did some digging. I *think* I resolved the issue but you may have to do one more manual upgrade to get the fix. [See this thread for more info](https://github.com/jgyates/genmon/issues/920).
