### ISSUE TITLE
Settings Screen - Outbound Email Settings

### ISSUE THREAD

**Issue by krisasmith** [jgyates/genmon#92]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below.

### Expected Behavior

When i update the 'sender account' and 'SMTP Server SSL Enabled' it should update

### Actual Behavior

After making a change, saving, and then refreshing the page it goes back to the original setting.

### Steps to Reproduce (including precondition)

Change the 'sender account' and 'SSL Enabled' , click save, refresh the page and the account is set back to no-reply@gmail.com and SSL is off.

### Screenshot on This Problem (if possible)

Current settings
![image](https://user-images.githubusercontent.com/27901356/38741507-0f1c80f0-3f08-11e8-9348-ae0007e37b75.png)

My changes

![image](https://user-images.githubusercontent.com/27901356/38741557-2ab0bf52-3f08-11e8-93f7-df787b04ec22.png)

Click save

![image](https://user-images.githubusercontent.com/27901356/38741577-34b5ba66-3f08-11e8-9fc2-3398fde3723f.png)

Saving...

![image](https://user-images.githubusercontent.com/27901356/38741593-3c5cb210-3f08-11e8-9d25-82d5d64e05fc.png)

Looks good

![image](https://user-images.githubusercontent.com/27901356/38741606-444ecd14-3f08-11e8-92be-2364a2fc6036.png)

Click on status tab and then back to settings

![image](https://user-images.githubusercontent.com/27901356/38741638-552fd4fc-3f08-11e8-9557-bb3cd25c352d.png)

Here is /etc/mymail.conf

![image](https://user-images.githubusercontent.com/27901356/38741688-75681356-3f08-11e8-9315-c61c58f1c163.png)

As far as i can tell, SSL is enabled (gmail requires it). Is this possibly a permissions problem?

![image](https://user-images.githubusercontent.com/27901356/38741860-f9d98bd8-3f08-11e8-9004-9ea13e5e75a2.png)

### Your Environment

- Genereator Model: {Please write here}
- Generator Registers: {Please write here}
- Genmon Version: {Please write here}

**Comment by jonathanpisarczyk** [comment]
I wasn't able to get SSL working unless using port 465 with GMAIL.  I suspect gmail only accepts TLS on 587 now.

**Comment by jgyates** [comment]
This appears to be related to this issue (https://github.com/jgyates/genmon/issues/91). Looking at both of them now.

**Comment by jgyates** [comment]
An update has been checked in to address this. See https://github.com/jgyates/genmon/issues/91

**Comment by krisasmith** [comment]
The code change seems to work however i still am unable to update the 'sender account'. The emails are coming from the correct address, the setting just does not reflect that.

**Comment by krisasmith** [comment]
I found the problem, i had an older version of the mymail.conf file, i see you added a new parameter (sender_account) that i didn't have in my file. Should i expect that missing parameter to be written by the UI when clicking save?

**Comment by jgyates** [comment]
OK. I also found a problem related to the password. The masking of the password was added but this caused th pw not to be save properly, this change is coming in the next few min...

**Comment by jgyates** [comment]
I checked in a change to genserv.py. This change correct a problem saving the email password.

**Comment by jgyates** [comment]
It should save the missing parameter.

**Comment by jgyates** [comment]
I checked in a final update that handles the bug, but does not force a refresh. Let me know if you still have any issues.
