### ISSUE TITLE
Genmon upgrade issue / new version

### ISSUE THREAD

**Issue by jgyates** [jgyates/genmon#920]
I am posting a new version of genmon (V1.18.18) that has a few new features and fixes. One issue that I have addressed is related to a problem with genmon not upgrading on some systems. I believe I have tracked this down to the file permissions on the local repository are not in an expected state. I have a fix for this in the new version, however you have to be able to upgrade to get the version. ***If you attempt to upgrade your software and it does not then do the following***:

1) Log into your pi via ssh, then type:

       cd genmon
       sudo ./genmonmaint.sh -u

Then enter 'y' for Yes when prompted. When this is complete restart genmon with this command:

      ./startgenmon.sh restart

Refresh your web browser and you should see the new version on the About page. Future upgrades should work as expected.

If clicking the upgrade button on the About pages works for you then this issue was not present on your pi so just continue as in the past.

**Comment by mxplea10** [comment]
Thanks... I upgraded with the steps above.

**Comment by w-u-2-o** [comment]
Update through the web interface failed. Used the above procedure and am now at .18. Thanks!

**Comment by wtnh** [comment]
The above procedure worked flawlessly for me too. Thanks!
