### ISSUE TITLE
Interesting - Generac offering ecobee integration

### ISSUE THREAD

**Issue by wtnh** [jgyates/genmon#921]
Since I am an ecobee user, I thought this was interesting: (https://support.ecobee.com/s/articles/Setting-up-and-using-the-Generac-Mobile-Link-integration-with-your-ecobee-smart-thermostat?utm_source=newsletter&utm_campaign=q223_mobilelink&utm_medium=email&utm_content=1_cta)

There is an ecobee python API that could make for an interesting Genmon add-on: https://pypi.org/project/python-ecobee-api/

The devil is in the details, of course. :-)

**Comment by jgyates** [comment]
I added this to the feature list:

https://github.com/jgyates/genmon/blob/master/feature_requests.md

I will update this thread when complete.
