### ISSUE TITLE
moved and transistioning genmon from 11kW to 22kW evolution 2.0  - any tips where 8 pin input connector is located?

### ISSUE THREAD

**Issue by bmf7777** [jgyates/genmon#928]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below. This is a template so feel free to remove any of this text. Try to include the info below when applicable.

***NOTE:*** If you are having issues with your serial connection, please read this page before posting:

https://github.com/jgyates/genmon/wiki/3.6---Serial-Troubleshooting

If you are having other issues, please see the following page:

https://github.com/jgyates/genmon/wiki/3.5---General-Troubleshooting

You can search past issues by removing the "is:open" keywords from the search window and adding any keywords that are relevant to your issue.

If you need to send you logs and registers to the developer, if your email is setup and working properly you can click send your logs on the About page in the web interface.

### Expected Behavior

{Please write here}

### Actual Behavior

{Please write here}

### Steps to Reproduce (including precondition)

{Please write here}

### Screenshot or Pictures relating to the problem (if possible)

{Please write here}

### Your Environment

- Generator Model: {Please write here}
- Genmon Logs: Submit via the About page
- Genmon Version: {Please write here}

**Comment by skipfire** [comment]
Your new one may have a MobileLink plugged into it already, but it's on the underside of the controller.  If there isn't something plugged in there may be a sticker over the port and another port with no connector next to it.  If you can't find it, post a picture of the underside of your controller.

**Comment by bmf7777** [comment]
It looks like there is a wifi module … I’m going to unplug it as suggested and give it a try after I get a 12v battery to usb cable Dan Marotta+1949.466.7611If this email isn't intended for you, please delete it.On Jul 24, 2023, at 1:17 PM, Jon R. Helms ***@***.***> wrote:﻿
Your new one may have a MobileLink plugged into it already, but it's on the underside of the controller.  If there isn't something plugged in there may be a sticker over the port and another port with no connector next to it.  If you can't find it, post a picture of the underside of your controller.
