### ISSUE TITLE
Setting up Genmon with Gmail (inboud and outbound)

### ISSUE THREAD

**Issue by mac1-131** [jgyates/genmon#933]
I didn't see too much detail on the nuts and bolts of setting up Genmon for email, so wanted to offer the following. Maybe you want to add it to your wiki.

Google has been forcing on 2-Step Verification (MFA) for non-enterprise accounts for a while now, and this gets in the way of IoT devices sending emails with a simple username/password authentication. Fortunately, they have provided something called App passwords which creates a complex password defined by Google that will allow most IoT devices to function. If your Gmail has 2-Step verification turned on, these steps will help you get it set up. The second section will also fill-in the gaps on how to make inbound generator command emails work with Gmail (process would be similar for other IMAP clients).

### Outbound Emails from Genmon

1. Sign-in to the Google account you want to use on a PC browser
2. Select your account picture and click on _Manage you Google Account_
3. Click the _Security_ tab, then scroll down and click on _2-Step Verification_
4. Turn it on if it is not already on (no way around this, if you really can't use MFA then stop here)
5. Scroll down to the bottom and click on _App passwords_
6. Select an app (Other is good) and give it a name (Genmon is good, or gmail SMTP is good, you can use this password for all IoT devices that need to send emails, not just Genmon)
7. Click on _Generate_ and copy the password to your clipboard, or write it down (even though it tells you not to write it down, do it anyway, you will need to put it in your Genmon Settings
8. Log into Genmon and click on the _Settings_ link
9. Scroll down to _Outbound Email Settings_ and turn it on
10. Enter the email account you are using, the one you generated the application password in
11. Enter the application password you generated in your Google account settings
12. Sender address can be no-reply@gmail.com or you can put in your email if you want, if you have trouble getting emails delivered to your inbox directly, try putting your email address as the sender
13. Sender name can be whatever you want, Genmon is fine
14. SMTP server is smpt.gmail.com
15. Leave port at 587
16. Click the _Test Email Settings_ button, you should receive a test email
17. Click the _Save_ link at the bottom of the page, Genmon will restart and you should get an email in a couple minutes saying that Genmon was started

### Setting up Inbound Emails to Send Generator Commands

1. In Genmon _Settings_, just turn it on and imap.gmail.com is fine, and the default folders are fine
2. You must create those folders in the Gmail account yourself, and create a filter to move received emails to that folder. Be advised Gmail now calls folders "Labels" so your are actually working with Labels in Gmail
3. Go to Gmail for that account, and on the left side click the + next to Labels
4. Create a Label called Generator and do not nest it under any other labels. By default, IMAP access for this folder will be on
5. Click the + again, and create another label, nest it under Generator, and call it Processed
6. Now you need a filter to move any received emails to the Generator folder. Click the _Settings_ wheel at the top right of your Gmail, and click on _See all settings_
7. Click the _Filters and Blocked Addresses_ tab
8. Scroll down and click the _Create a new filter_ link
9. In the Subject line, enter **generator:** and click _Create filter_
10. Under When a message is an exact match, check the _Apply the label box_ and click the drop-down arrow and select Generator
11. Click the blue _Create filter button_
12. Send a test email from any email address to your Gmail email address you set this up on with **generator: status** in the subject line and you should get a response. The email does not need any text, just the subject line
13. You can now use the rest of the commands as shown in the wiki, or send **generator: help** for a list of commands

**Comment by jgyates** [comment]
Good idea. In addition you can set the filter to only move emails from a specific email address into the Generator folder.
