### ISSUE TITLE
Generac wifi not working with molex bypass

### ISSUE THREAD

**Issue by notms** [jgyates/genmon#940]
Hello Genmon community. I have recently got the genmon softwarw working with RS-232 and also used a molex with a bypass for generac wifi. The weird part is I can’t get wifi for generac working when using molex, direct it works fine. I followed molex connection directions for revolution 2 with wifi. Any help would be appreciated if you have seen it before. I used pi2 as ground, initially had pin 1 for 5volts but was unstable for raspberry w2 and went direct from pattern. Should I got for pin4 for ground on rev 2, I though it was usually if pin4 doesn’t work default to pin2, here I defaulted right away to pin2.

### Expected Behavior

Generac wifi working

### Actual Behavior

Generac wifi not working

### Steps to Reproduce (including precondition)

{Please write here}

### Screenshot or Pictures relating to the problem (if possible)

![IMG_3806](https://github.com/jgyates/genmon/assets/64244399/08e396a3-e116-4737-acc7-87e86fb4bf0e)
![IMG_3809](https://github.com/jgyates/genmon/assets/64244399/4518f0c5-7613-4ea7-b58e-c4cfd7e43959)

{Please write here}

### Your Environment

- Generator Model: {Please write here}
- Genmon Logs: Submit via the About page
- Genmon Version: {Please write here}

**Comment by skipfire** [comment]
Can you post a picture of, or link to, the bypass cable you mention?

**Comment by notms** [comment]
Unfortunately I am away from the generator, will be back in a couple of days to post, I followed the molex cable making diagram from the wiki page.

**Comment by liltux** [comment]
According to the display it is not connected to the WiFi network.  One thing to check is if there is a green led blinking on the back side of the Mobile Link Antenna inside the generator.  This would indicate connection status and also if the power supply to the module is good.  Also, how strong is your WiFi signal form your house to the generator?  The Mobile Link antenna requires a better signal than most other devices.

**Comment by notms** [comment]
Here are the pics. I am thinking logically and would think that some level of power would
Need to be provided to the wifi on generac. The wifi has four connections I am only connected to two of them, I am assuming other is ground and power. I think I need power. When connect with the original connector to wifi I see a green light come on the wifi module, with my bypass I don’t![IMG_3905](https://github.com/jgyates/genmon/assets/64244399/38738614-f58e-48db-9c1a-3e6dcc979c49)
![IMG_3908](https://github.com/jgyates/genmon/assets/64244399/0a857add-95c1-4cc9-8e9b-824a1e61077a)
![IMG_3909](https://github.com/jgyates/genmon/assets/64244399/6321a89e-b0fd-4613-b683-12273926b3de)
![IMG_3911](https://github.com/jgyates/genmon/assets/64244399/a4b6f92f-09be-4859-8246-1a043bd11845)
![IMG_3910](https://github.com/jgyates/genmon/assets/64244399/0437ba3d-8fe2-43b6-9687-bbcee257f93f)

**Comment by skipfire** [comment]
You do need all 4 wires, the other two are power and ground.  The MobileLink WiFi also uses RS485, so if you followed GenMon wiring instructions you are probably connecting the wrong wires as GenMon uses the RS232 wires.  Under the RS232 wires are 12v and ground, under the RS485 wires are the 5v and ground and my MobileLink uses the 5v, ground, and the 2 RS485 pins matching the pinout on your MobileLink.  Can you get a picture of the entire bypass cable so we can see how the splices are setup?

**Comment by jgyates** [comment]
I am going to close this issue for now but feel free to post to this thread if you have any follow up questions or status.
