### ISSUE TITLE
Genmon MQTT Start Stop Commands

### ISSUE THREAD

**Issue by Daniel-dev22** [jgyates/genmon#947]
Awhile back I opened this issue https://github.com/jgyates/genmon/issues/893#issuecomment-1542137221

And I was curious about the mqtt commands to start/stop the generator as the wiki is a bit confusing.

From the wiki on commands
> The setremote command issues commands directly to the controller. Start and stop commands should be back to back, i.e. is is not recommended to issue start followed by starttransfer, you should have a stop after each start command. Also, when the starttransfer command is used, once a stop command is issued the controller will set the transfer switch back to "utility" but the generator will continue to run in "cool down" mode for few minutes. This is normal and the behavior is controlled by the controller.

What does that mean issue a start then stop command? Isn't that going to start then stop the generator? 

### Your Environment

- Generator Model: {Generac 24Kw}
- Genmon Logs: Submit via the About page
- Genmon Version: {1.18.8}

**Comment by jgyates** [comment]
see https://github.com/jgyates/genmon/issues/893
