### ISSUE TITLE
Automatic feedback address - information needed only 

### ISSUE THREAD

**Issue by steve-bailey1** [jgyates/genmon#95]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below.

### Expected Behavior

email the software team the feedback notices

### Actual Behavior

none at the moment.  Need to know the email domain of the target address to allow relaying via my mail servers

### Steps to Reproduce (including precondition)

turning on the auto feedback option

### Your Environment

- Genereator Model: {Please write here}
- Generator Registers: {Please write here}
- Genmon Version:  1.6.2

**Comment by jgyates** [comment]
the email domain is gmail.com. The full email address used is generatormonitor.software@gmail.com

**Comment by steve-bailey1** [comment]
Thank you.  I just turned it on and it looks like it went through.
