### ISSUE TITLE
Turned off Web Security and now can't connect to dashboard

### ISSUE THREAD

**Issue by dhar2024** [jgyates/genmon#986]
I am getting "Internal Server Error"  It all worked fine when it was first setup and then I turned on web security with Multi-factor authentication and all worked well.  I then turned it off to go back to the http://192.XXX.X.XXX:8000/ and get the Internal Server Error - The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.  Can someone advise on how to fix this?

Thanks

**Comment by jgyates** [comment]
Have you tried rebooting your pi?

Also, can you show the last couple of lines of the file /var/log/genserv.log

This is the log file for the web server.

**Comment by dhar2024** [comment]
Yes I rebooted the PI. Hopefully you can see this. 
![log](https://github.com/jgyates/genmon/assets/153125750/ef0efda4-0785-474f-8e9d-e617622f2027)

**Comment by dhar2024** [comment]
Sorry about that the Port is 8000

**Comment by dhar2024** [comment]
The other thing I will add is that when I reboot, I do get the emails saying "Generator Monitoring started"

**Comment by jgyates** [comment]
Can you log into the pi with ssh?

**Comment by dhar2024** [comment]
Yes I can. I just logged in with my PC

**Comment by jgyates** [comment]
I got your logs, except for not serial communications, everything looks normal. the web interface will take more time to come up if the serial comms are not connected, but you should not get an internal error message.

Let's look at what the server and browser thing is happening in terms of the web traffic:

log in via ssh and stop genmon:

       cd genmon
       ./startgenmon.sh stop

Then we will start genmon.py manually, loading it in the background, then we will start genserv.py manually in the foreground so we can see the output. Once you load genserv.py then refresh your broswers with the link you are using to access the web interface. The following screen shot is what you should do:

<img width="794" alt="Screenshot 2023-12-06 at 5 10 03 PM" src="https://github.com/jgyates/genmon/assets/4513286/4291bf31-935e-4ac0-aba8-b231c5bd2050">

type "Ctrl+C" to stop genserv.py then type "sudo reboot" to restart your pi (this is easier to do this than to kill the genmon process in the background).

Once the pi has rebooted, make sure genmon has started and then start Chrome on your PC and go to the Chrome settings menu and go to "More Tools" -> "Developer Mode". On the developer mode screen on the left you will see a window with multiple tabs, select the "Network" tab. then refresh your browser to the address used to access genmon. It should look like this:

<img width="1278" alt="Screenshot 2023-12-06 at 5 11 35 PM" src="https://github.com/jgyates/genmon/assets/4513286/1784dafc-256f-4734-a970-19430e382f02">

Send a screen shot of both of the above steps.

**Comment by dhar2024** [comment]
tried to do step 1 and got this:
![image](https://github.com/jgyates/genmon/assets/153125750/24b11b2a-7e9a-4963-97e4-0710b24168c7)

**Comment by jgyates** [comment]
Has this system been attached to a generator before and working or is this a new install? The above message indicates that either you have not run the install script or your file system may be corrupt. crcmod is a python library used to calculate modbus CRC. It is requried but it is saying that it is not installed.

**Comment by dhar2024** [comment]
This has not been attached to a generator yet.  My generator is at a remote location and I am trying to get it all setup before I take it there.  The remote location uses the same named wifi network.  I usually set things up here and take them there and they automatically connect. Everything worked as it should before I toggled web security off.

**Comment by jgyates** [comment]
Have you ran the install script?

**Comment by dhar2024** [comment]
I just order the preload open from pintsizeme and connected it wifi. My understanding is that is was ready to work once I connected to wifi.

**Comment by jgyates** [comment]
ok. Your log files show that you are running bookworm, which is a managed python environment so we need to run another step first. Lets repeat the steps again except run this before (from the genmon directory):.

      source ./genenv/bin/activate

once you run the above command then run everything like the screen shot  above:

      sudo python3 genmon.py &
      sudo python3 genserv.py

Then refresh the browser.

**Comment by dhar2024** [comment]
Here is what I get: 
![image](https://github.com/jgyates/genmon/assets/153125750/7b87f9ef-9ca3-422c-b096-cd3c01c15d33)

**Comment by dhar2024** [comment]
I was able to reboot but am still getting the Internal Server error.  Still showing monitoring on the reboot

**Comment by jgyates** [comment]
OK. This is the source of the problem. The Flask library is crashing for some reason. This is the library that is installed by the install script that handles all of the web server functionality. I am not sure why this is happening but we can try a few things to attempt to correct the problem. Your pi must be able to access the internet via your network for this next step as we will uninstall then reinstall the Flask library. The reinstall will pull the Flask from the pip repository on the internet.

after a reboot first stop genmon

      cd genmon
      ./startgenmon.sh stop

Next we will try to uninstall / reinstall the Flask library:

       source ./genenv/bin/activate
       sudo ./genenv/bin/pip3 uninstall Flask

Then reinstall Flask
      
      sudo  ./genenv/bin/pip3 install Flask
      deactivate

If you are prompted for yes / no, type y for yes.

Once this is complete then lets restart genmon and see if you still get the internal server error.

If that does not work we can do a complete reinstall of genmon.

**Comment by dhar2024** [comment]
The uninstall and reinstall of Flask went great. I am still getting the Internal Server Error unfortunately

**Comment by skipfire** [comment]
Based on the error message, what about editing the config file to set `usehttps=false`?  That looks like it would skip where flask is having the SECURE_KEY value set.

**Comment by jgyates** [comment]
I think I figured out the problem. The issue is that Flask will crash if multifactor authentication is enabled but HTTPS is not. To get you back running you can edit the file /etc/genmon/genmon.conf like this

     sudo nano /etc/genmon/genmon.conf

Near the bottom of the file you will see a like like this


      usemfa = true

change it to 

      usemfa = false

save the file by typing Ctrl+X then y for yes. Then restart genmon

Let me know if this resolves you issue. I have never seen this before. I will add a check to make sure this does not happen.

**Comment by dhar2024** [comment]
PROBLEM SOLVED!!!  Should I not use MFA in the future? Thank you!!!

**Comment by jgyates** [comment]
I checked in an update to fix this issue. If you upate to the latest and restart it should fix your problem

If you update form the About page you should not see this issue again. You can use MFA, but it is only active if HTTPS is enabled. The web interface shows this dependency, but the underlying code in genmon would allow it and that is an invalid setting. the new code I just checked in will not use MFA if HTTPS is not enabled. 

Thanks for help me find this.

I am going to close this issue but feel free to post any follow up status or related questions to this thread.
