### ISSUE TITLE
Incorrect pin reference in gengpio.py for ER_PITEMP

### ISSUE THREAD

**Issue by gkefsen** [jgyates/genmon#987]
https://github.com/jgyates/genmon/blame/a92b9c504276cb8f3ef700c996de505c8b713a21/addon/gengpio.py#L366-L373

I have been working with the project for a couple weeks now to set up a deployment for my brother.  I have been looking for an excuse to work with a Raspberry Pi and this project has been very rewarding so far.  I'm still working on the bench and have yet to hook up the build to the gen. 

I'm using a RPi zero 2 W, with Raspberry Pi OS, 64-bit lite.  I was thinking I may want to use a fan to cool the CPU and started with fancontrol (found on howchoo.com).  I got it working on a breadboard and then found similar support in the Genmon project using gengpio.py.  I disabled the fancontrol code and then set all pins=0 in the gengpio.conf with the exception of the ER_PITEMP.  I used the same GPIO pin that fancontrol used on the breadboard.  I set the temp level low enough to make sure the fan would run.  It was not turning on the fan, so I set debug=True, to see what may be going on.
![image](https://github.com/jgyates/genmon/assets/153251506/654aac43-68a2-4c53-9514-41e8b11b2e9c)

I'm not sure why the InitGPIO and SetGPIO are issued (like I said, I set all config items to zero except the ER_PITEMP).  

More concerning related to the fan not turning on, the SetGPIO was getting an error.  Looking at the code for the CPU temp block (lines 366-373 of gengpio.py) reference ER_GENMON instead of ER_PITEMP.  I updated the two references and now the fan runs (SetGPIO sets to high and the fan runs, then when temp drops the SetGPIO sets to low and fan turns off).

This may not have been discovered, but I set ER_GENMON=0 in the gengpio.conf.  When the SetGPIO was issued using the ER_GENMON at zero, the error (Error: pin = 0 in SetGPIO) was issued.

I will let you determine if the intention was to use ER_GENMON or if it should have been ER_PITEMP.

**Comment by jgyates** [comment]
Thanks for finding this. I updated the code, let me know if you have any other issues.
